
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `InboundItem` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model InboundItem
 * 
 */
export type InboundItemModel = runtime.Types.Result.DefaultSelection<Prisma.$InboundItemPayload>

export type AggregateInboundItem = {
  _count: InboundItemCountAggregateOutputType | null
  _avg: InboundItemAvgAggregateOutputType | null
  _sum: InboundItemSumAggregateOutputType | null
  _min: InboundItemMinAggregateOutputType | null
  _max: InboundItemMaxAggregateOutputType | null
}

export type InboundItemAvgAggregateOutputType = {
  expectedQuantity: number | null
  receivedQuantity: number | null
  acceptedQuantity: number | null
  rejectedQuantity: number | null
}

export type InboundItemSumAggregateOutputType = {
  expectedQuantity: number | null
  receivedQuantity: number | null
  acceptedQuantity: number | null
  rejectedQuantity: number | null
}

export type InboundItemMinAggregateOutputType = {
  id: string | null
  inboundId: string | null
  itemId: string | null
  expectedQuantity: number | null
  receivedQuantity: number | null
  acceptedQuantity: number | null
  rejectedQuantity: number | null
  notes: string | null
  discrepancyType: $Enums.InboundDiscrepancyType | null
  discrepancyReason: string | null
  discrepancyAction: $Enums.DiscrepancyResolution | null
  discrepancyDocumentUrl: string | null
}

export type InboundItemMaxAggregateOutputType = {
  id: string | null
  inboundId: string | null
  itemId: string | null
  expectedQuantity: number | null
  receivedQuantity: number | null
  acceptedQuantity: number | null
  rejectedQuantity: number | null
  notes: string | null
  discrepancyType: $Enums.InboundDiscrepancyType | null
  discrepancyReason: string | null
  discrepancyAction: $Enums.DiscrepancyResolution | null
  discrepancyDocumentUrl: string | null
}

export type InboundItemCountAggregateOutputType = {
  id: number
  inboundId: number
  itemId: number
  expectedQuantity: number
  receivedQuantity: number
  acceptedQuantity: number
  rejectedQuantity: number
  notes: number
  discrepancyType: number
  discrepancyReason: number
  discrepancyAction: number
  discrepancyDocumentUrl: number
  _all: number
}


export type InboundItemAvgAggregateInputType = {
  expectedQuantity?: true
  receivedQuantity?: true
  acceptedQuantity?: true
  rejectedQuantity?: true
}

export type InboundItemSumAggregateInputType = {
  expectedQuantity?: true
  receivedQuantity?: true
  acceptedQuantity?: true
  rejectedQuantity?: true
}

export type InboundItemMinAggregateInputType = {
  id?: true
  inboundId?: true
  itemId?: true
  expectedQuantity?: true
  receivedQuantity?: true
  acceptedQuantity?: true
  rejectedQuantity?: true
  notes?: true
  discrepancyType?: true
  discrepancyReason?: true
  discrepancyAction?: true
  discrepancyDocumentUrl?: true
}

export type InboundItemMaxAggregateInputType = {
  id?: true
  inboundId?: true
  itemId?: true
  expectedQuantity?: true
  receivedQuantity?: true
  acceptedQuantity?: true
  rejectedQuantity?: true
  notes?: true
  discrepancyType?: true
  discrepancyReason?: true
  discrepancyAction?: true
  discrepancyDocumentUrl?: true
}

export type InboundItemCountAggregateInputType = {
  id?: true
  inboundId?: true
  itemId?: true
  expectedQuantity?: true
  receivedQuantity?: true
  acceptedQuantity?: true
  rejectedQuantity?: true
  notes?: true
  discrepancyType?: true
  discrepancyReason?: true
  discrepancyAction?: true
  discrepancyDocumentUrl?: true
  _all?: true
}

export type InboundItemAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which InboundItem to aggregate.
   */
  where?: Prisma.InboundItemWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of InboundItems to fetch.
   */
  orderBy?: Prisma.InboundItemOrderByWithRelationInput | Prisma.InboundItemOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.InboundItemWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` InboundItems from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` InboundItems.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned InboundItems
  **/
  _count?: true | InboundItemCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: InboundItemAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: InboundItemSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: InboundItemMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: InboundItemMaxAggregateInputType
}

export type GetInboundItemAggregateType<T extends InboundItemAggregateArgs> = {
      [P in keyof T & keyof AggregateInboundItem]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateInboundItem[P]>
    : Prisma.GetScalarType<T[P], AggregateInboundItem[P]>
}




export type InboundItemGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.InboundItemWhereInput
  orderBy?: Prisma.InboundItemOrderByWithAggregationInput | Prisma.InboundItemOrderByWithAggregationInput[]
  by: Prisma.InboundItemScalarFieldEnum[] | Prisma.InboundItemScalarFieldEnum
  having?: Prisma.InboundItemScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: InboundItemCountAggregateInputType | true
  _avg?: InboundItemAvgAggregateInputType
  _sum?: InboundItemSumAggregateInputType
  _min?: InboundItemMinAggregateInputType
  _max?: InboundItemMaxAggregateInputType
}

export type InboundItemGroupByOutputType = {
  id: string
  inboundId: string
  itemId: string
  expectedQuantity: number
  receivedQuantity: number
  acceptedQuantity: number
  rejectedQuantity: number
  notes: string | null
  discrepancyType: $Enums.InboundDiscrepancyType
  discrepancyReason: string | null
  discrepancyAction: $Enums.DiscrepancyResolution | null
  discrepancyDocumentUrl: string | null
  _count: InboundItemCountAggregateOutputType | null
  _avg: InboundItemAvgAggregateOutputType | null
  _sum: InboundItemSumAggregateOutputType | null
  _min: InboundItemMinAggregateOutputType | null
  _max: InboundItemMaxAggregateOutputType | null
}

type GetInboundItemGroupByPayload<T extends InboundItemGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<InboundItemGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof InboundItemGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], InboundItemGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], InboundItemGroupByOutputType[P]>
      }
    >
  >



export type InboundItemWhereInput = {
  AND?: Prisma.InboundItemWhereInput | Prisma.InboundItemWhereInput[]
  OR?: Prisma.InboundItemWhereInput[]
  NOT?: Prisma.InboundItemWhereInput | Prisma.InboundItemWhereInput[]
  id?: Prisma.StringFilter<"InboundItem"> | string
  inboundId?: Prisma.StringFilter<"InboundItem"> | string
  itemId?: Prisma.StringFilter<"InboundItem"> | string
  expectedQuantity?: Prisma.IntFilter<"InboundItem"> | number
  receivedQuantity?: Prisma.IntFilter<"InboundItem"> | number
  acceptedQuantity?: Prisma.IntFilter<"InboundItem"> | number
  rejectedQuantity?: Prisma.IntFilter<"InboundItem"> | number
  notes?: Prisma.StringNullableFilter<"InboundItem"> | string | null
  discrepancyType?: Prisma.EnumInboundDiscrepancyTypeFilter<"InboundItem"> | $Enums.InboundDiscrepancyType
  discrepancyReason?: Prisma.StringNullableFilter<"InboundItem"> | string | null
  discrepancyAction?: Prisma.EnumDiscrepancyResolutionNullableFilter<"InboundItem"> | $Enums.DiscrepancyResolution | null
  discrepancyDocumentUrl?: Prisma.StringNullableFilter<"InboundItem"> | string | null
  inbound?: Prisma.XOR<Prisma.InboundScalarRelationFilter, Prisma.InboundWhereInput>
  item?: Prisma.XOR<Prisma.ItemScalarRelationFilter, Prisma.ItemWhereInput>
}

export type InboundItemOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  inboundId?: Prisma.SortOrder
  itemId?: Prisma.SortOrder
  expectedQuantity?: Prisma.SortOrder
  receivedQuantity?: Prisma.SortOrder
  acceptedQuantity?: Prisma.SortOrder
  rejectedQuantity?: Prisma.SortOrder
  notes?: Prisma.SortOrderInput | Prisma.SortOrder
  discrepancyType?: Prisma.SortOrder
  discrepancyReason?: Prisma.SortOrderInput | Prisma.SortOrder
  discrepancyAction?: Prisma.SortOrderInput | Prisma.SortOrder
  discrepancyDocumentUrl?: Prisma.SortOrderInput | Prisma.SortOrder
  inbound?: Prisma.InboundOrderByWithRelationInput
  item?: Prisma.ItemOrderByWithRelationInput
}

export type InboundItemWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.InboundItemWhereInput | Prisma.InboundItemWhereInput[]
  OR?: Prisma.InboundItemWhereInput[]
  NOT?: Prisma.InboundItemWhereInput | Prisma.InboundItemWhereInput[]
  inboundId?: Prisma.StringFilter<"InboundItem"> | string
  itemId?: Prisma.StringFilter<"InboundItem"> | string
  expectedQuantity?: Prisma.IntFilter<"InboundItem"> | number
  receivedQuantity?: Prisma.IntFilter<"InboundItem"> | number
  acceptedQuantity?: Prisma.IntFilter<"InboundItem"> | number
  rejectedQuantity?: Prisma.IntFilter<"InboundItem"> | number
  notes?: Prisma.StringNullableFilter<"InboundItem"> | string | null
  discrepancyType?: Prisma.EnumInboundDiscrepancyTypeFilter<"InboundItem"> | $Enums.InboundDiscrepancyType
  discrepancyReason?: Prisma.StringNullableFilter<"InboundItem"> | string | null
  discrepancyAction?: Prisma.EnumDiscrepancyResolutionNullableFilter<"InboundItem"> | $Enums.DiscrepancyResolution | null
  discrepancyDocumentUrl?: Prisma.StringNullableFilter<"InboundItem"> | string | null
  inbound?: Prisma.XOR<Prisma.InboundScalarRelationFilter, Prisma.InboundWhereInput>
  item?: Prisma.XOR<Prisma.ItemScalarRelationFilter, Prisma.ItemWhereInput>
}, "id">

export type InboundItemOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  inboundId?: Prisma.SortOrder
  itemId?: Prisma.SortOrder
  expectedQuantity?: Prisma.SortOrder
  receivedQuantity?: Prisma.SortOrder
  acceptedQuantity?: Prisma.SortOrder
  rejectedQuantity?: Prisma.SortOrder
  notes?: Prisma.SortOrderInput | Prisma.SortOrder
  discrepancyType?: Prisma.SortOrder
  discrepancyReason?: Prisma.SortOrderInput | Prisma.SortOrder
  discrepancyAction?: Prisma.SortOrderInput | Prisma.SortOrder
  discrepancyDocumentUrl?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.InboundItemCountOrderByAggregateInput
  _avg?: Prisma.InboundItemAvgOrderByAggregateInput
  _max?: Prisma.InboundItemMaxOrderByAggregateInput
  _min?: Prisma.InboundItemMinOrderByAggregateInput
  _sum?: Prisma.InboundItemSumOrderByAggregateInput
}

export type InboundItemScalarWhereWithAggregatesInput = {
  AND?: Prisma.InboundItemScalarWhereWithAggregatesInput | Prisma.InboundItemScalarWhereWithAggregatesInput[]
  OR?: Prisma.InboundItemScalarWhereWithAggregatesInput[]
  NOT?: Prisma.InboundItemScalarWhereWithAggregatesInput | Prisma.InboundItemScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"InboundItem"> | string
  inboundId?: Prisma.StringWithAggregatesFilter<"InboundItem"> | string
  itemId?: Prisma.StringWithAggregatesFilter<"InboundItem"> | string
  expectedQuantity?: Prisma.IntWithAggregatesFilter<"InboundItem"> | number
  receivedQuantity?: Prisma.IntWithAggregatesFilter<"InboundItem"> | number
  acceptedQuantity?: Prisma.IntWithAggregatesFilter<"InboundItem"> | number
  rejectedQuantity?: Prisma.IntWithAggregatesFilter<"InboundItem"> | number
  notes?: Prisma.StringNullableWithAggregatesFilter<"InboundItem"> | string | null
  discrepancyType?: Prisma.EnumInboundDiscrepancyTypeWithAggregatesFilter<"InboundItem"> | $Enums.InboundDiscrepancyType
  discrepancyReason?: Prisma.StringNullableWithAggregatesFilter<"InboundItem"> | string | null
  discrepancyAction?: Prisma.EnumDiscrepancyResolutionNullableWithAggregatesFilter<"InboundItem"> | $Enums.DiscrepancyResolution | null
  discrepancyDocumentUrl?: Prisma.StringNullableWithAggregatesFilter<"InboundItem"> | string | null
}

export type InboundItemCreateInput = {
  id?: string
  expectedQuantity: number
  receivedQuantity: number
  acceptedQuantity?: number
  rejectedQuantity?: number
  notes?: string | null
  discrepancyType?: $Enums.InboundDiscrepancyType
  discrepancyReason?: string | null
  discrepancyAction?: $Enums.DiscrepancyResolution | null
  discrepancyDocumentUrl?: string | null
  inbound: Prisma.InboundCreateNestedOneWithoutItemsInput
  item: Prisma.ItemCreateNestedOneWithoutInboundItemsInput
}

export type InboundItemUncheckedCreateInput = {
  id?: string
  inboundId: string
  itemId: string
  expectedQuantity: number
  receivedQuantity: number
  acceptedQuantity?: number
  rejectedQuantity?: number
  notes?: string | null
  discrepancyType?: $Enums.InboundDiscrepancyType
  discrepancyReason?: string | null
  discrepancyAction?: $Enums.DiscrepancyResolution | null
  discrepancyDocumentUrl?: string | null
}

export type InboundItemUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  expectedQuantity?: Prisma.IntFieldUpdateOperationsInput | number
  receivedQuantity?: Prisma.IntFieldUpdateOperationsInput | number
  acceptedQuantity?: Prisma.IntFieldUpdateOperationsInput | number
  rejectedQuantity?: Prisma.IntFieldUpdateOperationsInput | number
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  discrepancyType?: Prisma.EnumInboundDiscrepancyTypeFieldUpdateOperationsInput | $Enums.InboundDiscrepancyType
  discrepancyReason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  discrepancyAction?: Prisma.NullableEnumDiscrepancyResolutionFieldUpdateOperationsInput | $Enums.DiscrepancyResolution | null
  discrepancyDocumentUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  inbound?: Prisma.InboundUpdateOneRequiredWithoutItemsNestedInput
  item?: Prisma.ItemUpdateOneRequiredWithoutInboundItemsNestedInput
}

export type InboundItemUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  inboundId?: Prisma.StringFieldUpdateOperationsInput | string
  itemId?: Prisma.StringFieldUpdateOperationsInput | string
  expectedQuantity?: Prisma.IntFieldUpdateOperationsInput | number
  receivedQuantity?: Prisma.IntFieldUpdateOperationsInput | number
  acceptedQuantity?: Prisma.IntFieldUpdateOperationsInput | number
  rejectedQuantity?: Prisma.IntFieldUpdateOperationsInput | number
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  discrepancyType?: Prisma.EnumInboundDiscrepancyTypeFieldUpdateOperationsInput | $Enums.InboundDiscrepancyType
  discrepancyReason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  discrepancyAction?: Prisma.NullableEnumDiscrepancyResolutionFieldUpdateOperationsInput | $Enums.DiscrepancyResolution | null
  discrepancyDocumentUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type InboundItemCreateManyInput = {
  id?: string
  inboundId: string
  itemId: string
  expectedQuantity: number
  receivedQuantity: number
  acceptedQuantity?: number
  rejectedQuantity?: number
  notes?: string | null
  discrepancyType?: $Enums.InboundDiscrepancyType
  discrepancyReason?: string | null
  discrepancyAction?: $Enums.DiscrepancyResolution | null
  discrepancyDocumentUrl?: string | null
}

export type InboundItemUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  expectedQuantity?: Prisma.IntFieldUpdateOperationsInput | number
  receivedQuantity?: Prisma.IntFieldUpdateOperationsInput | number
  acceptedQuantity?: Prisma.IntFieldUpdateOperationsInput | number
  rejectedQuantity?: Prisma.IntFieldUpdateOperationsInput | number
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  discrepancyType?: Prisma.EnumInboundDiscrepancyTypeFieldUpdateOperationsInput | $Enums.InboundDiscrepancyType
  discrepancyReason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  discrepancyAction?: Prisma.NullableEnumDiscrepancyResolutionFieldUpdateOperationsInput | $Enums.DiscrepancyResolution | null
  discrepancyDocumentUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type InboundItemUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  inboundId?: Prisma.StringFieldUpdateOperationsInput | string
  itemId?: Prisma.StringFieldUpdateOperationsInput | string
  expectedQuantity?: Prisma.IntFieldUpdateOperationsInput | number
  receivedQuantity?: Prisma.IntFieldUpdateOperationsInput | number
  acceptedQuantity?: Prisma.IntFieldUpdateOperationsInput | number
  rejectedQuantity?: Prisma.IntFieldUpdateOperationsInput | number
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  discrepancyType?: Prisma.EnumInboundDiscrepancyTypeFieldUpdateOperationsInput | $Enums.InboundDiscrepancyType
  discrepancyReason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  discrepancyAction?: Prisma.NullableEnumDiscrepancyResolutionFieldUpdateOperationsInput | $Enums.DiscrepancyResolution | null
  discrepancyDocumentUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type InboundItemListRelationFilter = {
  every?: Prisma.InboundItemWhereInput
  some?: Prisma.InboundItemWhereInput
  none?: Prisma.InboundItemWhereInput
}

export type InboundItemOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type InboundItemCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  inboundId?: Prisma.SortOrder
  itemId?: Prisma.SortOrder
  expectedQuantity?: Prisma.SortOrder
  receivedQuantity?: Prisma.SortOrder
  acceptedQuantity?: Prisma.SortOrder
  rejectedQuantity?: Prisma.SortOrder
  notes?: Prisma.SortOrder
  discrepancyType?: Prisma.SortOrder
  discrepancyReason?: Prisma.SortOrder
  discrepancyAction?: Prisma.SortOrder
  discrepancyDocumentUrl?: Prisma.SortOrder
}

export type InboundItemAvgOrderByAggregateInput = {
  expectedQuantity?: Prisma.SortOrder
  receivedQuantity?: Prisma.SortOrder
  acceptedQuantity?: Prisma.SortOrder
  rejectedQuantity?: Prisma.SortOrder
}

export type InboundItemMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  inboundId?: Prisma.SortOrder
  itemId?: Prisma.SortOrder
  expectedQuantity?: Prisma.SortOrder
  receivedQuantity?: Prisma.SortOrder
  acceptedQuantity?: Prisma.SortOrder
  rejectedQuantity?: Prisma.SortOrder
  notes?: Prisma.SortOrder
  discrepancyType?: Prisma.SortOrder
  discrepancyReason?: Prisma.SortOrder
  discrepancyAction?: Prisma.SortOrder
  discrepancyDocumentUrl?: Prisma.SortOrder
}

export type InboundItemMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  inboundId?: Prisma.SortOrder
  itemId?: Prisma.SortOrder
  expectedQuantity?: Prisma.SortOrder
  receivedQuantity?: Prisma.SortOrder
  acceptedQuantity?: Prisma.SortOrder
  rejectedQuantity?: Prisma.SortOrder
  notes?: Prisma.SortOrder
  discrepancyType?: Prisma.SortOrder
  discrepancyReason?: Prisma.SortOrder
  discrepancyAction?: Prisma.SortOrder
  discrepancyDocumentUrl?: Prisma.SortOrder
}

export type InboundItemSumOrderByAggregateInput = {
  expectedQuantity?: Prisma.SortOrder
  receivedQuantity?: Prisma.SortOrder
  acceptedQuantity?: Prisma.SortOrder
  rejectedQuantity?: Prisma.SortOrder
}

export type InboundItemCreateNestedManyWithoutItemInput = {
  create?: Prisma.XOR<Prisma.InboundItemCreateWithoutItemInput, Prisma.InboundItemUncheckedCreateWithoutItemInput> | Prisma.InboundItemCreateWithoutItemInput[] | Prisma.InboundItemUncheckedCreateWithoutItemInput[]
  connectOrCreate?: Prisma.InboundItemCreateOrConnectWithoutItemInput | Prisma.InboundItemCreateOrConnectWithoutItemInput[]
  createMany?: Prisma.InboundItemCreateManyItemInputEnvelope
  connect?: Prisma.InboundItemWhereUniqueInput | Prisma.InboundItemWhereUniqueInput[]
}

export type InboundItemUncheckedCreateNestedManyWithoutItemInput = {
  create?: Prisma.XOR<Prisma.InboundItemCreateWithoutItemInput, Prisma.InboundItemUncheckedCreateWithoutItemInput> | Prisma.InboundItemCreateWithoutItemInput[] | Prisma.InboundItemUncheckedCreateWithoutItemInput[]
  connectOrCreate?: Prisma.InboundItemCreateOrConnectWithoutItemInput | Prisma.InboundItemCreateOrConnectWithoutItemInput[]
  createMany?: Prisma.InboundItemCreateManyItemInputEnvelope
  connect?: Prisma.InboundItemWhereUniqueInput | Prisma.InboundItemWhereUniqueInput[]
}

export type InboundItemUpdateManyWithoutItemNestedInput = {
  create?: Prisma.XOR<Prisma.InboundItemCreateWithoutItemInput, Prisma.InboundItemUncheckedCreateWithoutItemInput> | Prisma.InboundItemCreateWithoutItemInput[] | Prisma.InboundItemUncheckedCreateWithoutItemInput[]
  connectOrCreate?: Prisma.InboundItemCreateOrConnectWithoutItemInput | Prisma.InboundItemCreateOrConnectWithoutItemInput[]
  upsert?: Prisma.InboundItemUpsertWithWhereUniqueWithoutItemInput | Prisma.InboundItemUpsertWithWhereUniqueWithoutItemInput[]
  createMany?: Prisma.InboundItemCreateManyItemInputEnvelope
  set?: Prisma.InboundItemWhereUniqueInput | Prisma.InboundItemWhereUniqueInput[]
  disconnect?: Prisma.InboundItemWhereUniqueInput | Prisma.InboundItemWhereUniqueInput[]
  delete?: Prisma.InboundItemWhereUniqueInput | Prisma.InboundItemWhereUniqueInput[]
  connect?: Prisma.InboundItemWhereUniqueInput | Prisma.InboundItemWhereUniqueInput[]
  update?: Prisma.InboundItemUpdateWithWhereUniqueWithoutItemInput | Prisma.InboundItemUpdateWithWhereUniqueWithoutItemInput[]
  updateMany?: Prisma.InboundItemUpdateManyWithWhereWithoutItemInput | Prisma.InboundItemUpdateManyWithWhereWithoutItemInput[]
  deleteMany?: Prisma.InboundItemScalarWhereInput | Prisma.InboundItemScalarWhereInput[]
}

export type InboundItemUncheckedUpdateManyWithoutItemNestedInput = {
  create?: Prisma.XOR<Prisma.InboundItemCreateWithoutItemInput, Prisma.InboundItemUncheckedCreateWithoutItemInput> | Prisma.InboundItemCreateWithoutItemInput[] | Prisma.InboundItemUncheckedCreateWithoutItemInput[]
  connectOrCreate?: Prisma.InboundItemCreateOrConnectWithoutItemInput | Prisma.InboundItemCreateOrConnectWithoutItemInput[]
  upsert?: Prisma.InboundItemUpsertWithWhereUniqueWithoutItemInput | Prisma.InboundItemUpsertWithWhereUniqueWithoutItemInput[]
  createMany?: Prisma.InboundItemCreateManyItemInputEnvelope
  set?: Prisma.InboundItemWhereUniqueInput | Prisma.InboundItemWhereUniqueInput[]
  disconnect?: Prisma.InboundItemWhereUniqueInput | Prisma.InboundItemWhereUniqueInput[]
  delete?: Prisma.InboundItemWhereUniqueInput | Prisma.InboundItemWhereUniqueInput[]
  connect?: Prisma.InboundItemWhereUniqueInput | Prisma.InboundItemWhereUniqueInput[]
  update?: Prisma.InboundItemUpdateWithWhereUniqueWithoutItemInput | Prisma.InboundItemUpdateWithWhereUniqueWithoutItemInput[]
  updateMany?: Prisma.InboundItemUpdateManyWithWhereWithoutItemInput | Prisma.InboundItemUpdateManyWithWhereWithoutItemInput[]
  deleteMany?: Prisma.InboundItemScalarWhereInput | Prisma.InboundItemScalarWhereInput[]
}

export type InboundItemCreateNestedManyWithoutInboundInput = {
  create?: Prisma.XOR<Prisma.InboundItemCreateWithoutInboundInput, Prisma.InboundItemUncheckedCreateWithoutInboundInput> | Prisma.InboundItemCreateWithoutInboundInput[] | Prisma.InboundItemUncheckedCreateWithoutInboundInput[]
  connectOrCreate?: Prisma.InboundItemCreateOrConnectWithoutInboundInput | Prisma.InboundItemCreateOrConnectWithoutInboundInput[]
  createMany?: Prisma.InboundItemCreateManyInboundInputEnvelope
  connect?: Prisma.InboundItemWhereUniqueInput | Prisma.InboundItemWhereUniqueInput[]
}

export type InboundItemUncheckedCreateNestedManyWithoutInboundInput = {
  create?: Prisma.XOR<Prisma.InboundItemCreateWithoutInboundInput, Prisma.InboundItemUncheckedCreateWithoutInboundInput> | Prisma.InboundItemCreateWithoutInboundInput[] | Prisma.InboundItemUncheckedCreateWithoutInboundInput[]
  connectOrCreate?: Prisma.InboundItemCreateOrConnectWithoutInboundInput | Prisma.InboundItemCreateOrConnectWithoutInboundInput[]
  createMany?: Prisma.InboundItemCreateManyInboundInputEnvelope
  connect?: Prisma.InboundItemWhereUniqueInput | Prisma.InboundItemWhereUniqueInput[]
}

export type InboundItemUpdateManyWithoutInboundNestedInput = {
  create?: Prisma.XOR<Prisma.InboundItemCreateWithoutInboundInput, Prisma.InboundItemUncheckedCreateWithoutInboundInput> | Prisma.InboundItemCreateWithoutInboundInput[] | Prisma.InboundItemUncheckedCreateWithoutInboundInput[]
  connectOrCreate?: Prisma.InboundItemCreateOrConnectWithoutInboundInput | Prisma.InboundItemCreateOrConnectWithoutInboundInput[]
  upsert?: Prisma.InboundItemUpsertWithWhereUniqueWithoutInboundInput | Prisma.InboundItemUpsertWithWhereUniqueWithoutInboundInput[]
  createMany?: Prisma.InboundItemCreateManyInboundInputEnvelope
  set?: Prisma.InboundItemWhereUniqueInput | Prisma.InboundItemWhereUniqueInput[]
  disconnect?: Prisma.InboundItemWhereUniqueInput | Prisma.InboundItemWhereUniqueInput[]
  delete?: Prisma.InboundItemWhereUniqueInput | Prisma.InboundItemWhereUniqueInput[]
  connect?: Prisma.InboundItemWhereUniqueInput | Prisma.InboundItemWhereUniqueInput[]
  update?: Prisma.InboundItemUpdateWithWhereUniqueWithoutInboundInput | Prisma.InboundItemUpdateWithWhereUniqueWithoutInboundInput[]
  updateMany?: Prisma.InboundItemUpdateManyWithWhereWithoutInboundInput | Prisma.InboundItemUpdateManyWithWhereWithoutInboundInput[]
  deleteMany?: Prisma.InboundItemScalarWhereInput | Prisma.InboundItemScalarWhereInput[]
}

export type InboundItemUncheckedUpdateManyWithoutInboundNestedInput = {
  create?: Prisma.XOR<Prisma.InboundItemCreateWithoutInboundInput, Prisma.InboundItemUncheckedCreateWithoutInboundInput> | Prisma.InboundItemCreateWithoutInboundInput[] | Prisma.InboundItemUncheckedCreateWithoutInboundInput[]
  connectOrCreate?: Prisma.InboundItemCreateOrConnectWithoutInboundInput | Prisma.InboundItemCreateOrConnectWithoutInboundInput[]
  upsert?: Prisma.InboundItemUpsertWithWhereUniqueWithoutInboundInput | Prisma.InboundItemUpsertWithWhereUniqueWithoutInboundInput[]
  createMany?: Prisma.InboundItemCreateManyInboundInputEnvelope
  set?: Prisma.InboundItemWhereUniqueInput | Prisma.InboundItemWhereUniqueInput[]
  disconnect?: Prisma.InboundItemWhereUniqueInput | Prisma.InboundItemWhereUniqueInput[]
  delete?: Prisma.InboundItemWhereUniqueInput | Prisma.InboundItemWhereUniqueInput[]
  connect?: Prisma.InboundItemWhereUniqueInput | Prisma.InboundItemWhereUniqueInput[]
  update?: Prisma.InboundItemUpdateWithWhereUniqueWithoutInboundInput | Prisma.InboundItemUpdateWithWhereUniqueWithoutInboundInput[]
  updateMany?: Prisma.InboundItemUpdateManyWithWhereWithoutInboundInput | Prisma.InboundItemUpdateManyWithWhereWithoutInboundInput[]
  deleteMany?: Prisma.InboundItemScalarWhereInput | Prisma.InboundItemScalarWhereInput[]
}

export type EnumInboundDiscrepancyTypeFieldUpdateOperationsInput = {
  set?: $Enums.InboundDiscrepancyType
}

export type NullableEnumDiscrepancyResolutionFieldUpdateOperationsInput = {
  set?: $Enums.DiscrepancyResolution | null
}

export type InboundItemCreateWithoutItemInput = {
  id?: string
  expectedQuantity: number
  receivedQuantity: number
  acceptedQuantity?: number
  rejectedQuantity?: number
  notes?: string | null
  discrepancyType?: $Enums.InboundDiscrepancyType
  discrepancyReason?: string | null
  discrepancyAction?: $Enums.DiscrepancyResolution | null
  discrepancyDocumentUrl?: string | null
  inbound: Prisma.InboundCreateNestedOneWithoutItemsInput
}

export type InboundItemUncheckedCreateWithoutItemInput = {
  id?: string
  inboundId: string
  expectedQuantity: number
  receivedQuantity: number
  acceptedQuantity?: number
  rejectedQuantity?: number
  notes?: string | null
  discrepancyType?: $Enums.InboundDiscrepancyType
  discrepancyReason?: string | null
  discrepancyAction?: $Enums.DiscrepancyResolution | null
  discrepancyDocumentUrl?: string | null
}

export type InboundItemCreateOrConnectWithoutItemInput = {
  where: Prisma.InboundItemWhereUniqueInput
  create: Prisma.XOR<Prisma.InboundItemCreateWithoutItemInput, Prisma.InboundItemUncheckedCreateWithoutItemInput>
}

export type InboundItemCreateManyItemInputEnvelope = {
  data: Prisma.InboundItemCreateManyItemInput | Prisma.InboundItemCreateManyItemInput[]
  skipDuplicates?: boolean
}

export type InboundItemUpsertWithWhereUniqueWithoutItemInput = {
  where: Prisma.InboundItemWhereUniqueInput
  update: Prisma.XOR<Prisma.InboundItemUpdateWithoutItemInput, Prisma.InboundItemUncheckedUpdateWithoutItemInput>
  create: Prisma.XOR<Prisma.InboundItemCreateWithoutItemInput, Prisma.InboundItemUncheckedCreateWithoutItemInput>
}

export type InboundItemUpdateWithWhereUniqueWithoutItemInput = {
  where: Prisma.InboundItemWhereUniqueInput
  data: Prisma.XOR<Prisma.InboundItemUpdateWithoutItemInput, Prisma.InboundItemUncheckedUpdateWithoutItemInput>
}

export type InboundItemUpdateManyWithWhereWithoutItemInput = {
  where: Prisma.InboundItemScalarWhereInput
  data: Prisma.XOR<Prisma.InboundItemUpdateManyMutationInput, Prisma.InboundItemUncheckedUpdateManyWithoutItemInput>
}

export type InboundItemScalarWhereInput = {
  AND?: Prisma.InboundItemScalarWhereInput | Prisma.InboundItemScalarWhereInput[]
  OR?: Prisma.InboundItemScalarWhereInput[]
  NOT?: Prisma.InboundItemScalarWhereInput | Prisma.InboundItemScalarWhereInput[]
  id?: Prisma.StringFilter<"InboundItem"> | string
  inboundId?: Prisma.StringFilter<"InboundItem"> | string
  itemId?: Prisma.StringFilter<"InboundItem"> | string
  expectedQuantity?: Prisma.IntFilter<"InboundItem"> | number
  receivedQuantity?: Prisma.IntFilter<"InboundItem"> | number
  acceptedQuantity?: Prisma.IntFilter<"InboundItem"> | number
  rejectedQuantity?: Prisma.IntFilter<"InboundItem"> | number
  notes?: Prisma.StringNullableFilter<"InboundItem"> | string | null
  discrepancyType?: Prisma.EnumInboundDiscrepancyTypeFilter<"InboundItem"> | $Enums.InboundDiscrepancyType
  discrepancyReason?: Prisma.StringNullableFilter<"InboundItem"> | string | null
  discrepancyAction?: Prisma.EnumDiscrepancyResolutionNullableFilter<"InboundItem"> | $Enums.DiscrepancyResolution | null
  discrepancyDocumentUrl?: Prisma.StringNullableFilter<"InboundItem"> | string | null
}

export type InboundItemCreateWithoutInboundInput = {
  id?: string
  expectedQuantity: number
  receivedQuantity: number
  acceptedQuantity?: number
  rejectedQuantity?: number
  notes?: string | null
  discrepancyType?: $Enums.InboundDiscrepancyType
  discrepancyReason?: string | null
  discrepancyAction?: $Enums.DiscrepancyResolution | null
  discrepancyDocumentUrl?: string | null
  item: Prisma.ItemCreateNestedOneWithoutInboundItemsInput
}

export type InboundItemUncheckedCreateWithoutInboundInput = {
  id?: string
  itemId: string
  expectedQuantity: number
  receivedQuantity: number
  acceptedQuantity?: number
  rejectedQuantity?: number
  notes?: string | null
  discrepancyType?: $Enums.InboundDiscrepancyType
  discrepancyReason?: string | null
  discrepancyAction?: $Enums.DiscrepancyResolution | null
  discrepancyDocumentUrl?: string | null
}

export type InboundItemCreateOrConnectWithoutInboundInput = {
  where: Prisma.InboundItemWhereUniqueInput
  create: Prisma.XOR<Prisma.InboundItemCreateWithoutInboundInput, Prisma.InboundItemUncheckedCreateWithoutInboundInput>
}

export type InboundItemCreateManyInboundInputEnvelope = {
  data: Prisma.InboundItemCreateManyInboundInput | Prisma.InboundItemCreateManyInboundInput[]
  skipDuplicates?: boolean
}

export type InboundItemUpsertWithWhereUniqueWithoutInboundInput = {
  where: Prisma.InboundItemWhereUniqueInput
  update: Prisma.XOR<Prisma.InboundItemUpdateWithoutInboundInput, Prisma.InboundItemUncheckedUpdateWithoutInboundInput>
  create: Prisma.XOR<Prisma.InboundItemCreateWithoutInboundInput, Prisma.InboundItemUncheckedCreateWithoutInboundInput>
}

export type InboundItemUpdateWithWhereUniqueWithoutInboundInput = {
  where: Prisma.InboundItemWhereUniqueInput
  data: Prisma.XOR<Prisma.InboundItemUpdateWithoutInboundInput, Prisma.InboundItemUncheckedUpdateWithoutInboundInput>
}

export type InboundItemUpdateManyWithWhereWithoutInboundInput = {
  where: Prisma.InboundItemScalarWhereInput
  data: Prisma.XOR<Prisma.InboundItemUpdateManyMutationInput, Prisma.InboundItemUncheckedUpdateManyWithoutInboundInput>
}

export type InboundItemCreateManyItemInput = {
  id?: string
  inboundId: string
  expectedQuantity: number
  receivedQuantity: number
  acceptedQuantity?: number
  rejectedQuantity?: number
  notes?: string | null
  discrepancyType?: $Enums.InboundDiscrepancyType
  discrepancyReason?: string | null
  discrepancyAction?: $Enums.DiscrepancyResolution | null
  discrepancyDocumentUrl?: string | null
}

export type InboundItemUpdateWithoutItemInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  expectedQuantity?: Prisma.IntFieldUpdateOperationsInput | number
  receivedQuantity?: Prisma.IntFieldUpdateOperationsInput | number
  acceptedQuantity?: Prisma.IntFieldUpdateOperationsInput | number
  rejectedQuantity?: Prisma.IntFieldUpdateOperationsInput | number
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  discrepancyType?: Prisma.EnumInboundDiscrepancyTypeFieldUpdateOperationsInput | $Enums.InboundDiscrepancyType
  discrepancyReason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  discrepancyAction?: Prisma.NullableEnumDiscrepancyResolutionFieldUpdateOperationsInput | $Enums.DiscrepancyResolution | null
  discrepancyDocumentUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  inbound?: Prisma.InboundUpdateOneRequiredWithoutItemsNestedInput
}

export type InboundItemUncheckedUpdateWithoutItemInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  inboundId?: Prisma.StringFieldUpdateOperationsInput | string
  expectedQuantity?: Prisma.IntFieldUpdateOperationsInput | number
  receivedQuantity?: Prisma.IntFieldUpdateOperationsInput | number
  acceptedQuantity?: Prisma.IntFieldUpdateOperationsInput | number
  rejectedQuantity?: Prisma.IntFieldUpdateOperationsInput | number
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  discrepancyType?: Prisma.EnumInboundDiscrepancyTypeFieldUpdateOperationsInput | $Enums.InboundDiscrepancyType
  discrepancyReason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  discrepancyAction?: Prisma.NullableEnumDiscrepancyResolutionFieldUpdateOperationsInput | $Enums.DiscrepancyResolution | null
  discrepancyDocumentUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type InboundItemUncheckedUpdateManyWithoutItemInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  inboundId?: Prisma.StringFieldUpdateOperationsInput | string
  expectedQuantity?: Prisma.IntFieldUpdateOperationsInput | number
  receivedQuantity?: Prisma.IntFieldUpdateOperationsInput | number
  acceptedQuantity?: Prisma.IntFieldUpdateOperationsInput | number
  rejectedQuantity?: Prisma.IntFieldUpdateOperationsInput | number
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  discrepancyType?: Prisma.EnumInboundDiscrepancyTypeFieldUpdateOperationsInput | $Enums.InboundDiscrepancyType
  discrepancyReason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  discrepancyAction?: Prisma.NullableEnumDiscrepancyResolutionFieldUpdateOperationsInput | $Enums.DiscrepancyResolution | null
  discrepancyDocumentUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type InboundItemCreateManyInboundInput = {
  id?: string
  itemId: string
  expectedQuantity: number
  receivedQuantity: number
  acceptedQuantity?: number
  rejectedQuantity?: number
  notes?: string | null
  discrepancyType?: $Enums.InboundDiscrepancyType
  discrepancyReason?: string | null
  discrepancyAction?: $Enums.DiscrepancyResolution | null
  discrepancyDocumentUrl?: string | null
}

export type InboundItemUpdateWithoutInboundInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  expectedQuantity?: Prisma.IntFieldUpdateOperationsInput | number
  receivedQuantity?: Prisma.IntFieldUpdateOperationsInput | number
  acceptedQuantity?: Prisma.IntFieldUpdateOperationsInput | number
  rejectedQuantity?: Prisma.IntFieldUpdateOperationsInput | number
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  discrepancyType?: Prisma.EnumInboundDiscrepancyTypeFieldUpdateOperationsInput | $Enums.InboundDiscrepancyType
  discrepancyReason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  discrepancyAction?: Prisma.NullableEnumDiscrepancyResolutionFieldUpdateOperationsInput | $Enums.DiscrepancyResolution | null
  discrepancyDocumentUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  item?: Prisma.ItemUpdateOneRequiredWithoutInboundItemsNestedInput
}

export type InboundItemUncheckedUpdateWithoutInboundInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  itemId?: Prisma.StringFieldUpdateOperationsInput | string
  expectedQuantity?: Prisma.IntFieldUpdateOperationsInput | number
  receivedQuantity?: Prisma.IntFieldUpdateOperationsInput | number
  acceptedQuantity?: Prisma.IntFieldUpdateOperationsInput | number
  rejectedQuantity?: Prisma.IntFieldUpdateOperationsInput | number
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  discrepancyType?: Prisma.EnumInboundDiscrepancyTypeFieldUpdateOperationsInput | $Enums.InboundDiscrepancyType
  discrepancyReason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  discrepancyAction?: Prisma.NullableEnumDiscrepancyResolutionFieldUpdateOperationsInput | $Enums.DiscrepancyResolution | null
  discrepancyDocumentUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type InboundItemUncheckedUpdateManyWithoutInboundInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  itemId?: Prisma.StringFieldUpdateOperationsInput | string
  expectedQuantity?: Prisma.IntFieldUpdateOperationsInput | number
  receivedQuantity?: Prisma.IntFieldUpdateOperationsInput | number
  acceptedQuantity?: Prisma.IntFieldUpdateOperationsInput | number
  rejectedQuantity?: Prisma.IntFieldUpdateOperationsInput | number
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  discrepancyType?: Prisma.EnumInboundDiscrepancyTypeFieldUpdateOperationsInput | $Enums.InboundDiscrepancyType
  discrepancyReason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  discrepancyAction?: Prisma.NullableEnumDiscrepancyResolutionFieldUpdateOperationsInput | $Enums.DiscrepancyResolution | null
  discrepancyDocumentUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}



export type InboundItemSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  inboundId?: boolean
  itemId?: boolean
  expectedQuantity?: boolean
  receivedQuantity?: boolean
  acceptedQuantity?: boolean
  rejectedQuantity?: boolean
  notes?: boolean
  discrepancyType?: boolean
  discrepancyReason?: boolean
  discrepancyAction?: boolean
  discrepancyDocumentUrl?: boolean
  inbound?: boolean | Prisma.InboundDefaultArgs<ExtArgs>
  item?: boolean | Prisma.ItemDefaultArgs<ExtArgs>
}, ExtArgs["result"]["inboundItem"]>

export type InboundItemSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  inboundId?: boolean
  itemId?: boolean
  expectedQuantity?: boolean
  receivedQuantity?: boolean
  acceptedQuantity?: boolean
  rejectedQuantity?: boolean
  notes?: boolean
  discrepancyType?: boolean
  discrepancyReason?: boolean
  discrepancyAction?: boolean
  discrepancyDocumentUrl?: boolean
  inbound?: boolean | Prisma.InboundDefaultArgs<ExtArgs>
  item?: boolean | Prisma.ItemDefaultArgs<ExtArgs>
}, ExtArgs["result"]["inboundItem"]>

export type InboundItemSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  inboundId?: boolean
  itemId?: boolean
  expectedQuantity?: boolean
  receivedQuantity?: boolean
  acceptedQuantity?: boolean
  rejectedQuantity?: boolean
  notes?: boolean
  discrepancyType?: boolean
  discrepancyReason?: boolean
  discrepancyAction?: boolean
  discrepancyDocumentUrl?: boolean
  inbound?: boolean | Prisma.InboundDefaultArgs<ExtArgs>
  item?: boolean | Prisma.ItemDefaultArgs<ExtArgs>
}, ExtArgs["result"]["inboundItem"]>

export type InboundItemSelectScalar = {
  id?: boolean
  inboundId?: boolean
  itemId?: boolean
  expectedQuantity?: boolean
  receivedQuantity?: boolean
  acceptedQuantity?: boolean
  rejectedQuantity?: boolean
  notes?: boolean
  discrepancyType?: boolean
  discrepancyReason?: boolean
  discrepancyAction?: boolean
  discrepancyDocumentUrl?: boolean
}

export type InboundItemOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "inboundId" | "itemId" | "expectedQuantity" | "receivedQuantity" | "acceptedQuantity" | "rejectedQuantity" | "notes" | "discrepancyType" | "discrepancyReason" | "discrepancyAction" | "discrepancyDocumentUrl", ExtArgs["result"]["inboundItem"]>
export type InboundItemInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  inbound?: boolean | Prisma.InboundDefaultArgs<ExtArgs>
  item?: boolean | Prisma.ItemDefaultArgs<ExtArgs>
}
export type InboundItemIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  inbound?: boolean | Prisma.InboundDefaultArgs<ExtArgs>
  item?: boolean | Prisma.ItemDefaultArgs<ExtArgs>
}
export type InboundItemIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  inbound?: boolean | Prisma.InboundDefaultArgs<ExtArgs>
  item?: boolean | Prisma.ItemDefaultArgs<ExtArgs>
}

export type $InboundItemPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "InboundItem"
  objects: {
    inbound: Prisma.$InboundPayload<ExtArgs>
    item: Prisma.$ItemPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    inboundId: string
    itemId: string
    expectedQuantity: number
    receivedQuantity: number
    acceptedQuantity: number
    rejectedQuantity: number
    notes: string | null
    discrepancyType: $Enums.InboundDiscrepancyType
    discrepancyReason: string | null
    discrepancyAction: $Enums.DiscrepancyResolution | null
    discrepancyDocumentUrl: string | null
  }, ExtArgs["result"]["inboundItem"]>
  composites: {}
}

export type InboundItemGetPayload<S extends boolean | null | undefined | InboundItemDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$InboundItemPayload, S>

export type InboundItemCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<InboundItemFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: InboundItemCountAggregateInputType | true
  }

export interface InboundItemDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['InboundItem'], meta: { name: 'InboundItem' } }
  /**
   * Find zero or one InboundItem that matches the filter.
   * @param {InboundItemFindUniqueArgs} args - Arguments to find a InboundItem
   * @example
   * // Get one InboundItem
   * const inboundItem = await prisma.inboundItem.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends InboundItemFindUniqueArgs>(args: Prisma.SelectSubset<T, InboundItemFindUniqueArgs<ExtArgs>>): Prisma.Prisma__InboundItemClient<runtime.Types.Result.GetResult<Prisma.$InboundItemPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one InboundItem that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {InboundItemFindUniqueOrThrowArgs} args - Arguments to find a InboundItem
   * @example
   * // Get one InboundItem
   * const inboundItem = await prisma.inboundItem.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends InboundItemFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, InboundItemFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__InboundItemClient<runtime.Types.Result.GetResult<Prisma.$InboundItemPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first InboundItem that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {InboundItemFindFirstArgs} args - Arguments to find a InboundItem
   * @example
   * // Get one InboundItem
   * const inboundItem = await prisma.inboundItem.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends InboundItemFindFirstArgs>(args?: Prisma.SelectSubset<T, InboundItemFindFirstArgs<ExtArgs>>): Prisma.Prisma__InboundItemClient<runtime.Types.Result.GetResult<Prisma.$InboundItemPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first InboundItem that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {InboundItemFindFirstOrThrowArgs} args - Arguments to find a InboundItem
   * @example
   * // Get one InboundItem
   * const inboundItem = await prisma.inboundItem.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends InboundItemFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, InboundItemFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__InboundItemClient<runtime.Types.Result.GetResult<Prisma.$InboundItemPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more InboundItems that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {InboundItemFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all InboundItems
   * const inboundItems = await prisma.inboundItem.findMany()
   * 
   * // Get first 10 InboundItems
   * const inboundItems = await prisma.inboundItem.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const inboundItemWithIdOnly = await prisma.inboundItem.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends InboundItemFindManyArgs>(args?: Prisma.SelectSubset<T, InboundItemFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$InboundItemPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a InboundItem.
   * @param {InboundItemCreateArgs} args - Arguments to create a InboundItem.
   * @example
   * // Create one InboundItem
   * const InboundItem = await prisma.inboundItem.create({
   *   data: {
   *     // ... data to create a InboundItem
   *   }
   * })
   * 
   */
  create<T extends InboundItemCreateArgs>(args: Prisma.SelectSubset<T, InboundItemCreateArgs<ExtArgs>>): Prisma.Prisma__InboundItemClient<runtime.Types.Result.GetResult<Prisma.$InboundItemPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many InboundItems.
   * @param {InboundItemCreateManyArgs} args - Arguments to create many InboundItems.
   * @example
   * // Create many InboundItems
   * const inboundItem = await prisma.inboundItem.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends InboundItemCreateManyArgs>(args?: Prisma.SelectSubset<T, InboundItemCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many InboundItems and returns the data saved in the database.
   * @param {InboundItemCreateManyAndReturnArgs} args - Arguments to create many InboundItems.
   * @example
   * // Create many InboundItems
   * const inboundItem = await prisma.inboundItem.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many InboundItems and only return the `id`
   * const inboundItemWithIdOnly = await prisma.inboundItem.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends InboundItemCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, InboundItemCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$InboundItemPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a InboundItem.
   * @param {InboundItemDeleteArgs} args - Arguments to delete one InboundItem.
   * @example
   * // Delete one InboundItem
   * const InboundItem = await prisma.inboundItem.delete({
   *   where: {
   *     // ... filter to delete one InboundItem
   *   }
   * })
   * 
   */
  delete<T extends InboundItemDeleteArgs>(args: Prisma.SelectSubset<T, InboundItemDeleteArgs<ExtArgs>>): Prisma.Prisma__InboundItemClient<runtime.Types.Result.GetResult<Prisma.$InboundItemPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one InboundItem.
   * @param {InboundItemUpdateArgs} args - Arguments to update one InboundItem.
   * @example
   * // Update one InboundItem
   * const inboundItem = await prisma.inboundItem.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends InboundItemUpdateArgs>(args: Prisma.SelectSubset<T, InboundItemUpdateArgs<ExtArgs>>): Prisma.Prisma__InboundItemClient<runtime.Types.Result.GetResult<Prisma.$InboundItemPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more InboundItems.
   * @param {InboundItemDeleteManyArgs} args - Arguments to filter InboundItems to delete.
   * @example
   * // Delete a few InboundItems
   * const { count } = await prisma.inboundItem.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends InboundItemDeleteManyArgs>(args?: Prisma.SelectSubset<T, InboundItemDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more InboundItems.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {InboundItemUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many InboundItems
   * const inboundItem = await prisma.inboundItem.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends InboundItemUpdateManyArgs>(args: Prisma.SelectSubset<T, InboundItemUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more InboundItems and returns the data updated in the database.
   * @param {InboundItemUpdateManyAndReturnArgs} args - Arguments to update many InboundItems.
   * @example
   * // Update many InboundItems
   * const inboundItem = await prisma.inboundItem.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more InboundItems and only return the `id`
   * const inboundItemWithIdOnly = await prisma.inboundItem.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends InboundItemUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, InboundItemUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$InboundItemPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one InboundItem.
   * @param {InboundItemUpsertArgs} args - Arguments to update or create a InboundItem.
   * @example
   * // Update or create a InboundItem
   * const inboundItem = await prisma.inboundItem.upsert({
   *   create: {
   *     // ... data to create a InboundItem
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the InboundItem we want to update
   *   }
   * })
   */
  upsert<T extends InboundItemUpsertArgs>(args: Prisma.SelectSubset<T, InboundItemUpsertArgs<ExtArgs>>): Prisma.Prisma__InboundItemClient<runtime.Types.Result.GetResult<Prisma.$InboundItemPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of InboundItems.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {InboundItemCountArgs} args - Arguments to filter InboundItems to count.
   * @example
   * // Count the number of InboundItems
   * const count = await prisma.inboundItem.count({
   *   where: {
   *     // ... the filter for the InboundItems we want to count
   *   }
   * })
  **/
  count<T extends InboundItemCountArgs>(
    args?: Prisma.Subset<T, InboundItemCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], InboundItemCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a InboundItem.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {InboundItemAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends InboundItemAggregateArgs>(args: Prisma.Subset<T, InboundItemAggregateArgs>): Prisma.PrismaPromise<GetInboundItemAggregateType<T>>

  /**
   * Group by InboundItem.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {InboundItemGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends InboundItemGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: InboundItemGroupByArgs['orderBy'] }
      : { orderBy?: InboundItemGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, InboundItemGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetInboundItemGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the InboundItem model
 */
readonly fields: InboundItemFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for InboundItem.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__InboundItemClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  inbound<T extends Prisma.InboundDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.InboundDefaultArgs<ExtArgs>>): Prisma.Prisma__InboundClient<runtime.Types.Result.GetResult<Prisma.$InboundPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  item<T extends Prisma.ItemDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ItemDefaultArgs<ExtArgs>>): Prisma.Prisma__ItemClient<runtime.Types.Result.GetResult<Prisma.$ItemPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the InboundItem model
 */
export interface InboundItemFieldRefs {
  readonly id: Prisma.FieldRef<"InboundItem", 'String'>
  readonly inboundId: Prisma.FieldRef<"InboundItem", 'String'>
  readonly itemId: Prisma.FieldRef<"InboundItem", 'String'>
  readonly expectedQuantity: Prisma.FieldRef<"InboundItem", 'Int'>
  readonly receivedQuantity: Prisma.FieldRef<"InboundItem", 'Int'>
  readonly acceptedQuantity: Prisma.FieldRef<"InboundItem", 'Int'>
  readonly rejectedQuantity: Prisma.FieldRef<"InboundItem", 'Int'>
  readonly notes: Prisma.FieldRef<"InboundItem", 'String'>
  readonly discrepancyType: Prisma.FieldRef<"InboundItem", 'InboundDiscrepancyType'>
  readonly discrepancyReason: Prisma.FieldRef<"InboundItem", 'String'>
  readonly discrepancyAction: Prisma.FieldRef<"InboundItem", 'DiscrepancyResolution'>
  readonly discrepancyDocumentUrl: Prisma.FieldRef<"InboundItem", 'String'>
}
    

// Custom InputTypes
/**
 * InboundItem findUnique
 */
export type InboundItemFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the InboundItem
   */
  select?: Prisma.InboundItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the InboundItem
   */
  omit?: Prisma.InboundItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InboundItemInclude<ExtArgs> | null
  /**
   * Filter, which InboundItem to fetch.
   */
  where: Prisma.InboundItemWhereUniqueInput
}

/**
 * InboundItem findUniqueOrThrow
 */
export type InboundItemFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the InboundItem
   */
  select?: Prisma.InboundItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the InboundItem
   */
  omit?: Prisma.InboundItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InboundItemInclude<ExtArgs> | null
  /**
   * Filter, which InboundItem to fetch.
   */
  where: Prisma.InboundItemWhereUniqueInput
}

/**
 * InboundItem findFirst
 */
export type InboundItemFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the InboundItem
   */
  select?: Prisma.InboundItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the InboundItem
   */
  omit?: Prisma.InboundItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InboundItemInclude<ExtArgs> | null
  /**
   * Filter, which InboundItem to fetch.
   */
  where?: Prisma.InboundItemWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of InboundItems to fetch.
   */
  orderBy?: Prisma.InboundItemOrderByWithRelationInput | Prisma.InboundItemOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for InboundItems.
   */
  cursor?: Prisma.InboundItemWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` InboundItems from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` InboundItems.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of InboundItems.
   */
  distinct?: Prisma.InboundItemScalarFieldEnum | Prisma.InboundItemScalarFieldEnum[]
}

/**
 * InboundItem findFirstOrThrow
 */
export type InboundItemFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the InboundItem
   */
  select?: Prisma.InboundItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the InboundItem
   */
  omit?: Prisma.InboundItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InboundItemInclude<ExtArgs> | null
  /**
   * Filter, which InboundItem to fetch.
   */
  where?: Prisma.InboundItemWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of InboundItems to fetch.
   */
  orderBy?: Prisma.InboundItemOrderByWithRelationInput | Prisma.InboundItemOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for InboundItems.
   */
  cursor?: Prisma.InboundItemWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` InboundItems from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` InboundItems.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of InboundItems.
   */
  distinct?: Prisma.InboundItemScalarFieldEnum | Prisma.InboundItemScalarFieldEnum[]
}

/**
 * InboundItem findMany
 */
export type InboundItemFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the InboundItem
   */
  select?: Prisma.InboundItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the InboundItem
   */
  omit?: Prisma.InboundItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InboundItemInclude<ExtArgs> | null
  /**
   * Filter, which InboundItems to fetch.
   */
  where?: Prisma.InboundItemWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of InboundItems to fetch.
   */
  orderBy?: Prisma.InboundItemOrderByWithRelationInput | Prisma.InboundItemOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing InboundItems.
   */
  cursor?: Prisma.InboundItemWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` InboundItems from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` InboundItems.
   */
  skip?: number
  distinct?: Prisma.InboundItemScalarFieldEnum | Prisma.InboundItemScalarFieldEnum[]
}

/**
 * InboundItem create
 */
export type InboundItemCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the InboundItem
   */
  select?: Prisma.InboundItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the InboundItem
   */
  omit?: Prisma.InboundItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InboundItemInclude<ExtArgs> | null
  /**
   * The data needed to create a InboundItem.
   */
  data: Prisma.XOR<Prisma.InboundItemCreateInput, Prisma.InboundItemUncheckedCreateInput>
}

/**
 * InboundItem createMany
 */
export type InboundItemCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many InboundItems.
   */
  data: Prisma.InboundItemCreateManyInput | Prisma.InboundItemCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * InboundItem createManyAndReturn
 */
export type InboundItemCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the InboundItem
   */
  select?: Prisma.InboundItemSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the InboundItem
   */
  omit?: Prisma.InboundItemOmit<ExtArgs> | null
  /**
   * The data used to create many InboundItems.
   */
  data: Prisma.InboundItemCreateManyInput | Prisma.InboundItemCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InboundItemIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * InboundItem update
 */
export type InboundItemUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the InboundItem
   */
  select?: Prisma.InboundItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the InboundItem
   */
  omit?: Prisma.InboundItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InboundItemInclude<ExtArgs> | null
  /**
   * The data needed to update a InboundItem.
   */
  data: Prisma.XOR<Prisma.InboundItemUpdateInput, Prisma.InboundItemUncheckedUpdateInput>
  /**
   * Choose, which InboundItem to update.
   */
  where: Prisma.InboundItemWhereUniqueInput
}

/**
 * InboundItem updateMany
 */
export type InboundItemUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update InboundItems.
   */
  data: Prisma.XOR<Prisma.InboundItemUpdateManyMutationInput, Prisma.InboundItemUncheckedUpdateManyInput>
  /**
   * Filter which InboundItems to update
   */
  where?: Prisma.InboundItemWhereInput
  /**
   * Limit how many InboundItems to update.
   */
  limit?: number
}

/**
 * InboundItem updateManyAndReturn
 */
export type InboundItemUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the InboundItem
   */
  select?: Prisma.InboundItemSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the InboundItem
   */
  omit?: Prisma.InboundItemOmit<ExtArgs> | null
  /**
   * The data used to update InboundItems.
   */
  data: Prisma.XOR<Prisma.InboundItemUpdateManyMutationInput, Prisma.InboundItemUncheckedUpdateManyInput>
  /**
   * Filter which InboundItems to update
   */
  where?: Prisma.InboundItemWhereInput
  /**
   * Limit how many InboundItems to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InboundItemIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * InboundItem upsert
 */
export type InboundItemUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the InboundItem
   */
  select?: Prisma.InboundItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the InboundItem
   */
  omit?: Prisma.InboundItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InboundItemInclude<ExtArgs> | null
  /**
   * The filter to search for the InboundItem to update in case it exists.
   */
  where: Prisma.InboundItemWhereUniqueInput
  /**
   * In case the InboundItem found by the `where` argument doesn't exist, create a new InboundItem with this data.
   */
  create: Prisma.XOR<Prisma.InboundItemCreateInput, Prisma.InboundItemUncheckedCreateInput>
  /**
   * In case the InboundItem was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.InboundItemUpdateInput, Prisma.InboundItemUncheckedUpdateInput>
}

/**
 * InboundItem delete
 */
export type InboundItemDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the InboundItem
   */
  select?: Prisma.InboundItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the InboundItem
   */
  omit?: Prisma.InboundItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InboundItemInclude<ExtArgs> | null
  /**
   * Filter which InboundItem to delete.
   */
  where: Prisma.InboundItemWhereUniqueInput
}

/**
 * InboundItem deleteMany
 */
export type InboundItemDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which InboundItems to delete
   */
  where?: Prisma.InboundItemWhereInput
  /**
   * Limit how many InboundItems to delete.
   */
  limit?: number
}

/**
 * InboundItem without action
 */
export type InboundItemDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the InboundItem
   */
  select?: Prisma.InboundItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the InboundItem
   */
  omit?: Prisma.InboundItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InboundItemInclude<ExtArgs> | null
}
