
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `ItemPriceHistory` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model ItemPriceHistory
 * 
 */
export type ItemPriceHistoryModel = runtime.Types.Result.DefaultSelection<Prisma.$ItemPriceHistoryPayload>

export type AggregateItemPriceHistory = {
  _count: ItemPriceHistoryCountAggregateOutputType | null
  _avg: ItemPriceHistoryAvgAggregateOutputType | null
  _sum: ItemPriceHistorySumAggregateOutputType | null
  _min: ItemPriceHistoryMinAggregateOutputType | null
  _max: ItemPriceHistoryMaxAggregateOutputType | null
}

export type ItemPriceHistoryAvgAggregateOutputType = {
  unitPrice: runtime.Decimal | null
}

export type ItemPriceHistorySumAggregateOutputType = {
  unitPrice: runtime.Decimal | null
}

export type ItemPriceHistoryMinAggregateOutputType = {
  id: string | null
  itemId: string | null
  vendorId: string | null
  unitPrice: runtime.Decimal | null
  currency: string | null
  validFrom: Date | null
  validTo: Date | null
  createdAt: Date | null
}

export type ItemPriceHistoryMaxAggregateOutputType = {
  id: string | null
  itemId: string | null
  vendorId: string | null
  unitPrice: runtime.Decimal | null
  currency: string | null
  validFrom: Date | null
  validTo: Date | null
  createdAt: Date | null
}

export type ItemPriceHistoryCountAggregateOutputType = {
  id: number
  itemId: number
  vendorId: number
  unitPrice: number
  currency: number
  validFrom: number
  validTo: number
  createdAt: number
  _all: number
}


export type ItemPriceHistoryAvgAggregateInputType = {
  unitPrice?: true
}

export type ItemPriceHistorySumAggregateInputType = {
  unitPrice?: true
}

export type ItemPriceHistoryMinAggregateInputType = {
  id?: true
  itemId?: true
  vendorId?: true
  unitPrice?: true
  currency?: true
  validFrom?: true
  validTo?: true
  createdAt?: true
}

export type ItemPriceHistoryMaxAggregateInputType = {
  id?: true
  itemId?: true
  vendorId?: true
  unitPrice?: true
  currency?: true
  validFrom?: true
  validTo?: true
  createdAt?: true
}

export type ItemPriceHistoryCountAggregateInputType = {
  id?: true
  itemId?: true
  vendorId?: true
  unitPrice?: true
  currency?: true
  validFrom?: true
  validTo?: true
  createdAt?: true
  _all?: true
}

export type ItemPriceHistoryAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ItemPriceHistory to aggregate.
   */
  where?: Prisma.ItemPriceHistoryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ItemPriceHistories to fetch.
   */
  orderBy?: Prisma.ItemPriceHistoryOrderByWithRelationInput | Prisma.ItemPriceHistoryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ItemPriceHistoryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ItemPriceHistories from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ItemPriceHistories.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned ItemPriceHistories
  **/
  _count?: true | ItemPriceHistoryCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: ItemPriceHistoryAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: ItemPriceHistorySumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ItemPriceHistoryMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ItemPriceHistoryMaxAggregateInputType
}

export type GetItemPriceHistoryAggregateType<T extends ItemPriceHistoryAggregateArgs> = {
      [P in keyof T & keyof AggregateItemPriceHistory]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateItemPriceHistory[P]>
    : Prisma.GetScalarType<T[P], AggregateItemPriceHistory[P]>
}




export type ItemPriceHistoryGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ItemPriceHistoryWhereInput
  orderBy?: Prisma.ItemPriceHistoryOrderByWithAggregationInput | Prisma.ItemPriceHistoryOrderByWithAggregationInput[]
  by: Prisma.ItemPriceHistoryScalarFieldEnum[] | Prisma.ItemPriceHistoryScalarFieldEnum
  having?: Prisma.ItemPriceHistoryScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ItemPriceHistoryCountAggregateInputType | true
  _avg?: ItemPriceHistoryAvgAggregateInputType
  _sum?: ItemPriceHistorySumAggregateInputType
  _min?: ItemPriceHistoryMinAggregateInputType
  _max?: ItemPriceHistoryMaxAggregateInputType
}

export type ItemPriceHistoryGroupByOutputType = {
  id: string
  itemId: string
  vendorId: string
  unitPrice: runtime.Decimal
  currency: string
  validFrom: Date
  validTo: Date | null
  createdAt: Date
  _count: ItemPriceHistoryCountAggregateOutputType | null
  _avg: ItemPriceHistoryAvgAggregateOutputType | null
  _sum: ItemPriceHistorySumAggregateOutputType | null
  _min: ItemPriceHistoryMinAggregateOutputType | null
  _max: ItemPriceHistoryMaxAggregateOutputType | null
}

type GetItemPriceHistoryGroupByPayload<T extends ItemPriceHistoryGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ItemPriceHistoryGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ItemPriceHistoryGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ItemPriceHistoryGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ItemPriceHistoryGroupByOutputType[P]>
      }
    >
  >



export type ItemPriceHistoryWhereInput = {
  AND?: Prisma.ItemPriceHistoryWhereInput | Prisma.ItemPriceHistoryWhereInput[]
  OR?: Prisma.ItemPriceHistoryWhereInput[]
  NOT?: Prisma.ItemPriceHistoryWhereInput | Prisma.ItemPriceHistoryWhereInput[]
  id?: Prisma.StringFilter<"ItemPriceHistory"> | string
  itemId?: Prisma.StringFilter<"ItemPriceHistory"> | string
  vendorId?: Prisma.StringFilter<"ItemPriceHistory"> | string
  unitPrice?: Prisma.DecimalFilter<"ItemPriceHistory"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  currency?: Prisma.StringFilter<"ItemPriceHistory"> | string
  validFrom?: Prisma.DateTimeFilter<"ItemPriceHistory"> | Date | string
  validTo?: Prisma.DateTimeNullableFilter<"ItemPriceHistory"> | Date | string | null
  createdAt?: Prisma.DateTimeFilter<"ItemPriceHistory"> | Date | string
  item?: Prisma.XOR<Prisma.ItemScalarRelationFilter, Prisma.ItemWhereInput>
  vendor?: Prisma.XOR<Prisma.VendorScalarRelationFilter, Prisma.VendorWhereInput>
}

export type ItemPriceHistoryOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  itemId?: Prisma.SortOrder
  vendorId?: Prisma.SortOrder
  unitPrice?: Prisma.SortOrder
  currency?: Prisma.SortOrder
  validFrom?: Prisma.SortOrder
  validTo?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  item?: Prisma.ItemOrderByWithRelationInput
  vendor?: Prisma.VendorOrderByWithRelationInput
}

export type ItemPriceHistoryWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.ItemPriceHistoryWhereInput | Prisma.ItemPriceHistoryWhereInput[]
  OR?: Prisma.ItemPriceHistoryWhereInput[]
  NOT?: Prisma.ItemPriceHistoryWhereInput | Prisma.ItemPriceHistoryWhereInput[]
  itemId?: Prisma.StringFilter<"ItemPriceHistory"> | string
  vendorId?: Prisma.StringFilter<"ItemPriceHistory"> | string
  unitPrice?: Prisma.DecimalFilter<"ItemPriceHistory"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  currency?: Prisma.StringFilter<"ItemPriceHistory"> | string
  validFrom?: Prisma.DateTimeFilter<"ItemPriceHistory"> | Date | string
  validTo?: Prisma.DateTimeNullableFilter<"ItemPriceHistory"> | Date | string | null
  createdAt?: Prisma.DateTimeFilter<"ItemPriceHistory"> | Date | string
  item?: Prisma.XOR<Prisma.ItemScalarRelationFilter, Prisma.ItemWhereInput>
  vendor?: Prisma.XOR<Prisma.VendorScalarRelationFilter, Prisma.VendorWhereInput>
}, "id">

export type ItemPriceHistoryOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  itemId?: Prisma.SortOrder
  vendorId?: Prisma.SortOrder
  unitPrice?: Prisma.SortOrder
  currency?: Prisma.SortOrder
  validFrom?: Prisma.SortOrder
  validTo?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.ItemPriceHistoryCountOrderByAggregateInput
  _avg?: Prisma.ItemPriceHistoryAvgOrderByAggregateInput
  _max?: Prisma.ItemPriceHistoryMaxOrderByAggregateInput
  _min?: Prisma.ItemPriceHistoryMinOrderByAggregateInput
  _sum?: Prisma.ItemPriceHistorySumOrderByAggregateInput
}

export type ItemPriceHistoryScalarWhereWithAggregatesInput = {
  AND?: Prisma.ItemPriceHistoryScalarWhereWithAggregatesInput | Prisma.ItemPriceHistoryScalarWhereWithAggregatesInput[]
  OR?: Prisma.ItemPriceHistoryScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ItemPriceHistoryScalarWhereWithAggregatesInput | Prisma.ItemPriceHistoryScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"ItemPriceHistory"> | string
  itemId?: Prisma.StringWithAggregatesFilter<"ItemPriceHistory"> | string
  vendorId?: Prisma.StringWithAggregatesFilter<"ItemPriceHistory"> | string
  unitPrice?: Prisma.DecimalWithAggregatesFilter<"ItemPriceHistory"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  currency?: Prisma.StringWithAggregatesFilter<"ItemPriceHistory"> | string
  validFrom?: Prisma.DateTimeWithAggregatesFilter<"ItemPriceHistory"> | Date | string
  validTo?: Prisma.DateTimeNullableWithAggregatesFilter<"ItemPriceHistory"> | Date | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"ItemPriceHistory"> | Date | string
}

export type ItemPriceHistoryCreateInput = {
  id?: string
  unitPrice: runtime.Decimal | runtime.DecimalJsLike | number | string
  currency?: string
  validFrom?: Date | string
  validTo?: Date | string | null
  createdAt?: Date | string
  item: Prisma.ItemCreateNestedOneWithoutPriceHistoriesInput
  vendor: Prisma.VendorCreateNestedOneWithoutPriceHistoriesInput
}

export type ItemPriceHistoryUncheckedCreateInput = {
  id?: string
  itemId: string
  vendorId: string
  unitPrice: runtime.Decimal | runtime.DecimalJsLike | number | string
  currency?: string
  validFrom?: Date | string
  validTo?: Date | string | null
  createdAt?: Date | string
}

export type ItemPriceHistoryUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  unitPrice?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  currency?: Prisma.StringFieldUpdateOperationsInput | string
  validFrom?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  validTo?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  item?: Prisma.ItemUpdateOneRequiredWithoutPriceHistoriesNestedInput
  vendor?: Prisma.VendorUpdateOneRequiredWithoutPriceHistoriesNestedInput
}

export type ItemPriceHistoryUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  itemId?: Prisma.StringFieldUpdateOperationsInput | string
  vendorId?: Prisma.StringFieldUpdateOperationsInput | string
  unitPrice?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  currency?: Prisma.StringFieldUpdateOperationsInput | string
  validFrom?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  validTo?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ItemPriceHistoryCreateManyInput = {
  id?: string
  itemId: string
  vendorId: string
  unitPrice: runtime.Decimal | runtime.DecimalJsLike | number | string
  currency?: string
  validFrom?: Date | string
  validTo?: Date | string | null
  createdAt?: Date | string
}

export type ItemPriceHistoryUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  unitPrice?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  currency?: Prisma.StringFieldUpdateOperationsInput | string
  validFrom?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  validTo?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ItemPriceHistoryUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  itemId?: Prisma.StringFieldUpdateOperationsInput | string
  vendorId?: Prisma.StringFieldUpdateOperationsInput | string
  unitPrice?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  currency?: Prisma.StringFieldUpdateOperationsInput | string
  validFrom?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  validTo?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ItemPriceHistoryListRelationFilter = {
  every?: Prisma.ItemPriceHistoryWhereInput
  some?: Prisma.ItemPriceHistoryWhereInput
  none?: Prisma.ItemPriceHistoryWhereInput
}

export type ItemPriceHistoryOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type ItemPriceHistoryCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  itemId?: Prisma.SortOrder
  vendorId?: Prisma.SortOrder
  unitPrice?: Prisma.SortOrder
  currency?: Prisma.SortOrder
  validFrom?: Prisma.SortOrder
  validTo?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type ItemPriceHistoryAvgOrderByAggregateInput = {
  unitPrice?: Prisma.SortOrder
}

export type ItemPriceHistoryMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  itemId?: Prisma.SortOrder
  vendorId?: Prisma.SortOrder
  unitPrice?: Prisma.SortOrder
  currency?: Prisma.SortOrder
  validFrom?: Prisma.SortOrder
  validTo?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type ItemPriceHistoryMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  itemId?: Prisma.SortOrder
  vendorId?: Prisma.SortOrder
  unitPrice?: Prisma.SortOrder
  currency?: Prisma.SortOrder
  validFrom?: Prisma.SortOrder
  validTo?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type ItemPriceHistorySumOrderByAggregateInput = {
  unitPrice?: Prisma.SortOrder
}

export type ItemPriceHistoryCreateNestedManyWithoutVendorInput = {
  create?: Prisma.XOR<Prisma.ItemPriceHistoryCreateWithoutVendorInput, Prisma.ItemPriceHistoryUncheckedCreateWithoutVendorInput> | Prisma.ItemPriceHistoryCreateWithoutVendorInput[] | Prisma.ItemPriceHistoryUncheckedCreateWithoutVendorInput[]
  connectOrCreate?: Prisma.ItemPriceHistoryCreateOrConnectWithoutVendorInput | Prisma.ItemPriceHistoryCreateOrConnectWithoutVendorInput[]
  createMany?: Prisma.ItemPriceHistoryCreateManyVendorInputEnvelope
  connect?: Prisma.ItemPriceHistoryWhereUniqueInput | Prisma.ItemPriceHistoryWhereUniqueInput[]
}

export type ItemPriceHistoryUncheckedCreateNestedManyWithoutVendorInput = {
  create?: Prisma.XOR<Prisma.ItemPriceHistoryCreateWithoutVendorInput, Prisma.ItemPriceHistoryUncheckedCreateWithoutVendorInput> | Prisma.ItemPriceHistoryCreateWithoutVendorInput[] | Prisma.ItemPriceHistoryUncheckedCreateWithoutVendorInput[]
  connectOrCreate?: Prisma.ItemPriceHistoryCreateOrConnectWithoutVendorInput | Prisma.ItemPriceHistoryCreateOrConnectWithoutVendorInput[]
  createMany?: Prisma.ItemPriceHistoryCreateManyVendorInputEnvelope
  connect?: Prisma.ItemPriceHistoryWhereUniqueInput | Prisma.ItemPriceHistoryWhereUniqueInput[]
}

export type ItemPriceHistoryUpdateManyWithoutVendorNestedInput = {
  create?: Prisma.XOR<Prisma.ItemPriceHistoryCreateWithoutVendorInput, Prisma.ItemPriceHistoryUncheckedCreateWithoutVendorInput> | Prisma.ItemPriceHistoryCreateWithoutVendorInput[] | Prisma.ItemPriceHistoryUncheckedCreateWithoutVendorInput[]
  connectOrCreate?: Prisma.ItemPriceHistoryCreateOrConnectWithoutVendorInput | Prisma.ItemPriceHistoryCreateOrConnectWithoutVendorInput[]
  upsert?: Prisma.ItemPriceHistoryUpsertWithWhereUniqueWithoutVendorInput | Prisma.ItemPriceHistoryUpsertWithWhereUniqueWithoutVendorInput[]
  createMany?: Prisma.ItemPriceHistoryCreateManyVendorInputEnvelope
  set?: Prisma.ItemPriceHistoryWhereUniqueInput | Prisma.ItemPriceHistoryWhereUniqueInput[]
  disconnect?: Prisma.ItemPriceHistoryWhereUniqueInput | Prisma.ItemPriceHistoryWhereUniqueInput[]
  delete?: Prisma.ItemPriceHistoryWhereUniqueInput | Prisma.ItemPriceHistoryWhereUniqueInput[]
  connect?: Prisma.ItemPriceHistoryWhereUniqueInput | Prisma.ItemPriceHistoryWhereUniqueInput[]
  update?: Prisma.ItemPriceHistoryUpdateWithWhereUniqueWithoutVendorInput | Prisma.ItemPriceHistoryUpdateWithWhereUniqueWithoutVendorInput[]
  updateMany?: Prisma.ItemPriceHistoryUpdateManyWithWhereWithoutVendorInput | Prisma.ItemPriceHistoryUpdateManyWithWhereWithoutVendorInput[]
  deleteMany?: Prisma.ItemPriceHistoryScalarWhereInput | Prisma.ItemPriceHistoryScalarWhereInput[]
}

export type ItemPriceHistoryUncheckedUpdateManyWithoutVendorNestedInput = {
  create?: Prisma.XOR<Prisma.ItemPriceHistoryCreateWithoutVendorInput, Prisma.ItemPriceHistoryUncheckedCreateWithoutVendorInput> | Prisma.ItemPriceHistoryCreateWithoutVendorInput[] | Prisma.ItemPriceHistoryUncheckedCreateWithoutVendorInput[]
  connectOrCreate?: Prisma.ItemPriceHistoryCreateOrConnectWithoutVendorInput | Prisma.ItemPriceHistoryCreateOrConnectWithoutVendorInput[]
  upsert?: Prisma.ItemPriceHistoryUpsertWithWhereUniqueWithoutVendorInput | Prisma.ItemPriceHistoryUpsertWithWhereUniqueWithoutVendorInput[]
  createMany?: Prisma.ItemPriceHistoryCreateManyVendorInputEnvelope
  set?: Prisma.ItemPriceHistoryWhereUniqueInput | Prisma.ItemPriceHistoryWhereUniqueInput[]
  disconnect?: Prisma.ItemPriceHistoryWhereUniqueInput | Prisma.ItemPriceHistoryWhereUniqueInput[]
  delete?: Prisma.ItemPriceHistoryWhereUniqueInput | Prisma.ItemPriceHistoryWhereUniqueInput[]
  connect?: Prisma.ItemPriceHistoryWhereUniqueInput | Prisma.ItemPriceHistoryWhereUniqueInput[]
  update?: Prisma.ItemPriceHistoryUpdateWithWhereUniqueWithoutVendorInput | Prisma.ItemPriceHistoryUpdateWithWhereUniqueWithoutVendorInput[]
  updateMany?: Prisma.ItemPriceHistoryUpdateManyWithWhereWithoutVendorInput | Prisma.ItemPriceHistoryUpdateManyWithWhereWithoutVendorInput[]
  deleteMany?: Prisma.ItemPriceHistoryScalarWhereInput | Prisma.ItemPriceHistoryScalarWhereInput[]
}

export type ItemPriceHistoryCreateNestedManyWithoutItemInput = {
  create?: Prisma.XOR<Prisma.ItemPriceHistoryCreateWithoutItemInput, Prisma.ItemPriceHistoryUncheckedCreateWithoutItemInput> | Prisma.ItemPriceHistoryCreateWithoutItemInput[] | Prisma.ItemPriceHistoryUncheckedCreateWithoutItemInput[]
  connectOrCreate?: Prisma.ItemPriceHistoryCreateOrConnectWithoutItemInput | Prisma.ItemPriceHistoryCreateOrConnectWithoutItemInput[]
  createMany?: Prisma.ItemPriceHistoryCreateManyItemInputEnvelope
  connect?: Prisma.ItemPriceHistoryWhereUniqueInput | Prisma.ItemPriceHistoryWhereUniqueInput[]
}

export type ItemPriceHistoryUncheckedCreateNestedManyWithoutItemInput = {
  create?: Prisma.XOR<Prisma.ItemPriceHistoryCreateWithoutItemInput, Prisma.ItemPriceHistoryUncheckedCreateWithoutItemInput> | Prisma.ItemPriceHistoryCreateWithoutItemInput[] | Prisma.ItemPriceHistoryUncheckedCreateWithoutItemInput[]
  connectOrCreate?: Prisma.ItemPriceHistoryCreateOrConnectWithoutItemInput | Prisma.ItemPriceHistoryCreateOrConnectWithoutItemInput[]
  createMany?: Prisma.ItemPriceHistoryCreateManyItemInputEnvelope
  connect?: Prisma.ItemPriceHistoryWhereUniqueInput | Prisma.ItemPriceHistoryWhereUniqueInput[]
}

export type ItemPriceHistoryUpdateManyWithoutItemNestedInput = {
  create?: Prisma.XOR<Prisma.ItemPriceHistoryCreateWithoutItemInput, Prisma.ItemPriceHistoryUncheckedCreateWithoutItemInput> | Prisma.ItemPriceHistoryCreateWithoutItemInput[] | Prisma.ItemPriceHistoryUncheckedCreateWithoutItemInput[]
  connectOrCreate?: Prisma.ItemPriceHistoryCreateOrConnectWithoutItemInput | Prisma.ItemPriceHistoryCreateOrConnectWithoutItemInput[]
  upsert?: Prisma.ItemPriceHistoryUpsertWithWhereUniqueWithoutItemInput | Prisma.ItemPriceHistoryUpsertWithWhereUniqueWithoutItemInput[]
  createMany?: Prisma.ItemPriceHistoryCreateManyItemInputEnvelope
  set?: Prisma.ItemPriceHistoryWhereUniqueInput | Prisma.ItemPriceHistoryWhereUniqueInput[]
  disconnect?: Prisma.ItemPriceHistoryWhereUniqueInput | Prisma.ItemPriceHistoryWhereUniqueInput[]
  delete?: Prisma.ItemPriceHistoryWhereUniqueInput | Prisma.ItemPriceHistoryWhereUniqueInput[]
  connect?: Prisma.ItemPriceHistoryWhereUniqueInput | Prisma.ItemPriceHistoryWhereUniqueInput[]
  update?: Prisma.ItemPriceHistoryUpdateWithWhereUniqueWithoutItemInput | Prisma.ItemPriceHistoryUpdateWithWhereUniqueWithoutItemInput[]
  updateMany?: Prisma.ItemPriceHistoryUpdateManyWithWhereWithoutItemInput | Prisma.ItemPriceHistoryUpdateManyWithWhereWithoutItemInput[]
  deleteMany?: Prisma.ItemPriceHistoryScalarWhereInput | Prisma.ItemPriceHistoryScalarWhereInput[]
}

export type ItemPriceHistoryUncheckedUpdateManyWithoutItemNestedInput = {
  create?: Prisma.XOR<Prisma.ItemPriceHistoryCreateWithoutItemInput, Prisma.ItemPriceHistoryUncheckedCreateWithoutItemInput> | Prisma.ItemPriceHistoryCreateWithoutItemInput[] | Prisma.ItemPriceHistoryUncheckedCreateWithoutItemInput[]
  connectOrCreate?: Prisma.ItemPriceHistoryCreateOrConnectWithoutItemInput | Prisma.ItemPriceHistoryCreateOrConnectWithoutItemInput[]
  upsert?: Prisma.ItemPriceHistoryUpsertWithWhereUniqueWithoutItemInput | Prisma.ItemPriceHistoryUpsertWithWhereUniqueWithoutItemInput[]
  createMany?: Prisma.ItemPriceHistoryCreateManyItemInputEnvelope
  set?: Prisma.ItemPriceHistoryWhereUniqueInput | Prisma.ItemPriceHistoryWhereUniqueInput[]
  disconnect?: Prisma.ItemPriceHistoryWhereUniqueInput | Prisma.ItemPriceHistoryWhereUniqueInput[]
  delete?: Prisma.ItemPriceHistoryWhereUniqueInput | Prisma.ItemPriceHistoryWhereUniqueInput[]
  connect?: Prisma.ItemPriceHistoryWhereUniqueInput | Prisma.ItemPriceHistoryWhereUniqueInput[]
  update?: Prisma.ItemPriceHistoryUpdateWithWhereUniqueWithoutItemInput | Prisma.ItemPriceHistoryUpdateWithWhereUniqueWithoutItemInput[]
  updateMany?: Prisma.ItemPriceHistoryUpdateManyWithWhereWithoutItemInput | Prisma.ItemPriceHistoryUpdateManyWithWhereWithoutItemInput[]
  deleteMany?: Prisma.ItemPriceHistoryScalarWhereInput | Prisma.ItemPriceHistoryScalarWhereInput[]
}

export type DecimalFieldUpdateOperationsInput = {
  set?: runtime.Decimal | runtime.DecimalJsLike | number | string
  increment?: runtime.Decimal | runtime.DecimalJsLike | number | string
  decrement?: runtime.Decimal | runtime.DecimalJsLike | number | string
  multiply?: runtime.Decimal | runtime.DecimalJsLike | number | string
  divide?: runtime.Decimal | runtime.DecimalJsLike | number | string
}

export type NullableDateTimeFieldUpdateOperationsInput = {
  set?: Date | string | null
}

export type ItemPriceHistoryCreateWithoutVendorInput = {
  id?: string
  unitPrice: runtime.Decimal | runtime.DecimalJsLike | number | string
  currency?: string
  validFrom?: Date | string
  validTo?: Date | string | null
  createdAt?: Date | string
  item: Prisma.ItemCreateNestedOneWithoutPriceHistoriesInput
}

export type ItemPriceHistoryUncheckedCreateWithoutVendorInput = {
  id?: string
  itemId: string
  unitPrice: runtime.Decimal | runtime.DecimalJsLike | number | string
  currency?: string
  validFrom?: Date | string
  validTo?: Date | string | null
  createdAt?: Date | string
}

export type ItemPriceHistoryCreateOrConnectWithoutVendorInput = {
  where: Prisma.ItemPriceHistoryWhereUniqueInput
  create: Prisma.XOR<Prisma.ItemPriceHistoryCreateWithoutVendorInput, Prisma.ItemPriceHistoryUncheckedCreateWithoutVendorInput>
}

export type ItemPriceHistoryCreateManyVendorInputEnvelope = {
  data: Prisma.ItemPriceHistoryCreateManyVendorInput | Prisma.ItemPriceHistoryCreateManyVendorInput[]
  skipDuplicates?: boolean
}

export type ItemPriceHistoryUpsertWithWhereUniqueWithoutVendorInput = {
  where: Prisma.ItemPriceHistoryWhereUniqueInput
  update: Prisma.XOR<Prisma.ItemPriceHistoryUpdateWithoutVendorInput, Prisma.ItemPriceHistoryUncheckedUpdateWithoutVendorInput>
  create: Prisma.XOR<Prisma.ItemPriceHistoryCreateWithoutVendorInput, Prisma.ItemPriceHistoryUncheckedCreateWithoutVendorInput>
}

export type ItemPriceHistoryUpdateWithWhereUniqueWithoutVendorInput = {
  where: Prisma.ItemPriceHistoryWhereUniqueInput
  data: Prisma.XOR<Prisma.ItemPriceHistoryUpdateWithoutVendorInput, Prisma.ItemPriceHistoryUncheckedUpdateWithoutVendorInput>
}

export type ItemPriceHistoryUpdateManyWithWhereWithoutVendorInput = {
  where: Prisma.ItemPriceHistoryScalarWhereInput
  data: Prisma.XOR<Prisma.ItemPriceHistoryUpdateManyMutationInput, Prisma.ItemPriceHistoryUncheckedUpdateManyWithoutVendorInput>
}

export type ItemPriceHistoryScalarWhereInput = {
  AND?: Prisma.ItemPriceHistoryScalarWhereInput | Prisma.ItemPriceHistoryScalarWhereInput[]
  OR?: Prisma.ItemPriceHistoryScalarWhereInput[]
  NOT?: Prisma.ItemPriceHistoryScalarWhereInput | Prisma.ItemPriceHistoryScalarWhereInput[]
  id?: Prisma.StringFilter<"ItemPriceHistory"> | string
  itemId?: Prisma.StringFilter<"ItemPriceHistory"> | string
  vendorId?: Prisma.StringFilter<"ItemPriceHistory"> | string
  unitPrice?: Prisma.DecimalFilter<"ItemPriceHistory"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  currency?: Prisma.StringFilter<"ItemPriceHistory"> | string
  validFrom?: Prisma.DateTimeFilter<"ItemPriceHistory"> | Date | string
  validTo?: Prisma.DateTimeNullableFilter<"ItemPriceHistory"> | Date | string | null
  createdAt?: Prisma.DateTimeFilter<"ItemPriceHistory"> | Date | string
}

export type ItemPriceHistoryCreateWithoutItemInput = {
  id?: string
  unitPrice: runtime.Decimal | runtime.DecimalJsLike | number | string
  currency?: string
  validFrom?: Date | string
  validTo?: Date | string | null
  createdAt?: Date | string
  vendor: Prisma.VendorCreateNestedOneWithoutPriceHistoriesInput
}

export type ItemPriceHistoryUncheckedCreateWithoutItemInput = {
  id?: string
  vendorId: string
  unitPrice: runtime.Decimal | runtime.DecimalJsLike | number | string
  currency?: string
  validFrom?: Date | string
  validTo?: Date | string | null
  createdAt?: Date | string
}

export type ItemPriceHistoryCreateOrConnectWithoutItemInput = {
  where: Prisma.ItemPriceHistoryWhereUniqueInput
  create: Prisma.XOR<Prisma.ItemPriceHistoryCreateWithoutItemInput, Prisma.ItemPriceHistoryUncheckedCreateWithoutItemInput>
}

export type ItemPriceHistoryCreateManyItemInputEnvelope = {
  data: Prisma.ItemPriceHistoryCreateManyItemInput | Prisma.ItemPriceHistoryCreateManyItemInput[]
  skipDuplicates?: boolean
}

export type ItemPriceHistoryUpsertWithWhereUniqueWithoutItemInput = {
  where: Prisma.ItemPriceHistoryWhereUniqueInput
  update: Prisma.XOR<Prisma.ItemPriceHistoryUpdateWithoutItemInput, Prisma.ItemPriceHistoryUncheckedUpdateWithoutItemInput>
  create: Prisma.XOR<Prisma.ItemPriceHistoryCreateWithoutItemInput, Prisma.ItemPriceHistoryUncheckedCreateWithoutItemInput>
}

export type ItemPriceHistoryUpdateWithWhereUniqueWithoutItemInput = {
  where: Prisma.ItemPriceHistoryWhereUniqueInput
  data: Prisma.XOR<Prisma.ItemPriceHistoryUpdateWithoutItemInput, Prisma.ItemPriceHistoryUncheckedUpdateWithoutItemInput>
}

export type ItemPriceHistoryUpdateManyWithWhereWithoutItemInput = {
  where: Prisma.ItemPriceHistoryScalarWhereInput
  data: Prisma.XOR<Prisma.ItemPriceHistoryUpdateManyMutationInput, Prisma.ItemPriceHistoryUncheckedUpdateManyWithoutItemInput>
}

export type ItemPriceHistoryCreateManyVendorInput = {
  id?: string
  itemId: string
  unitPrice: runtime.Decimal | runtime.DecimalJsLike | number | string
  currency?: string
  validFrom?: Date | string
  validTo?: Date | string | null
  createdAt?: Date | string
}

export type ItemPriceHistoryUpdateWithoutVendorInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  unitPrice?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  currency?: Prisma.StringFieldUpdateOperationsInput | string
  validFrom?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  validTo?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  item?: Prisma.ItemUpdateOneRequiredWithoutPriceHistoriesNestedInput
}

export type ItemPriceHistoryUncheckedUpdateWithoutVendorInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  itemId?: Prisma.StringFieldUpdateOperationsInput | string
  unitPrice?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  currency?: Prisma.StringFieldUpdateOperationsInput | string
  validFrom?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  validTo?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ItemPriceHistoryUncheckedUpdateManyWithoutVendorInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  itemId?: Prisma.StringFieldUpdateOperationsInput | string
  unitPrice?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  currency?: Prisma.StringFieldUpdateOperationsInput | string
  validFrom?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  validTo?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ItemPriceHistoryCreateManyItemInput = {
  id?: string
  vendorId: string
  unitPrice: runtime.Decimal | runtime.DecimalJsLike | number | string
  currency?: string
  validFrom?: Date | string
  validTo?: Date | string | null
  createdAt?: Date | string
}

export type ItemPriceHistoryUpdateWithoutItemInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  unitPrice?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  currency?: Prisma.StringFieldUpdateOperationsInput | string
  validFrom?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  validTo?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  vendor?: Prisma.VendorUpdateOneRequiredWithoutPriceHistoriesNestedInput
}

export type ItemPriceHistoryUncheckedUpdateWithoutItemInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  vendorId?: Prisma.StringFieldUpdateOperationsInput | string
  unitPrice?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  currency?: Prisma.StringFieldUpdateOperationsInput | string
  validFrom?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  validTo?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ItemPriceHistoryUncheckedUpdateManyWithoutItemInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  vendorId?: Prisma.StringFieldUpdateOperationsInput | string
  unitPrice?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  currency?: Prisma.StringFieldUpdateOperationsInput | string
  validFrom?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  validTo?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type ItemPriceHistorySelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  itemId?: boolean
  vendorId?: boolean
  unitPrice?: boolean
  currency?: boolean
  validFrom?: boolean
  validTo?: boolean
  createdAt?: boolean
  item?: boolean | Prisma.ItemDefaultArgs<ExtArgs>
  vendor?: boolean | Prisma.VendorDefaultArgs<ExtArgs>
}, ExtArgs["result"]["itemPriceHistory"]>

export type ItemPriceHistorySelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  itemId?: boolean
  vendorId?: boolean
  unitPrice?: boolean
  currency?: boolean
  validFrom?: boolean
  validTo?: boolean
  createdAt?: boolean
  item?: boolean | Prisma.ItemDefaultArgs<ExtArgs>
  vendor?: boolean | Prisma.VendorDefaultArgs<ExtArgs>
}, ExtArgs["result"]["itemPriceHistory"]>

export type ItemPriceHistorySelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  itemId?: boolean
  vendorId?: boolean
  unitPrice?: boolean
  currency?: boolean
  validFrom?: boolean
  validTo?: boolean
  createdAt?: boolean
  item?: boolean | Prisma.ItemDefaultArgs<ExtArgs>
  vendor?: boolean | Prisma.VendorDefaultArgs<ExtArgs>
}, ExtArgs["result"]["itemPriceHistory"]>

export type ItemPriceHistorySelectScalar = {
  id?: boolean
  itemId?: boolean
  vendorId?: boolean
  unitPrice?: boolean
  currency?: boolean
  validFrom?: boolean
  validTo?: boolean
  createdAt?: boolean
}

export type ItemPriceHistoryOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "itemId" | "vendorId" | "unitPrice" | "currency" | "validFrom" | "validTo" | "createdAt", ExtArgs["result"]["itemPriceHistory"]>
export type ItemPriceHistoryInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  item?: boolean | Prisma.ItemDefaultArgs<ExtArgs>
  vendor?: boolean | Prisma.VendorDefaultArgs<ExtArgs>
}
export type ItemPriceHistoryIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  item?: boolean | Prisma.ItemDefaultArgs<ExtArgs>
  vendor?: boolean | Prisma.VendorDefaultArgs<ExtArgs>
}
export type ItemPriceHistoryIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  item?: boolean | Prisma.ItemDefaultArgs<ExtArgs>
  vendor?: boolean | Prisma.VendorDefaultArgs<ExtArgs>
}

export type $ItemPriceHistoryPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "ItemPriceHistory"
  objects: {
    item: Prisma.$ItemPayload<ExtArgs>
    vendor: Prisma.$VendorPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    itemId: string
    vendorId: string
    unitPrice: runtime.Decimal
    currency: string
    validFrom: Date
    validTo: Date | null
    createdAt: Date
  }, ExtArgs["result"]["itemPriceHistory"]>
  composites: {}
}

export type ItemPriceHistoryGetPayload<S extends boolean | null | undefined | ItemPriceHistoryDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ItemPriceHistoryPayload, S>

export type ItemPriceHistoryCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ItemPriceHistoryFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ItemPriceHistoryCountAggregateInputType | true
  }

export interface ItemPriceHistoryDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['ItemPriceHistory'], meta: { name: 'ItemPriceHistory' } }
  /**
   * Find zero or one ItemPriceHistory that matches the filter.
   * @param {ItemPriceHistoryFindUniqueArgs} args - Arguments to find a ItemPriceHistory
   * @example
   * // Get one ItemPriceHistory
   * const itemPriceHistory = await prisma.itemPriceHistory.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ItemPriceHistoryFindUniqueArgs>(args: Prisma.SelectSubset<T, ItemPriceHistoryFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ItemPriceHistoryClient<runtime.Types.Result.GetResult<Prisma.$ItemPriceHistoryPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one ItemPriceHistory that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ItemPriceHistoryFindUniqueOrThrowArgs} args - Arguments to find a ItemPriceHistory
   * @example
   * // Get one ItemPriceHistory
   * const itemPriceHistory = await prisma.itemPriceHistory.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ItemPriceHistoryFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ItemPriceHistoryFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ItemPriceHistoryClient<runtime.Types.Result.GetResult<Prisma.$ItemPriceHistoryPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ItemPriceHistory that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ItemPriceHistoryFindFirstArgs} args - Arguments to find a ItemPriceHistory
   * @example
   * // Get one ItemPriceHistory
   * const itemPriceHistory = await prisma.itemPriceHistory.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ItemPriceHistoryFindFirstArgs>(args?: Prisma.SelectSubset<T, ItemPriceHistoryFindFirstArgs<ExtArgs>>): Prisma.Prisma__ItemPriceHistoryClient<runtime.Types.Result.GetResult<Prisma.$ItemPriceHistoryPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ItemPriceHistory that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ItemPriceHistoryFindFirstOrThrowArgs} args - Arguments to find a ItemPriceHistory
   * @example
   * // Get one ItemPriceHistory
   * const itemPriceHistory = await prisma.itemPriceHistory.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ItemPriceHistoryFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ItemPriceHistoryFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ItemPriceHistoryClient<runtime.Types.Result.GetResult<Prisma.$ItemPriceHistoryPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more ItemPriceHistories that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ItemPriceHistoryFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all ItemPriceHistories
   * const itemPriceHistories = await prisma.itemPriceHistory.findMany()
   * 
   * // Get first 10 ItemPriceHistories
   * const itemPriceHistories = await prisma.itemPriceHistory.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const itemPriceHistoryWithIdOnly = await prisma.itemPriceHistory.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ItemPriceHistoryFindManyArgs>(args?: Prisma.SelectSubset<T, ItemPriceHistoryFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ItemPriceHistoryPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a ItemPriceHistory.
   * @param {ItemPriceHistoryCreateArgs} args - Arguments to create a ItemPriceHistory.
   * @example
   * // Create one ItemPriceHistory
   * const ItemPriceHistory = await prisma.itemPriceHistory.create({
   *   data: {
   *     // ... data to create a ItemPriceHistory
   *   }
   * })
   * 
   */
  create<T extends ItemPriceHistoryCreateArgs>(args: Prisma.SelectSubset<T, ItemPriceHistoryCreateArgs<ExtArgs>>): Prisma.Prisma__ItemPriceHistoryClient<runtime.Types.Result.GetResult<Prisma.$ItemPriceHistoryPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many ItemPriceHistories.
   * @param {ItemPriceHistoryCreateManyArgs} args - Arguments to create many ItemPriceHistories.
   * @example
   * // Create many ItemPriceHistories
   * const itemPriceHistory = await prisma.itemPriceHistory.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ItemPriceHistoryCreateManyArgs>(args?: Prisma.SelectSubset<T, ItemPriceHistoryCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many ItemPriceHistories and returns the data saved in the database.
   * @param {ItemPriceHistoryCreateManyAndReturnArgs} args - Arguments to create many ItemPriceHistories.
   * @example
   * // Create many ItemPriceHistories
   * const itemPriceHistory = await prisma.itemPriceHistory.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many ItemPriceHistories and only return the `id`
   * const itemPriceHistoryWithIdOnly = await prisma.itemPriceHistory.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ItemPriceHistoryCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ItemPriceHistoryCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ItemPriceHistoryPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a ItemPriceHistory.
   * @param {ItemPriceHistoryDeleteArgs} args - Arguments to delete one ItemPriceHistory.
   * @example
   * // Delete one ItemPriceHistory
   * const ItemPriceHistory = await prisma.itemPriceHistory.delete({
   *   where: {
   *     // ... filter to delete one ItemPriceHistory
   *   }
   * })
   * 
   */
  delete<T extends ItemPriceHistoryDeleteArgs>(args: Prisma.SelectSubset<T, ItemPriceHistoryDeleteArgs<ExtArgs>>): Prisma.Prisma__ItemPriceHistoryClient<runtime.Types.Result.GetResult<Prisma.$ItemPriceHistoryPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one ItemPriceHistory.
   * @param {ItemPriceHistoryUpdateArgs} args - Arguments to update one ItemPriceHistory.
   * @example
   * // Update one ItemPriceHistory
   * const itemPriceHistory = await prisma.itemPriceHistory.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ItemPriceHistoryUpdateArgs>(args: Prisma.SelectSubset<T, ItemPriceHistoryUpdateArgs<ExtArgs>>): Prisma.Prisma__ItemPriceHistoryClient<runtime.Types.Result.GetResult<Prisma.$ItemPriceHistoryPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more ItemPriceHistories.
   * @param {ItemPriceHistoryDeleteManyArgs} args - Arguments to filter ItemPriceHistories to delete.
   * @example
   * // Delete a few ItemPriceHistories
   * const { count } = await prisma.itemPriceHistory.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ItemPriceHistoryDeleteManyArgs>(args?: Prisma.SelectSubset<T, ItemPriceHistoryDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ItemPriceHistories.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ItemPriceHistoryUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many ItemPriceHistories
   * const itemPriceHistory = await prisma.itemPriceHistory.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ItemPriceHistoryUpdateManyArgs>(args: Prisma.SelectSubset<T, ItemPriceHistoryUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ItemPriceHistories and returns the data updated in the database.
   * @param {ItemPriceHistoryUpdateManyAndReturnArgs} args - Arguments to update many ItemPriceHistories.
   * @example
   * // Update many ItemPriceHistories
   * const itemPriceHistory = await prisma.itemPriceHistory.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more ItemPriceHistories and only return the `id`
   * const itemPriceHistoryWithIdOnly = await prisma.itemPriceHistory.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ItemPriceHistoryUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ItemPriceHistoryUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ItemPriceHistoryPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one ItemPriceHistory.
   * @param {ItemPriceHistoryUpsertArgs} args - Arguments to update or create a ItemPriceHistory.
   * @example
   * // Update or create a ItemPriceHistory
   * const itemPriceHistory = await prisma.itemPriceHistory.upsert({
   *   create: {
   *     // ... data to create a ItemPriceHistory
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the ItemPriceHistory we want to update
   *   }
   * })
   */
  upsert<T extends ItemPriceHistoryUpsertArgs>(args: Prisma.SelectSubset<T, ItemPriceHistoryUpsertArgs<ExtArgs>>): Prisma.Prisma__ItemPriceHistoryClient<runtime.Types.Result.GetResult<Prisma.$ItemPriceHistoryPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of ItemPriceHistories.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ItemPriceHistoryCountArgs} args - Arguments to filter ItemPriceHistories to count.
   * @example
   * // Count the number of ItemPriceHistories
   * const count = await prisma.itemPriceHistory.count({
   *   where: {
   *     // ... the filter for the ItemPriceHistories we want to count
   *   }
   * })
  **/
  count<T extends ItemPriceHistoryCountArgs>(
    args?: Prisma.Subset<T, ItemPriceHistoryCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ItemPriceHistoryCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a ItemPriceHistory.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ItemPriceHistoryAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ItemPriceHistoryAggregateArgs>(args: Prisma.Subset<T, ItemPriceHistoryAggregateArgs>): Prisma.PrismaPromise<GetItemPriceHistoryAggregateType<T>>

  /**
   * Group by ItemPriceHistory.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ItemPriceHistoryGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ItemPriceHistoryGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ItemPriceHistoryGroupByArgs['orderBy'] }
      : { orderBy?: ItemPriceHistoryGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ItemPriceHistoryGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetItemPriceHistoryGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the ItemPriceHistory model
 */
readonly fields: ItemPriceHistoryFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for ItemPriceHistory.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ItemPriceHistoryClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  item<T extends Prisma.ItemDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ItemDefaultArgs<ExtArgs>>): Prisma.Prisma__ItemClient<runtime.Types.Result.GetResult<Prisma.$ItemPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  vendor<T extends Prisma.VendorDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.VendorDefaultArgs<ExtArgs>>): Prisma.Prisma__VendorClient<runtime.Types.Result.GetResult<Prisma.$VendorPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the ItemPriceHistory model
 */
export interface ItemPriceHistoryFieldRefs {
  readonly id: Prisma.FieldRef<"ItemPriceHistory", 'String'>
  readonly itemId: Prisma.FieldRef<"ItemPriceHistory", 'String'>
  readonly vendorId: Prisma.FieldRef<"ItemPriceHistory", 'String'>
  readonly unitPrice: Prisma.FieldRef<"ItemPriceHistory", 'Decimal'>
  readonly currency: Prisma.FieldRef<"ItemPriceHistory", 'String'>
  readonly validFrom: Prisma.FieldRef<"ItemPriceHistory", 'DateTime'>
  readonly validTo: Prisma.FieldRef<"ItemPriceHistory", 'DateTime'>
  readonly createdAt: Prisma.FieldRef<"ItemPriceHistory", 'DateTime'>
}
    

// Custom InputTypes
/**
 * ItemPriceHistory findUnique
 */
export type ItemPriceHistoryFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ItemPriceHistory
   */
  select?: Prisma.ItemPriceHistorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the ItemPriceHistory
   */
  omit?: Prisma.ItemPriceHistoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ItemPriceHistoryInclude<ExtArgs> | null
  /**
   * Filter, which ItemPriceHistory to fetch.
   */
  where: Prisma.ItemPriceHistoryWhereUniqueInput
}

/**
 * ItemPriceHistory findUniqueOrThrow
 */
export type ItemPriceHistoryFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ItemPriceHistory
   */
  select?: Prisma.ItemPriceHistorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the ItemPriceHistory
   */
  omit?: Prisma.ItemPriceHistoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ItemPriceHistoryInclude<ExtArgs> | null
  /**
   * Filter, which ItemPriceHistory to fetch.
   */
  where: Prisma.ItemPriceHistoryWhereUniqueInput
}

/**
 * ItemPriceHistory findFirst
 */
export type ItemPriceHistoryFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ItemPriceHistory
   */
  select?: Prisma.ItemPriceHistorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the ItemPriceHistory
   */
  omit?: Prisma.ItemPriceHistoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ItemPriceHistoryInclude<ExtArgs> | null
  /**
   * Filter, which ItemPriceHistory to fetch.
   */
  where?: Prisma.ItemPriceHistoryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ItemPriceHistories to fetch.
   */
  orderBy?: Prisma.ItemPriceHistoryOrderByWithRelationInput | Prisma.ItemPriceHistoryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ItemPriceHistories.
   */
  cursor?: Prisma.ItemPriceHistoryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ItemPriceHistories from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ItemPriceHistories.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ItemPriceHistories.
   */
  distinct?: Prisma.ItemPriceHistoryScalarFieldEnum | Prisma.ItemPriceHistoryScalarFieldEnum[]
}

/**
 * ItemPriceHistory findFirstOrThrow
 */
export type ItemPriceHistoryFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ItemPriceHistory
   */
  select?: Prisma.ItemPriceHistorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the ItemPriceHistory
   */
  omit?: Prisma.ItemPriceHistoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ItemPriceHistoryInclude<ExtArgs> | null
  /**
   * Filter, which ItemPriceHistory to fetch.
   */
  where?: Prisma.ItemPriceHistoryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ItemPriceHistories to fetch.
   */
  orderBy?: Prisma.ItemPriceHistoryOrderByWithRelationInput | Prisma.ItemPriceHistoryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ItemPriceHistories.
   */
  cursor?: Prisma.ItemPriceHistoryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ItemPriceHistories from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ItemPriceHistories.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ItemPriceHistories.
   */
  distinct?: Prisma.ItemPriceHistoryScalarFieldEnum | Prisma.ItemPriceHistoryScalarFieldEnum[]
}

/**
 * ItemPriceHistory findMany
 */
export type ItemPriceHistoryFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ItemPriceHistory
   */
  select?: Prisma.ItemPriceHistorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the ItemPriceHistory
   */
  omit?: Prisma.ItemPriceHistoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ItemPriceHistoryInclude<ExtArgs> | null
  /**
   * Filter, which ItemPriceHistories to fetch.
   */
  where?: Prisma.ItemPriceHistoryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ItemPriceHistories to fetch.
   */
  orderBy?: Prisma.ItemPriceHistoryOrderByWithRelationInput | Prisma.ItemPriceHistoryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing ItemPriceHistories.
   */
  cursor?: Prisma.ItemPriceHistoryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ItemPriceHistories from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ItemPriceHistories.
   */
  skip?: number
  distinct?: Prisma.ItemPriceHistoryScalarFieldEnum | Prisma.ItemPriceHistoryScalarFieldEnum[]
}

/**
 * ItemPriceHistory create
 */
export type ItemPriceHistoryCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ItemPriceHistory
   */
  select?: Prisma.ItemPriceHistorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the ItemPriceHistory
   */
  omit?: Prisma.ItemPriceHistoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ItemPriceHistoryInclude<ExtArgs> | null
  /**
   * The data needed to create a ItemPriceHistory.
   */
  data: Prisma.XOR<Prisma.ItemPriceHistoryCreateInput, Prisma.ItemPriceHistoryUncheckedCreateInput>
}

/**
 * ItemPriceHistory createMany
 */
export type ItemPriceHistoryCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many ItemPriceHistories.
   */
  data: Prisma.ItemPriceHistoryCreateManyInput | Prisma.ItemPriceHistoryCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * ItemPriceHistory createManyAndReturn
 */
export type ItemPriceHistoryCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ItemPriceHistory
   */
  select?: Prisma.ItemPriceHistorySelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ItemPriceHistory
   */
  omit?: Prisma.ItemPriceHistoryOmit<ExtArgs> | null
  /**
   * The data used to create many ItemPriceHistories.
   */
  data: Prisma.ItemPriceHistoryCreateManyInput | Prisma.ItemPriceHistoryCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ItemPriceHistoryIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * ItemPriceHistory update
 */
export type ItemPriceHistoryUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ItemPriceHistory
   */
  select?: Prisma.ItemPriceHistorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the ItemPriceHistory
   */
  omit?: Prisma.ItemPriceHistoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ItemPriceHistoryInclude<ExtArgs> | null
  /**
   * The data needed to update a ItemPriceHistory.
   */
  data: Prisma.XOR<Prisma.ItemPriceHistoryUpdateInput, Prisma.ItemPriceHistoryUncheckedUpdateInput>
  /**
   * Choose, which ItemPriceHistory to update.
   */
  where: Prisma.ItemPriceHistoryWhereUniqueInput
}

/**
 * ItemPriceHistory updateMany
 */
export type ItemPriceHistoryUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update ItemPriceHistories.
   */
  data: Prisma.XOR<Prisma.ItemPriceHistoryUpdateManyMutationInput, Prisma.ItemPriceHistoryUncheckedUpdateManyInput>
  /**
   * Filter which ItemPriceHistories to update
   */
  where?: Prisma.ItemPriceHistoryWhereInput
  /**
   * Limit how many ItemPriceHistories to update.
   */
  limit?: number
}

/**
 * ItemPriceHistory updateManyAndReturn
 */
export type ItemPriceHistoryUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ItemPriceHistory
   */
  select?: Prisma.ItemPriceHistorySelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ItemPriceHistory
   */
  omit?: Prisma.ItemPriceHistoryOmit<ExtArgs> | null
  /**
   * The data used to update ItemPriceHistories.
   */
  data: Prisma.XOR<Prisma.ItemPriceHistoryUpdateManyMutationInput, Prisma.ItemPriceHistoryUncheckedUpdateManyInput>
  /**
   * Filter which ItemPriceHistories to update
   */
  where?: Prisma.ItemPriceHistoryWhereInput
  /**
   * Limit how many ItemPriceHistories to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ItemPriceHistoryIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * ItemPriceHistory upsert
 */
export type ItemPriceHistoryUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ItemPriceHistory
   */
  select?: Prisma.ItemPriceHistorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the ItemPriceHistory
   */
  omit?: Prisma.ItemPriceHistoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ItemPriceHistoryInclude<ExtArgs> | null
  /**
   * The filter to search for the ItemPriceHistory to update in case it exists.
   */
  where: Prisma.ItemPriceHistoryWhereUniqueInput
  /**
   * In case the ItemPriceHistory found by the `where` argument doesn't exist, create a new ItemPriceHistory with this data.
   */
  create: Prisma.XOR<Prisma.ItemPriceHistoryCreateInput, Prisma.ItemPriceHistoryUncheckedCreateInput>
  /**
   * In case the ItemPriceHistory was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ItemPriceHistoryUpdateInput, Prisma.ItemPriceHistoryUncheckedUpdateInput>
}

/**
 * ItemPriceHistory delete
 */
export type ItemPriceHistoryDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ItemPriceHistory
   */
  select?: Prisma.ItemPriceHistorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the ItemPriceHistory
   */
  omit?: Prisma.ItemPriceHistoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ItemPriceHistoryInclude<ExtArgs> | null
  /**
   * Filter which ItemPriceHistory to delete.
   */
  where: Prisma.ItemPriceHistoryWhereUniqueInput
}

/**
 * ItemPriceHistory deleteMany
 */
export type ItemPriceHistoryDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ItemPriceHistories to delete
   */
  where?: Prisma.ItemPriceHistoryWhereInput
  /**
   * Limit how many ItemPriceHistories to delete.
   */
  limit?: number
}

/**
 * ItemPriceHistory without action
 */
export type ItemPriceHistoryDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ItemPriceHistory
   */
  select?: Prisma.ItemPriceHistorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the ItemPriceHistory
   */
  omit?: Prisma.ItemPriceHistoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ItemPriceHistoryInclude<ExtArgs> | null
}
