
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Partner` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Partner
 * 
 */
export type PartnerModel = runtime.Types.Result.DefaultSelection<Prisma.$PartnerPayload>

export type AggregatePartner = {
  _count: PartnerCountAggregateOutputType | null
  _min: PartnerMinAggregateOutputType | null
  _max: PartnerMaxAggregateOutputType | null
}

export type PartnerMinAggregateOutputType = {
  id: string | null
  code: string | null
  name: string | null
  address: string | null
  phone: string | null
  email: string | null
  contactName: string | null
  bankName: string | null
  bankAccount: string | null
  isActive: boolean | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type PartnerMaxAggregateOutputType = {
  id: string | null
  code: string | null
  name: string | null
  address: string | null
  phone: string | null
  email: string | null
  contactName: string | null
  bankName: string | null
  bankAccount: string | null
  isActive: boolean | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type PartnerCountAggregateOutputType = {
  id: number
  code: number
  name: number
  address: number
  phone: number
  email: number
  contactName: number
  bankName: number
  bankAccount: number
  isActive: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type PartnerMinAggregateInputType = {
  id?: true
  code?: true
  name?: true
  address?: true
  phone?: true
  email?: true
  contactName?: true
  bankName?: true
  bankAccount?: true
  isActive?: true
  createdAt?: true
  updatedAt?: true
}

export type PartnerMaxAggregateInputType = {
  id?: true
  code?: true
  name?: true
  address?: true
  phone?: true
  email?: true
  contactName?: true
  bankName?: true
  bankAccount?: true
  isActive?: true
  createdAt?: true
  updatedAt?: true
}

export type PartnerCountAggregateInputType = {
  id?: true
  code?: true
  name?: true
  address?: true
  phone?: true
  email?: true
  contactName?: true
  bankName?: true
  bankAccount?: true
  isActive?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type PartnerAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Partner to aggregate.
   */
  where?: Prisma.PartnerWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Partners to fetch.
   */
  orderBy?: Prisma.PartnerOrderByWithRelationInput | Prisma.PartnerOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.PartnerWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Partners from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Partners.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Partners
  **/
  _count?: true | PartnerCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: PartnerMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: PartnerMaxAggregateInputType
}

export type GetPartnerAggregateType<T extends PartnerAggregateArgs> = {
      [P in keyof T & keyof AggregatePartner]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregatePartner[P]>
    : Prisma.GetScalarType<T[P], AggregatePartner[P]>
}




export type PartnerGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.PartnerWhereInput
  orderBy?: Prisma.PartnerOrderByWithAggregationInput | Prisma.PartnerOrderByWithAggregationInput[]
  by: Prisma.PartnerScalarFieldEnum[] | Prisma.PartnerScalarFieldEnum
  having?: Prisma.PartnerScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: PartnerCountAggregateInputType | true
  _min?: PartnerMinAggregateInputType
  _max?: PartnerMaxAggregateInputType
}

export type PartnerGroupByOutputType = {
  id: string
  code: string
  name: string
  address: string | null
  phone: string | null
  email: string | null
  contactName: string | null
  bankName: string | null
  bankAccount: string | null
  isActive: boolean
  createdAt: Date
  updatedAt: Date
  _count: PartnerCountAggregateOutputType | null
  _min: PartnerMinAggregateOutputType | null
  _max: PartnerMaxAggregateOutputType | null
}

type GetPartnerGroupByPayload<T extends PartnerGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<PartnerGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof PartnerGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], PartnerGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], PartnerGroupByOutputType[P]>
      }
    >
  >



export type PartnerWhereInput = {
  AND?: Prisma.PartnerWhereInput | Prisma.PartnerWhereInput[]
  OR?: Prisma.PartnerWhereInput[]
  NOT?: Prisma.PartnerWhereInput | Prisma.PartnerWhereInput[]
  id?: Prisma.StringFilter<"Partner"> | string
  code?: Prisma.StringFilter<"Partner"> | string
  name?: Prisma.StringFilter<"Partner"> | string
  address?: Prisma.StringNullableFilter<"Partner"> | string | null
  phone?: Prisma.StringNullableFilter<"Partner"> | string | null
  email?: Prisma.StringNullableFilter<"Partner"> | string | null
  contactName?: Prisma.StringNullableFilter<"Partner"> | string | null
  bankName?: Prisma.StringNullableFilter<"Partner"> | string | null
  bankAccount?: Prisma.StringNullableFilter<"Partner"> | string | null
  isActive?: Prisma.BoolFilter<"Partner"> | boolean
  createdAt?: Prisma.DateTimeFilter<"Partner"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Partner"> | Date | string
  outbounds?: Prisma.OutboundListRelationFilter
  itemPrices?: Prisma.PartnerItemPriceListRelationFilter
}

export type PartnerOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  code?: Prisma.SortOrder
  name?: Prisma.SortOrder
  address?: Prisma.SortOrderInput | Prisma.SortOrder
  phone?: Prisma.SortOrderInput | Prisma.SortOrder
  email?: Prisma.SortOrderInput | Prisma.SortOrder
  contactName?: Prisma.SortOrderInput | Prisma.SortOrder
  bankName?: Prisma.SortOrderInput | Prisma.SortOrder
  bankAccount?: Prisma.SortOrderInput | Prisma.SortOrder
  isActive?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  outbounds?: Prisma.OutboundOrderByRelationAggregateInput
  itemPrices?: Prisma.PartnerItemPriceOrderByRelationAggregateInput
}

export type PartnerWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  code?: string
  AND?: Prisma.PartnerWhereInput | Prisma.PartnerWhereInput[]
  OR?: Prisma.PartnerWhereInput[]
  NOT?: Prisma.PartnerWhereInput | Prisma.PartnerWhereInput[]
  name?: Prisma.StringFilter<"Partner"> | string
  address?: Prisma.StringNullableFilter<"Partner"> | string | null
  phone?: Prisma.StringNullableFilter<"Partner"> | string | null
  email?: Prisma.StringNullableFilter<"Partner"> | string | null
  contactName?: Prisma.StringNullableFilter<"Partner"> | string | null
  bankName?: Prisma.StringNullableFilter<"Partner"> | string | null
  bankAccount?: Prisma.StringNullableFilter<"Partner"> | string | null
  isActive?: Prisma.BoolFilter<"Partner"> | boolean
  createdAt?: Prisma.DateTimeFilter<"Partner"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Partner"> | Date | string
  outbounds?: Prisma.OutboundListRelationFilter
  itemPrices?: Prisma.PartnerItemPriceListRelationFilter
}, "id" | "code">

export type PartnerOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  code?: Prisma.SortOrder
  name?: Prisma.SortOrder
  address?: Prisma.SortOrderInput | Prisma.SortOrder
  phone?: Prisma.SortOrderInput | Prisma.SortOrder
  email?: Prisma.SortOrderInput | Prisma.SortOrder
  contactName?: Prisma.SortOrderInput | Prisma.SortOrder
  bankName?: Prisma.SortOrderInput | Prisma.SortOrder
  bankAccount?: Prisma.SortOrderInput | Prisma.SortOrder
  isActive?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.PartnerCountOrderByAggregateInput
  _max?: Prisma.PartnerMaxOrderByAggregateInput
  _min?: Prisma.PartnerMinOrderByAggregateInput
}

export type PartnerScalarWhereWithAggregatesInput = {
  AND?: Prisma.PartnerScalarWhereWithAggregatesInput | Prisma.PartnerScalarWhereWithAggregatesInput[]
  OR?: Prisma.PartnerScalarWhereWithAggregatesInput[]
  NOT?: Prisma.PartnerScalarWhereWithAggregatesInput | Prisma.PartnerScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Partner"> | string
  code?: Prisma.StringWithAggregatesFilter<"Partner"> | string
  name?: Prisma.StringWithAggregatesFilter<"Partner"> | string
  address?: Prisma.StringNullableWithAggregatesFilter<"Partner"> | string | null
  phone?: Prisma.StringNullableWithAggregatesFilter<"Partner"> | string | null
  email?: Prisma.StringNullableWithAggregatesFilter<"Partner"> | string | null
  contactName?: Prisma.StringNullableWithAggregatesFilter<"Partner"> | string | null
  bankName?: Prisma.StringNullableWithAggregatesFilter<"Partner"> | string | null
  bankAccount?: Prisma.StringNullableWithAggregatesFilter<"Partner"> | string | null
  isActive?: Prisma.BoolWithAggregatesFilter<"Partner"> | boolean
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Partner"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"Partner"> | Date | string
}

export type PartnerCreateInput = {
  id?: string
  code: string
  name: string
  address?: string | null
  phone?: string | null
  email?: string | null
  contactName?: string | null
  bankName?: string | null
  bankAccount?: string | null
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  outbounds?: Prisma.OutboundCreateNestedManyWithoutPartnerInput
  itemPrices?: Prisma.PartnerItemPriceCreateNestedManyWithoutPartnerInput
}

export type PartnerUncheckedCreateInput = {
  id?: string
  code: string
  name: string
  address?: string | null
  phone?: string | null
  email?: string | null
  contactName?: string | null
  bankName?: string | null
  bankAccount?: string | null
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  outbounds?: Prisma.OutboundUncheckedCreateNestedManyWithoutPartnerInput
  itemPrices?: Prisma.PartnerItemPriceUncheckedCreateNestedManyWithoutPartnerInput
}

export type PartnerUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  code?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  phone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  contactName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  bankName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  bankAccount?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  outbounds?: Prisma.OutboundUpdateManyWithoutPartnerNestedInput
  itemPrices?: Prisma.PartnerItemPriceUpdateManyWithoutPartnerNestedInput
}

export type PartnerUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  code?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  phone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  contactName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  bankName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  bankAccount?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  outbounds?: Prisma.OutboundUncheckedUpdateManyWithoutPartnerNestedInput
  itemPrices?: Prisma.PartnerItemPriceUncheckedUpdateManyWithoutPartnerNestedInput
}

export type PartnerCreateManyInput = {
  id?: string
  code: string
  name: string
  address?: string | null
  phone?: string | null
  email?: string | null
  contactName?: string | null
  bankName?: string | null
  bankAccount?: string | null
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type PartnerUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  code?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  phone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  contactName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  bankName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  bankAccount?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PartnerUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  code?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  phone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  contactName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  bankName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  bankAccount?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PartnerNullableScalarRelationFilter = {
  is?: Prisma.PartnerWhereInput | null
  isNot?: Prisma.PartnerWhereInput | null
}

export type PartnerCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  code?: Prisma.SortOrder
  name?: Prisma.SortOrder
  address?: Prisma.SortOrder
  phone?: Prisma.SortOrder
  email?: Prisma.SortOrder
  contactName?: Prisma.SortOrder
  bankName?: Prisma.SortOrder
  bankAccount?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type PartnerMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  code?: Prisma.SortOrder
  name?: Prisma.SortOrder
  address?: Prisma.SortOrder
  phone?: Prisma.SortOrder
  email?: Prisma.SortOrder
  contactName?: Prisma.SortOrder
  bankName?: Prisma.SortOrder
  bankAccount?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type PartnerMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  code?: Prisma.SortOrder
  name?: Prisma.SortOrder
  address?: Prisma.SortOrder
  phone?: Prisma.SortOrder
  email?: Prisma.SortOrder
  contactName?: Prisma.SortOrder
  bankName?: Prisma.SortOrder
  bankAccount?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type PartnerScalarRelationFilter = {
  is?: Prisma.PartnerWhereInput
  isNot?: Prisma.PartnerWhereInput
}

export type PartnerCreateNestedOneWithoutOutboundsInput = {
  create?: Prisma.XOR<Prisma.PartnerCreateWithoutOutboundsInput, Prisma.PartnerUncheckedCreateWithoutOutboundsInput>
  connectOrCreate?: Prisma.PartnerCreateOrConnectWithoutOutboundsInput
  connect?: Prisma.PartnerWhereUniqueInput
}

export type PartnerUpdateOneWithoutOutboundsNestedInput = {
  create?: Prisma.XOR<Prisma.PartnerCreateWithoutOutboundsInput, Prisma.PartnerUncheckedCreateWithoutOutboundsInput>
  connectOrCreate?: Prisma.PartnerCreateOrConnectWithoutOutboundsInput
  upsert?: Prisma.PartnerUpsertWithoutOutboundsInput
  disconnect?: Prisma.PartnerWhereInput | boolean
  delete?: Prisma.PartnerWhereInput | boolean
  connect?: Prisma.PartnerWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.PartnerUpdateToOneWithWhereWithoutOutboundsInput, Prisma.PartnerUpdateWithoutOutboundsInput>, Prisma.PartnerUncheckedUpdateWithoutOutboundsInput>
}

export type PartnerCreateNestedOneWithoutItemPricesInput = {
  create?: Prisma.XOR<Prisma.PartnerCreateWithoutItemPricesInput, Prisma.PartnerUncheckedCreateWithoutItemPricesInput>
  connectOrCreate?: Prisma.PartnerCreateOrConnectWithoutItemPricesInput
  connect?: Prisma.PartnerWhereUniqueInput
}

export type PartnerUpdateOneRequiredWithoutItemPricesNestedInput = {
  create?: Prisma.XOR<Prisma.PartnerCreateWithoutItemPricesInput, Prisma.PartnerUncheckedCreateWithoutItemPricesInput>
  connectOrCreate?: Prisma.PartnerCreateOrConnectWithoutItemPricesInput
  upsert?: Prisma.PartnerUpsertWithoutItemPricesInput
  connect?: Prisma.PartnerWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.PartnerUpdateToOneWithWhereWithoutItemPricesInput, Prisma.PartnerUpdateWithoutItemPricesInput>, Prisma.PartnerUncheckedUpdateWithoutItemPricesInput>
}

export type PartnerCreateWithoutOutboundsInput = {
  id?: string
  code: string
  name: string
  address?: string | null
  phone?: string | null
  email?: string | null
  contactName?: string | null
  bankName?: string | null
  bankAccount?: string | null
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  itemPrices?: Prisma.PartnerItemPriceCreateNestedManyWithoutPartnerInput
}

export type PartnerUncheckedCreateWithoutOutboundsInput = {
  id?: string
  code: string
  name: string
  address?: string | null
  phone?: string | null
  email?: string | null
  contactName?: string | null
  bankName?: string | null
  bankAccount?: string | null
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  itemPrices?: Prisma.PartnerItemPriceUncheckedCreateNestedManyWithoutPartnerInput
}

export type PartnerCreateOrConnectWithoutOutboundsInput = {
  where: Prisma.PartnerWhereUniqueInput
  create: Prisma.XOR<Prisma.PartnerCreateWithoutOutboundsInput, Prisma.PartnerUncheckedCreateWithoutOutboundsInput>
}

export type PartnerUpsertWithoutOutboundsInput = {
  update: Prisma.XOR<Prisma.PartnerUpdateWithoutOutboundsInput, Prisma.PartnerUncheckedUpdateWithoutOutboundsInput>
  create: Prisma.XOR<Prisma.PartnerCreateWithoutOutboundsInput, Prisma.PartnerUncheckedCreateWithoutOutboundsInput>
  where?: Prisma.PartnerWhereInput
}

export type PartnerUpdateToOneWithWhereWithoutOutboundsInput = {
  where?: Prisma.PartnerWhereInput
  data: Prisma.XOR<Prisma.PartnerUpdateWithoutOutboundsInput, Prisma.PartnerUncheckedUpdateWithoutOutboundsInput>
}

export type PartnerUpdateWithoutOutboundsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  code?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  phone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  contactName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  bankName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  bankAccount?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  itemPrices?: Prisma.PartnerItemPriceUpdateManyWithoutPartnerNestedInput
}

export type PartnerUncheckedUpdateWithoutOutboundsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  code?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  phone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  contactName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  bankName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  bankAccount?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  itemPrices?: Prisma.PartnerItemPriceUncheckedUpdateManyWithoutPartnerNestedInput
}

export type PartnerCreateWithoutItemPricesInput = {
  id?: string
  code: string
  name: string
  address?: string | null
  phone?: string | null
  email?: string | null
  contactName?: string | null
  bankName?: string | null
  bankAccount?: string | null
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  outbounds?: Prisma.OutboundCreateNestedManyWithoutPartnerInput
}

export type PartnerUncheckedCreateWithoutItemPricesInput = {
  id?: string
  code: string
  name: string
  address?: string | null
  phone?: string | null
  email?: string | null
  contactName?: string | null
  bankName?: string | null
  bankAccount?: string | null
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  outbounds?: Prisma.OutboundUncheckedCreateNestedManyWithoutPartnerInput
}

export type PartnerCreateOrConnectWithoutItemPricesInput = {
  where: Prisma.PartnerWhereUniqueInput
  create: Prisma.XOR<Prisma.PartnerCreateWithoutItemPricesInput, Prisma.PartnerUncheckedCreateWithoutItemPricesInput>
}

export type PartnerUpsertWithoutItemPricesInput = {
  update: Prisma.XOR<Prisma.PartnerUpdateWithoutItemPricesInput, Prisma.PartnerUncheckedUpdateWithoutItemPricesInput>
  create: Prisma.XOR<Prisma.PartnerCreateWithoutItemPricesInput, Prisma.PartnerUncheckedCreateWithoutItemPricesInput>
  where?: Prisma.PartnerWhereInput
}

export type PartnerUpdateToOneWithWhereWithoutItemPricesInput = {
  where?: Prisma.PartnerWhereInput
  data: Prisma.XOR<Prisma.PartnerUpdateWithoutItemPricesInput, Prisma.PartnerUncheckedUpdateWithoutItemPricesInput>
}

export type PartnerUpdateWithoutItemPricesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  code?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  phone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  contactName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  bankName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  bankAccount?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  outbounds?: Prisma.OutboundUpdateManyWithoutPartnerNestedInput
}

export type PartnerUncheckedUpdateWithoutItemPricesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  code?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  phone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  contactName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  bankName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  bankAccount?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  outbounds?: Prisma.OutboundUncheckedUpdateManyWithoutPartnerNestedInput
}


/**
 * Count Type PartnerCountOutputType
 */

export type PartnerCountOutputType = {
  outbounds: number
  itemPrices: number
}

export type PartnerCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  outbounds?: boolean | PartnerCountOutputTypeCountOutboundsArgs
  itemPrices?: boolean | PartnerCountOutputTypeCountItemPricesArgs
}

/**
 * PartnerCountOutputType without action
 */
export type PartnerCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PartnerCountOutputType
   */
  select?: Prisma.PartnerCountOutputTypeSelect<ExtArgs> | null
}

/**
 * PartnerCountOutputType without action
 */
export type PartnerCountOutputTypeCountOutboundsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.OutboundWhereInput
}

/**
 * PartnerCountOutputType without action
 */
export type PartnerCountOutputTypeCountItemPricesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.PartnerItemPriceWhereInput
}


export type PartnerSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  code?: boolean
  name?: boolean
  address?: boolean
  phone?: boolean
  email?: boolean
  contactName?: boolean
  bankName?: boolean
  bankAccount?: boolean
  isActive?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  outbounds?: boolean | Prisma.Partner$outboundsArgs<ExtArgs>
  itemPrices?: boolean | Prisma.Partner$itemPricesArgs<ExtArgs>
  _count?: boolean | Prisma.PartnerCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["partner"]>

export type PartnerSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  code?: boolean
  name?: boolean
  address?: boolean
  phone?: boolean
  email?: boolean
  contactName?: boolean
  bankName?: boolean
  bankAccount?: boolean
  isActive?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["partner"]>

export type PartnerSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  code?: boolean
  name?: boolean
  address?: boolean
  phone?: boolean
  email?: boolean
  contactName?: boolean
  bankName?: boolean
  bankAccount?: boolean
  isActive?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["partner"]>

export type PartnerSelectScalar = {
  id?: boolean
  code?: boolean
  name?: boolean
  address?: boolean
  phone?: boolean
  email?: boolean
  contactName?: boolean
  bankName?: boolean
  bankAccount?: boolean
  isActive?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type PartnerOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "code" | "name" | "address" | "phone" | "email" | "contactName" | "bankName" | "bankAccount" | "isActive" | "createdAt" | "updatedAt", ExtArgs["result"]["partner"]>
export type PartnerInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  outbounds?: boolean | Prisma.Partner$outboundsArgs<ExtArgs>
  itemPrices?: boolean | Prisma.Partner$itemPricesArgs<ExtArgs>
  _count?: boolean | Prisma.PartnerCountOutputTypeDefaultArgs<ExtArgs>
}
export type PartnerIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type PartnerIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $PartnerPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Partner"
  objects: {
    outbounds: Prisma.$OutboundPayload<ExtArgs>[]
    itemPrices: Prisma.$PartnerItemPricePayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    code: string
    name: string
    address: string | null
    phone: string | null
    email: string | null
    contactName: string | null
    bankName: string | null
    bankAccount: string | null
    isActive: boolean
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["partner"]>
  composites: {}
}

export type PartnerGetPayload<S extends boolean | null | undefined | PartnerDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$PartnerPayload, S>

export type PartnerCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<PartnerFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: PartnerCountAggregateInputType | true
  }

export interface PartnerDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Partner'], meta: { name: 'Partner' } }
  /**
   * Find zero or one Partner that matches the filter.
   * @param {PartnerFindUniqueArgs} args - Arguments to find a Partner
   * @example
   * // Get one Partner
   * const partner = await prisma.partner.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends PartnerFindUniqueArgs>(args: Prisma.SelectSubset<T, PartnerFindUniqueArgs<ExtArgs>>): Prisma.Prisma__PartnerClient<runtime.Types.Result.GetResult<Prisma.$PartnerPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Partner that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {PartnerFindUniqueOrThrowArgs} args - Arguments to find a Partner
   * @example
   * // Get one Partner
   * const partner = await prisma.partner.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends PartnerFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, PartnerFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__PartnerClient<runtime.Types.Result.GetResult<Prisma.$PartnerPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Partner that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PartnerFindFirstArgs} args - Arguments to find a Partner
   * @example
   * // Get one Partner
   * const partner = await prisma.partner.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends PartnerFindFirstArgs>(args?: Prisma.SelectSubset<T, PartnerFindFirstArgs<ExtArgs>>): Prisma.Prisma__PartnerClient<runtime.Types.Result.GetResult<Prisma.$PartnerPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Partner that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PartnerFindFirstOrThrowArgs} args - Arguments to find a Partner
   * @example
   * // Get one Partner
   * const partner = await prisma.partner.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends PartnerFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, PartnerFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__PartnerClient<runtime.Types.Result.GetResult<Prisma.$PartnerPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Partners that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PartnerFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Partners
   * const partners = await prisma.partner.findMany()
   * 
   * // Get first 10 Partners
   * const partners = await prisma.partner.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const partnerWithIdOnly = await prisma.partner.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends PartnerFindManyArgs>(args?: Prisma.SelectSubset<T, PartnerFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PartnerPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Partner.
   * @param {PartnerCreateArgs} args - Arguments to create a Partner.
   * @example
   * // Create one Partner
   * const Partner = await prisma.partner.create({
   *   data: {
   *     // ... data to create a Partner
   *   }
   * })
   * 
   */
  create<T extends PartnerCreateArgs>(args: Prisma.SelectSubset<T, PartnerCreateArgs<ExtArgs>>): Prisma.Prisma__PartnerClient<runtime.Types.Result.GetResult<Prisma.$PartnerPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Partners.
   * @param {PartnerCreateManyArgs} args - Arguments to create many Partners.
   * @example
   * // Create many Partners
   * const partner = await prisma.partner.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends PartnerCreateManyArgs>(args?: Prisma.SelectSubset<T, PartnerCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Partners and returns the data saved in the database.
   * @param {PartnerCreateManyAndReturnArgs} args - Arguments to create many Partners.
   * @example
   * // Create many Partners
   * const partner = await prisma.partner.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Partners and only return the `id`
   * const partnerWithIdOnly = await prisma.partner.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends PartnerCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, PartnerCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PartnerPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Partner.
   * @param {PartnerDeleteArgs} args - Arguments to delete one Partner.
   * @example
   * // Delete one Partner
   * const Partner = await prisma.partner.delete({
   *   where: {
   *     // ... filter to delete one Partner
   *   }
   * })
   * 
   */
  delete<T extends PartnerDeleteArgs>(args: Prisma.SelectSubset<T, PartnerDeleteArgs<ExtArgs>>): Prisma.Prisma__PartnerClient<runtime.Types.Result.GetResult<Prisma.$PartnerPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Partner.
   * @param {PartnerUpdateArgs} args - Arguments to update one Partner.
   * @example
   * // Update one Partner
   * const partner = await prisma.partner.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends PartnerUpdateArgs>(args: Prisma.SelectSubset<T, PartnerUpdateArgs<ExtArgs>>): Prisma.Prisma__PartnerClient<runtime.Types.Result.GetResult<Prisma.$PartnerPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Partners.
   * @param {PartnerDeleteManyArgs} args - Arguments to filter Partners to delete.
   * @example
   * // Delete a few Partners
   * const { count } = await prisma.partner.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends PartnerDeleteManyArgs>(args?: Prisma.SelectSubset<T, PartnerDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Partners.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PartnerUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Partners
   * const partner = await prisma.partner.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends PartnerUpdateManyArgs>(args: Prisma.SelectSubset<T, PartnerUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Partners and returns the data updated in the database.
   * @param {PartnerUpdateManyAndReturnArgs} args - Arguments to update many Partners.
   * @example
   * // Update many Partners
   * const partner = await prisma.partner.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Partners and only return the `id`
   * const partnerWithIdOnly = await prisma.partner.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends PartnerUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, PartnerUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PartnerPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Partner.
   * @param {PartnerUpsertArgs} args - Arguments to update or create a Partner.
   * @example
   * // Update or create a Partner
   * const partner = await prisma.partner.upsert({
   *   create: {
   *     // ... data to create a Partner
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Partner we want to update
   *   }
   * })
   */
  upsert<T extends PartnerUpsertArgs>(args: Prisma.SelectSubset<T, PartnerUpsertArgs<ExtArgs>>): Prisma.Prisma__PartnerClient<runtime.Types.Result.GetResult<Prisma.$PartnerPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Partners.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PartnerCountArgs} args - Arguments to filter Partners to count.
   * @example
   * // Count the number of Partners
   * const count = await prisma.partner.count({
   *   where: {
   *     // ... the filter for the Partners we want to count
   *   }
   * })
  **/
  count<T extends PartnerCountArgs>(
    args?: Prisma.Subset<T, PartnerCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], PartnerCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Partner.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PartnerAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends PartnerAggregateArgs>(args: Prisma.Subset<T, PartnerAggregateArgs>): Prisma.PrismaPromise<GetPartnerAggregateType<T>>

  /**
   * Group by Partner.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PartnerGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends PartnerGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: PartnerGroupByArgs['orderBy'] }
      : { orderBy?: PartnerGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, PartnerGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetPartnerGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Partner model
 */
readonly fields: PartnerFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Partner.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__PartnerClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  outbounds<T extends Prisma.Partner$outboundsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Partner$outboundsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$OutboundPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  itemPrices<T extends Prisma.Partner$itemPricesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Partner$itemPricesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PartnerItemPricePayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Partner model
 */
export interface PartnerFieldRefs {
  readonly id: Prisma.FieldRef<"Partner", 'String'>
  readonly code: Prisma.FieldRef<"Partner", 'String'>
  readonly name: Prisma.FieldRef<"Partner", 'String'>
  readonly address: Prisma.FieldRef<"Partner", 'String'>
  readonly phone: Prisma.FieldRef<"Partner", 'String'>
  readonly email: Prisma.FieldRef<"Partner", 'String'>
  readonly contactName: Prisma.FieldRef<"Partner", 'String'>
  readonly bankName: Prisma.FieldRef<"Partner", 'String'>
  readonly bankAccount: Prisma.FieldRef<"Partner", 'String'>
  readonly isActive: Prisma.FieldRef<"Partner", 'Boolean'>
  readonly createdAt: Prisma.FieldRef<"Partner", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"Partner", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Partner findUnique
 */
export type PartnerFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Partner
   */
  select?: Prisma.PartnerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Partner
   */
  omit?: Prisma.PartnerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PartnerInclude<ExtArgs> | null
  /**
   * Filter, which Partner to fetch.
   */
  where: Prisma.PartnerWhereUniqueInput
}

/**
 * Partner findUniqueOrThrow
 */
export type PartnerFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Partner
   */
  select?: Prisma.PartnerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Partner
   */
  omit?: Prisma.PartnerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PartnerInclude<ExtArgs> | null
  /**
   * Filter, which Partner to fetch.
   */
  where: Prisma.PartnerWhereUniqueInput
}

/**
 * Partner findFirst
 */
export type PartnerFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Partner
   */
  select?: Prisma.PartnerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Partner
   */
  omit?: Prisma.PartnerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PartnerInclude<ExtArgs> | null
  /**
   * Filter, which Partner to fetch.
   */
  where?: Prisma.PartnerWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Partners to fetch.
   */
  orderBy?: Prisma.PartnerOrderByWithRelationInput | Prisma.PartnerOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Partners.
   */
  cursor?: Prisma.PartnerWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Partners from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Partners.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Partners.
   */
  distinct?: Prisma.PartnerScalarFieldEnum | Prisma.PartnerScalarFieldEnum[]
}

/**
 * Partner findFirstOrThrow
 */
export type PartnerFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Partner
   */
  select?: Prisma.PartnerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Partner
   */
  omit?: Prisma.PartnerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PartnerInclude<ExtArgs> | null
  /**
   * Filter, which Partner to fetch.
   */
  where?: Prisma.PartnerWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Partners to fetch.
   */
  orderBy?: Prisma.PartnerOrderByWithRelationInput | Prisma.PartnerOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Partners.
   */
  cursor?: Prisma.PartnerWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Partners from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Partners.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Partners.
   */
  distinct?: Prisma.PartnerScalarFieldEnum | Prisma.PartnerScalarFieldEnum[]
}

/**
 * Partner findMany
 */
export type PartnerFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Partner
   */
  select?: Prisma.PartnerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Partner
   */
  omit?: Prisma.PartnerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PartnerInclude<ExtArgs> | null
  /**
   * Filter, which Partners to fetch.
   */
  where?: Prisma.PartnerWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Partners to fetch.
   */
  orderBy?: Prisma.PartnerOrderByWithRelationInput | Prisma.PartnerOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Partners.
   */
  cursor?: Prisma.PartnerWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Partners from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Partners.
   */
  skip?: number
  distinct?: Prisma.PartnerScalarFieldEnum | Prisma.PartnerScalarFieldEnum[]
}

/**
 * Partner create
 */
export type PartnerCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Partner
   */
  select?: Prisma.PartnerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Partner
   */
  omit?: Prisma.PartnerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PartnerInclude<ExtArgs> | null
  /**
   * The data needed to create a Partner.
   */
  data: Prisma.XOR<Prisma.PartnerCreateInput, Prisma.PartnerUncheckedCreateInput>
}

/**
 * Partner createMany
 */
export type PartnerCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Partners.
   */
  data: Prisma.PartnerCreateManyInput | Prisma.PartnerCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Partner createManyAndReturn
 */
export type PartnerCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Partner
   */
  select?: Prisma.PartnerSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Partner
   */
  omit?: Prisma.PartnerOmit<ExtArgs> | null
  /**
   * The data used to create many Partners.
   */
  data: Prisma.PartnerCreateManyInput | Prisma.PartnerCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Partner update
 */
export type PartnerUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Partner
   */
  select?: Prisma.PartnerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Partner
   */
  omit?: Prisma.PartnerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PartnerInclude<ExtArgs> | null
  /**
   * The data needed to update a Partner.
   */
  data: Prisma.XOR<Prisma.PartnerUpdateInput, Prisma.PartnerUncheckedUpdateInput>
  /**
   * Choose, which Partner to update.
   */
  where: Prisma.PartnerWhereUniqueInput
}

/**
 * Partner updateMany
 */
export type PartnerUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Partners.
   */
  data: Prisma.XOR<Prisma.PartnerUpdateManyMutationInput, Prisma.PartnerUncheckedUpdateManyInput>
  /**
   * Filter which Partners to update
   */
  where?: Prisma.PartnerWhereInput
  /**
   * Limit how many Partners to update.
   */
  limit?: number
}

/**
 * Partner updateManyAndReturn
 */
export type PartnerUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Partner
   */
  select?: Prisma.PartnerSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Partner
   */
  omit?: Prisma.PartnerOmit<ExtArgs> | null
  /**
   * The data used to update Partners.
   */
  data: Prisma.XOR<Prisma.PartnerUpdateManyMutationInput, Prisma.PartnerUncheckedUpdateManyInput>
  /**
   * Filter which Partners to update
   */
  where?: Prisma.PartnerWhereInput
  /**
   * Limit how many Partners to update.
   */
  limit?: number
}

/**
 * Partner upsert
 */
export type PartnerUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Partner
   */
  select?: Prisma.PartnerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Partner
   */
  omit?: Prisma.PartnerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PartnerInclude<ExtArgs> | null
  /**
   * The filter to search for the Partner to update in case it exists.
   */
  where: Prisma.PartnerWhereUniqueInput
  /**
   * In case the Partner found by the `where` argument doesn't exist, create a new Partner with this data.
   */
  create: Prisma.XOR<Prisma.PartnerCreateInput, Prisma.PartnerUncheckedCreateInput>
  /**
   * In case the Partner was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.PartnerUpdateInput, Prisma.PartnerUncheckedUpdateInput>
}

/**
 * Partner delete
 */
export type PartnerDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Partner
   */
  select?: Prisma.PartnerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Partner
   */
  omit?: Prisma.PartnerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PartnerInclude<ExtArgs> | null
  /**
   * Filter which Partner to delete.
   */
  where: Prisma.PartnerWhereUniqueInput
}

/**
 * Partner deleteMany
 */
export type PartnerDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Partners to delete
   */
  where?: Prisma.PartnerWhereInput
  /**
   * Limit how many Partners to delete.
   */
  limit?: number
}

/**
 * Partner.outbounds
 */
export type Partner$outboundsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Outbound
   */
  select?: Prisma.OutboundSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Outbound
   */
  omit?: Prisma.OutboundOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OutboundInclude<ExtArgs> | null
  where?: Prisma.OutboundWhereInput
  orderBy?: Prisma.OutboundOrderByWithRelationInput | Prisma.OutboundOrderByWithRelationInput[]
  cursor?: Prisma.OutboundWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.OutboundScalarFieldEnum | Prisma.OutboundScalarFieldEnum[]
}

/**
 * Partner.itemPrices
 */
export type Partner$itemPricesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PartnerItemPrice
   */
  select?: Prisma.PartnerItemPriceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PartnerItemPrice
   */
  omit?: Prisma.PartnerItemPriceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PartnerItemPriceInclude<ExtArgs> | null
  where?: Prisma.PartnerItemPriceWhereInput
  orderBy?: Prisma.PartnerItemPriceOrderByWithRelationInput | Prisma.PartnerItemPriceOrderByWithRelationInput[]
  cursor?: Prisma.PartnerItemPriceWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.PartnerItemPriceScalarFieldEnum | Prisma.PartnerItemPriceScalarFieldEnum[]
}

/**
 * Partner without action
 */
export type PartnerDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Partner
   */
  select?: Prisma.PartnerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Partner
   */
  omit?: Prisma.PartnerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PartnerInclude<ExtArgs> | null
}
