
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `PartnerItemPrice` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model PartnerItemPrice
 * 
 */
export type PartnerItemPriceModel = runtime.Types.Result.DefaultSelection<Prisma.$PartnerItemPricePayload>

export type AggregatePartnerItemPrice = {
  _count: PartnerItemPriceCountAggregateOutputType | null
  _avg: PartnerItemPriceAvgAggregateOutputType | null
  _sum: PartnerItemPriceSumAggregateOutputType | null
  _min: PartnerItemPriceMinAggregateOutputType | null
  _max: PartnerItemPriceMaxAggregateOutputType | null
}

export type PartnerItemPriceAvgAggregateOutputType = {
  price: runtime.Decimal | null
}

export type PartnerItemPriceSumAggregateOutputType = {
  price: runtime.Decimal | null
}

export type PartnerItemPriceMinAggregateOutputType = {
  id: string | null
  partnerId: string | null
  itemId: string | null
  price: runtime.Decimal | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type PartnerItemPriceMaxAggregateOutputType = {
  id: string | null
  partnerId: string | null
  itemId: string | null
  price: runtime.Decimal | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type PartnerItemPriceCountAggregateOutputType = {
  id: number
  partnerId: number
  itemId: number
  price: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type PartnerItemPriceAvgAggregateInputType = {
  price?: true
}

export type PartnerItemPriceSumAggregateInputType = {
  price?: true
}

export type PartnerItemPriceMinAggregateInputType = {
  id?: true
  partnerId?: true
  itemId?: true
  price?: true
  createdAt?: true
  updatedAt?: true
}

export type PartnerItemPriceMaxAggregateInputType = {
  id?: true
  partnerId?: true
  itemId?: true
  price?: true
  createdAt?: true
  updatedAt?: true
}

export type PartnerItemPriceCountAggregateInputType = {
  id?: true
  partnerId?: true
  itemId?: true
  price?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type PartnerItemPriceAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which PartnerItemPrice to aggregate.
   */
  where?: Prisma.PartnerItemPriceWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PartnerItemPrices to fetch.
   */
  orderBy?: Prisma.PartnerItemPriceOrderByWithRelationInput | Prisma.PartnerItemPriceOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.PartnerItemPriceWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PartnerItemPrices from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PartnerItemPrices.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned PartnerItemPrices
  **/
  _count?: true | PartnerItemPriceCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: PartnerItemPriceAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: PartnerItemPriceSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: PartnerItemPriceMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: PartnerItemPriceMaxAggregateInputType
}

export type GetPartnerItemPriceAggregateType<T extends PartnerItemPriceAggregateArgs> = {
      [P in keyof T & keyof AggregatePartnerItemPrice]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregatePartnerItemPrice[P]>
    : Prisma.GetScalarType<T[P], AggregatePartnerItemPrice[P]>
}




export type PartnerItemPriceGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.PartnerItemPriceWhereInput
  orderBy?: Prisma.PartnerItemPriceOrderByWithAggregationInput | Prisma.PartnerItemPriceOrderByWithAggregationInput[]
  by: Prisma.PartnerItemPriceScalarFieldEnum[] | Prisma.PartnerItemPriceScalarFieldEnum
  having?: Prisma.PartnerItemPriceScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: PartnerItemPriceCountAggregateInputType | true
  _avg?: PartnerItemPriceAvgAggregateInputType
  _sum?: PartnerItemPriceSumAggregateInputType
  _min?: PartnerItemPriceMinAggregateInputType
  _max?: PartnerItemPriceMaxAggregateInputType
}

export type PartnerItemPriceGroupByOutputType = {
  id: string
  partnerId: string
  itemId: string
  price: runtime.Decimal
  createdAt: Date
  updatedAt: Date
  _count: PartnerItemPriceCountAggregateOutputType | null
  _avg: PartnerItemPriceAvgAggregateOutputType | null
  _sum: PartnerItemPriceSumAggregateOutputType | null
  _min: PartnerItemPriceMinAggregateOutputType | null
  _max: PartnerItemPriceMaxAggregateOutputType | null
}

type GetPartnerItemPriceGroupByPayload<T extends PartnerItemPriceGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<PartnerItemPriceGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof PartnerItemPriceGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], PartnerItemPriceGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], PartnerItemPriceGroupByOutputType[P]>
      }
    >
  >



export type PartnerItemPriceWhereInput = {
  AND?: Prisma.PartnerItemPriceWhereInput | Prisma.PartnerItemPriceWhereInput[]
  OR?: Prisma.PartnerItemPriceWhereInput[]
  NOT?: Prisma.PartnerItemPriceWhereInput | Prisma.PartnerItemPriceWhereInput[]
  id?: Prisma.StringFilter<"PartnerItemPrice"> | string
  partnerId?: Prisma.StringFilter<"PartnerItemPrice"> | string
  itemId?: Prisma.StringFilter<"PartnerItemPrice"> | string
  price?: Prisma.DecimalFilter<"PartnerItemPrice"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Prisma.DateTimeFilter<"PartnerItemPrice"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"PartnerItemPrice"> | Date | string
  partner?: Prisma.XOR<Prisma.PartnerScalarRelationFilter, Prisma.PartnerWhereInput>
  item?: Prisma.XOR<Prisma.ItemScalarRelationFilter, Prisma.ItemWhereInput>
}

export type PartnerItemPriceOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  partnerId?: Prisma.SortOrder
  itemId?: Prisma.SortOrder
  price?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  partner?: Prisma.PartnerOrderByWithRelationInput
  item?: Prisma.ItemOrderByWithRelationInput
}

export type PartnerItemPriceWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  partnerId_itemId?: Prisma.PartnerItemPricePartnerIdItemIdCompoundUniqueInput
  AND?: Prisma.PartnerItemPriceWhereInput | Prisma.PartnerItemPriceWhereInput[]
  OR?: Prisma.PartnerItemPriceWhereInput[]
  NOT?: Prisma.PartnerItemPriceWhereInput | Prisma.PartnerItemPriceWhereInput[]
  partnerId?: Prisma.StringFilter<"PartnerItemPrice"> | string
  itemId?: Prisma.StringFilter<"PartnerItemPrice"> | string
  price?: Prisma.DecimalFilter<"PartnerItemPrice"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Prisma.DateTimeFilter<"PartnerItemPrice"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"PartnerItemPrice"> | Date | string
  partner?: Prisma.XOR<Prisma.PartnerScalarRelationFilter, Prisma.PartnerWhereInput>
  item?: Prisma.XOR<Prisma.ItemScalarRelationFilter, Prisma.ItemWhereInput>
}, "id" | "partnerId_itemId">

export type PartnerItemPriceOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  partnerId?: Prisma.SortOrder
  itemId?: Prisma.SortOrder
  price?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.PartnerItemPriceCountOrderByAggregateInput
  _avg?: Prisma.PartnerItemPriceAvgOrderByAggregateInput
  _max?: Prisma.PartnerItemPriceMaxOrderByAggregateInput
  _min?: Prisma.PartnerItemPriceMinOrderByAggregateInput
  _sum?: Prisma.PartnerItemPriceSumOrderByAggregateInput
}

export type PartnerItemPriceScalarWhereWithAggregatesInput = {
  AND?: Prisma.PartnerItemPriceScalarWhereWithAggregatesInput | Prisma.PartnerItemPriceScalarWhereWithAggregatesInput[]
  OR?: Prisma.PartnerItemPriceScalarWhereWithAggregatesInput[]
  NOT?: Prisma.PartnerItemPriceScalarWhereWithAggregatesInput | Prisma.PartnerItemPriceScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"PartnerItemPrice"> | string
  partnerId?: Prisma.StringWithAggregatesFilter<"PartnerItemPrice"> | string
  itemId?: Prisma.StringWithAggregatesFilter<"PartnerItemPrice"> | string
  price?: Prisma.DecimalWithAggregatesFilter<"PartnerItemPrice"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"PartnerItemPrice"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"PartnerItemPrice"> | Date | string
}

export type PartnerItemPriceCreateInput = {
  id?: string
  price: runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Date | string
  updatedAt?: Date | string
  partner: Prisma.PartnerCreateNestedOneWithoutItemPricesInput
  item: Prisma.ItemCreateNestedOneWithoutPartnerPricesInput
}

export type PartnerItemPriceUncheckedCreateInput = {
  id?: string
  partnerId: string
  itemId: string
  price: runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type PartnerItemPriceUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  price?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  partner?: Prisma.PartnerUpdateOneRequiredWithoutItemPricesNestedInput
  item?: Prisma.ItemUpdateOneRequiredWithoutPartnerPricesNestedInput
}

export type PartnerItemPriceUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  partnerId?: Prisma.StringFieldUpdateOperationsInput | string
  itemId?: Prisma.StringFieldUpdateOperationsInput | string
  price?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PartnerItemPriceCreateManyInput = {
  id?: string
  partnerId: string
  itemId: string
  price: runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type PartnerItemPriceUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  price?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PartnerItemPriceUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  partnerId?: Prisma.StringFieldUpdateOperationsInput | string
  itemId?: Prisma.StringFieldUpdateOperationsInput | string
  price?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PartnerItemPriceListRelationFilter = {
  every?: Prisma.PartnerItemPriceWhereInput
  some?: Prisma.PartnerItemPriceWhereInput
  none?: Prisma.PartnerItemPriceWhereInput
}

export type PartnerItemPriceOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type PartnerItemPricePartnerIdItemIdCompoundUniqueInput = {
  partnerId: string
  itemId: string
}

export type PartnerItemPriceCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  partnerId?: Prisma.SortOrder
  itemId?: Prisma.SortOrder
  price?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type PartnerItemPriceAvgOrderByAggregateInput = {
  price?: Prisma.SortOrder
}

export type PartnerItemPriceMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  partnerId?: Prisma.SortOrder
  itemId?: Prisma.SortOrder
  price?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type PartnerItemPriceMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  partnerId?: Prisma.SortOrder
  itemId?: Prisma.SortOrder
  price?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type PartnerItemPriceSumOrderByAggregateInput = {
  price?: Prisma.SortOrder
}

export type PartnerItemPriceCreateNestedManyWithoutItemInput = {
  create?: Prisma.XOR<Prisma.PartnerItemPriceCreateWithoutItemInput, Prisma.PartnerItemPriceUncheckedCreateWithoutItemInput> | Prisma.PartnerItemPriceCreateWithoutItemInput[] | Prisma.PartnerItemPriceUncheckedCreateWithoutItemInput[]
  connectOrCreate?: Prisma.PartnerItemPriceCreateOrConnectWithoutItemInput | Prisma.PartnerItemPriceCreateOrConnectWithoutItemInput[]
  createMany?: Prisma.PartnerItemPriceCreateManyItemInputEnvelope
  connect?: Prisma.PartnerItemPriceWhereUniqueInput | Prisma.PartnerItemPriceWhereUniqueInput[]
}

export type PartnerItemPriceUncheckedCreateNestedManyWithoutItemInput = {
  create?: Prisma.XOR<Prisma.PartnerItemPriceCreateWithoutItemInput, Prisma.PartnerItemPriceUncheckedCreateWithoutItemInput> | Prisma.PartnerItemPriceCreateWithoutItemInput[] | Prisma.PartnerItemPriceUncheckedCreateWithoutItemInput[]
  connectOrCreate?: Prisma.PartnerItemPriceCreateOrConnectWithoutItemInput | Prisma.PartnerItemPriceCreateOrConnectWithoutItemInput[]
  createMany?: Prisma.PartnerItemPriceCreateManyItemInputEnvelope
  connect?: Prisma.PartnerItemPriceWhereUniqueInput | Prisma.PartnerItemPriceWhereUniqueInput[]
}

export type PartnerItemPriceUpdateManyWithoutItemNestedInput = {
  create?: Prisma.XOR<Prisma.PartnerItemPriceCreateWithoutItemInput, Prisma.PartnerItemPriceUncheckedCreateWithoutItemInput> | Prisma.PartnerItemPriceCreateWithoutItemInput[] | Prisma.PartnerItemPriceUncheckedCreateWithoutItemInput[]
  connectOrCreate?: Prisma.PartnerItemPriceCreateOrConnectWithoutItemInput | Prisma.PartnerItemPriceCreateOrConnectWithoutItemInput[]
  upsert?: Prisma.PartnerItemPriceUpsertWithWhereUniqueWithoutItemInput | Prisma.PartnerItemPriceUpsertWithWhereUniqueWithoutItemInput[]
  createMany?: Prisma.PartnerItemPriceCreateManyItemInputEnvelope
  set?: Prisma.PartnerItemPriceWhereUniqueInput | Prisma.PartnerItemPriceWhereUniqueInput[]
  disconnect?: Prisma.PartnerItemPriceWhereUniqueInput | Prisma.PartnerItemPriceWhereUniqueInput[]
  delete?: Prisma.PartnerItemPriceWhereUniqueInput | Prisma.PartnerItemPriceWhereUniqueInput[]
  connect?: Prisma.PartnerItemPriceWhereUniqueInput | Prisma.PartnerItemPriceWhereUniqueInput[]
  update?: Prisma.PartnerItemPriceUpdateWithWhereUniqueWithoutItemInput | Prisma.PartnerItemPriceUpdateWithWhereUniqueWithoutItemInput[]
  updateMany?: Prisma.PartnerItemPriceUpdateManyWithWhereWithoutItemInput | Prisma.PartnerItemPriceUpdateManyWithWhereWithoutItemInput[]
  deleteMany?: Prisma.PartnerItemPriceScalarWhereInput | Prisma.PartnerItemPriceScalarWhereInput[]
}

export type PartnerItemPriceUncheckedUpdateManyWithoutItemNestedInput = {
  create?: Prisma.XOR<Prisma.PartnerItemPriceCreateWithoutItemInput, Prisma.PartnerItemPriceUncheckedCreateWithoutItemInput> | Prisma.PartnerItemPriceCreateWithoutItemInput[] | Prisma.PartnerItemPriceUncheckedCreateWithoutItemInput[]
  connectOrCreate?: Prisma.PartnerItemPriceCreateOrConnectWithoutItemInput | Prisma.PartnerItemPriceCreateOrConnectWithoutItemInput[]
  upsert?: Prisma.PartnerItemPriceUpsertWithWhereUniqueWithoutItemInput | Prisma.PartnerItemPriceUpsertWithWhereUniqueWithoutItemInput[]
  createMany?: Prisma.PartnerItemPriceCreateManyItemInputEnvelope
  set?: Prisma.PartnerItemPriceWhereUniqueInput | Prisma.PartnerItemPriceWhereUniqueInput[]
  disconnect?: Prisma.PartnerItemPriceWhereUniqueInput | Prisma.PartnerItemPriceWhereUniqueInput[]
  delete?: Prisma.PartnerItemPriceWhereUniqueInput | Prisma.PartnerItemPriceWhereUniqueInput[]
  connect?: Prisma.PartnerItemPriceWhereUniqueInput | Prisma.PartnerItemPriceWhereUniqueInput[]
  update?: Prisma.PartnerItemPriceUpdateWithWhereUniqueWithoutItemInput | Prisma.PartnerItemPriceUpdateWithWhereUniqueWithoutItemInput[]
  updateMany?: Prisma.PartnerItemPriceUpdateManyWithWhereWithoutItemInput | Prisma.PartnerItemPriceUpdateManyWithWhereWithoutItemInput[]
  deleteMany?: Prisma.PartnerItemPriceScalarWhereInput | Prisma.PartnerItemPriceScalarWhereInput[]
}

export type PartnerItemPriceCreateNestedManyWithoutPartnerInput = {
  create?: Prisma.XOR<Prisma.PartnerItemPriceCreateWithoutPartnerInput, Prisma.PartnerItemPriceUncheckedCreateWithoutPartnerInput> | Prisma.PartnerItemPriceCreateWithoutPartnerInput[] | Prisma.PartnerItemPriceUncheckedCreateWithoutPartnerInput[]
  connectOrCreate?: Prisma.PartnerItemPriceCreateOrConnectWithoutPartnerInput | Prisma.PartnerItemPriceCreateOrConnectWithoutPartnerInput[]
  createMany?: Prisma.PartnerItemPriceCreateManyPartnerInputEnvelope
  connect?: Prisma.PartnerItemPriceWhereUniqueInput | Prisma.PartnerItemPriceWhereUniqueInput[]
}

export type PartnerItemPriceUncheckedCreateNestedManyWithoutPartnerInput = {
  create?: Prisma.XOR<Prisma.PartnerItemPriceCreateWithoutPartnerInput, Prisma.PartnerItemPriceUncheckedCreateWithoutPartnerInput> | Prisma.PartnerItemPriceCreateWithoutPartnerInput[] | Prisma.PartnerItemPriceUncheckedCreateWithoutPartnerInput[]
  connectOrCreate?: Prisma.PartnerItemPriceCreateOrConnectWithoutPartnerInput | Prisma.PartnerItemPriceCreateOrConnectWithoutPartnerInput[]
  createMany?: Prisma.PartnerItemPriceCreateManyPartnerInputEnvelope
  connect?: Prisma.PartnerItemPriceWhereUniqueInput | Prisma.PartnerItemPriceWhereUniqueInput[]
}

export type PartnerItemPriceUpdateManyWithoutPartnerNestedInput = {
  create?: Prisma.XOR<Prisma.PartnerItemPriceCreateWithoutPartnerInput, Prisma.PartnerItemPriceUncheckedCreateWithoutPartnerInput> | Prisma.PartnerItemPriceCreateWithoutPartnerInput[] | Prisma.PartnerItemPriceUncheckedCreateWithoutPartnerInput[]
  connectOrCreate?: Prisma.PartnerItemPriceCreateOrConnectWithoutPartnerInput | Prisma.PartnerItemPriceCreateOrConnectWithoutPartnerInput[]
  upsert?: Prisma.PartnerItemPriceUpsertWithWhereUniqueWithoutPartnerInput | Prisma.PartnerItemPriceUpsertWithWhereUniqueWithoutPartnerInput[]
  createMany?: Prisma.PartnerItemPriceCreateManyPartnerInputEnvelope
  set?: Prisma.PartnerItemPriceWhereUniqueInput | Prisma.PartnerItemPriceWhereUniqueInput[]
  disconnect?: Prisma.PartnerItemPriceWhereUniqueInput | Prisma.PartnerItemPriceWhereUniqueInput[]
  delete?: Prisma.PartnerItemPriceWhereUniqueInput | Prisma.PartnerItemPriceWhereUniqueInput[]
  connect?: Prisma.PartnerItemPriceWhereUniqueInput | Prisma.PartnerItemPriceWhereUniqueInput[]
  update?: Prisma.PartnerItemPriceUpdateWithWhereUniqueWithoutPartnerInput | Prisma.PartnerItemPriceUpdateWithWhereUniqueWithoutPartnerInput[]
  updateMany?: Prisma.PartnerItemPriceUpdateManyWithWhereWithoutPartnerInput | Prisma.PartnerItemPriceUpdateManyWithWhereWithoutPartnerInput[]
  deleteMany?: Prisma.PartnerItemPriceScalarWhereInput | Prisma.PartnerItemPriceScalarWhereInput[]
}

export type PartnerItemPriceUncheckedUpdateManyWithoutPartnerNestedInput = {
  create?: Prisma.XOR<Prisma.PartnerItemPriceCreateWithoutPartnerInput, Prisma.PartnerItemPriceUncheckedCreateWithoutPartnerInput> | Prisma.PartnerItemPriceCreateWithoutPartnerInput[] | Prisma.PartnerItemPriceUncheckedCreateWithoutPartnerInput[]
  connectOrCreate?: Prisma.PartnerItemPriceCreateOrConnectWithoutPartnerInput | Prisma.PartnerItemPriceCreateOrConnectWithoutPartnerInput[]
  upsert?: Prisma.PartnerItemPriceUpsertWithWhereUniqueWithoutPartnerInput | Prisma.PartnerItemPriceUpsertWithWhereUniqueWithoutPartnerInput[]
  createMany?: Prisma.PartnerItemPriceCreateManyPartnerInputEnvelope
  set?: Prisma.PartnerItemPriceWhereUniqueInput | Prisma.PartnerItemPriceWhereUniqueInput[]
  disconnect?: Prisma.PartnerItemPriceWhereUniqueInput | Prisma.PartnerItemPriceWhereUniqueInput[]
  delete?: Prisma.PartnerItemPriceWhereUniqueInput | Prisma.PartnerItemPriceWhereUniqueInput[]
  connect?: Prisma.PartnerItemPriceWhereUniqueInput | Prisma.PartnerItemPriceWhereUniqueInput[]
  update?: Prisma.PartnerItemPriceUpdateWithWhereUniqueWithoutPartnerInput | Prisma.PartnerItemPriceUpdateWithWhereUniqueWithoutPartnerInput[]
  updateMany?: Prisma.PartnerItemPriceUpdateManyWithWhereWithoutPartnerInput | Prisma.PartnerItemPriceUpdateManyWithWhereWithoutPartnerInput[]
  deleteMany?: Prisma.PartnerItemPriceScalarWhereInput | Prisma.PartnerItemPriceScalarWhereInput[]
}

export type PartnerItemPriceCreateWithoutItemInput = {
  id?: string
  price: runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Date | string
  updatedAt?: Date | string
  partner: Prisma.PartnerCreateNestedOneWithoutItemPricesInput
}

export type PartnerItemPriceUncheckedCreateWithoutItemInput = {
  id?: string
  partnerId: string
  price: runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type PartnerItemPriceCreateOrConnectWithoutItemInput = {
  where: Prisma.PartnerItemPriceWhereUniqueInput
  create: Prisma.XOR<Prisma.PartnerItemPriceCreateWithoutItemInput, Prisma.PartnerItemPriceUncheckedCreateWithoutItemInput>
}

export type PartnerItemPriceCreateManyItemInputEnvelope = {
  data: Prisma.PartnerItemPriceCreateManyItemInput | Prisma.PartnerItemPriceCreateManyItemInput[]
  skipDuplicates?: boolean
}

export type PartnerItemPriceUpsertWithWhereUniqueWithoutItemInput = {
  where: Prisma.PartnerItemPriceWhereUniqueInput
  update: Prisma.XOR<Prisma.PartnerItemPriceUpdateWithoutItemInput, Prisma.PartnerItemPriceUncheckedUpdateWithoutItemInput>
  create: Prisma.XOR<Prisma.PartnerItemPriceCreateWithoutItemInput, Prisma.PartnerItemPriceUncheckedCreateWithoutItemInput>
}

export type PartnerItemPriceUpdateWithWhereUniqueWithoutItemInput = {
  where: Prisma.PartnerItemPriceWhereUniqueInput
  data: Prisma.XOR<Prisma.PartnerItemPriceUpdateWithoutItemInput, Prisma.PartnerItemPriceUncheckedUpdateWithoutItemInput>
}

export type PartnerItemPriceUpdateManyWithWhereWithoutItemInput = {
  where: Prisma.PartnerItemPriceScalarWhereInput
  data: Prisma.XOR<Prisma.PartnerItemPriceUpdateManyMutationInput, Prisma.PartnerItemPriceUncheckedUpdateManyWithoutItemInput>
}

export type PartnerItemPriceScalarWhereInput = {
  AND?: Prisma.PartnerItemPriceScalarWhereInput | Prisma.PartnerItemPriceScalarWhereInput[]
  OR?: Prisma.PartnerItemPriceScalarWhereInput[]
  NOT?: Prisma.PartnerItemPriceScalarWhereInput | Prisma.PartnerItemPriceScalarWhereInput[]
  id?: Prisma.StringFilter<"PartnerItemPrice"> | string
  partnerId?: Prisma.StringFilter<"PartnerItemPrice"> | string
  itemId?: Prisma.StringFilter<"PartnerItemPrice"> | string
  price?: Prisma.DecimalFilter<"PartnerItemPrice"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Prisma.DateTimeFilter<"PartnerItemPrice"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"PartnerItemPrice"> | Date | string
}

export type PartnerItemPriceCreateWithoutPartnerInput = {
  id?: string
  price: runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Date | string
  updatedAt?: Date | string
  item: Prisma.ItemCreateNestedOneWithoutPartnerPricesInput
}

export type PartnerItemPriceUncheckedCreateWithoutPartnerInput = {
  id?: string
  itemId: string
  price: runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type PartnerItemPriceCreateOrConnectWithoutPartnerInput = {
  where: Prisma.PartnerItemPriceWhereUniqueInput
  create: Prisma.XOR<Prisma.PartnerItemPriceCreateWithoutPartnerInput, Prisma.PartnerItemPriceUncheckedCreateWithoutPartnerInput>
}

export type PartnerItemPriceCreateManyPartnerInputEnvelope = {
  data: Prisma.PartnerItemPriceCreateManyPartnerInput | Prisma.PartnerItemPriceCreateManyPartnerInput[]
  skipDuplicates?: boolean
}

export type PartnerItemPriceUpsertWithWhereUniqueWithoutPartnerInput = {
  where: Prisma.PartnerItemPriceWhereUniqueInput
  update: Prisma.XOR<Prisma.PartnerItemPriceUpdateWithoutPartnerInput, Prisma.PartnerItemPriceUncheckedUpdateWithoutPartnerInput>
  create: Prisma.XOR<Prisma.PartnerItemPriceCreateWithoutPartnerInput, Prisma.PartnerItemPriceUncheckedCreateWithoutPartnerInput>
}

export type PartnerItemPriceUpdateWithWhereUniqueWithoutPartnerInput = {
  where: Prisma.PartnerItemPriceWhereUniqueInput
  data: Prisma.XOR<Prisma.PartnerItemPriceUpdateWithoutPartnerInput, Prisma.PartnerItemPriceUncheckedUpdateWithoutPartnerInput>
}

export type PartnerItemPriceUpdateManyWithWhereWithoutPartnerInput = {
  where: Prisma.PartnerItemPriceScalarWhereInput
  data: Prisma.XOR<Prisma.PartnerItemPriceUpdateManyMutationInput, Prisma.PartnerItemPriceUncheckedUpdateManyWithoutPartnerInput>
}

export type PartnerItemPriceCreateManyItemInput = {
  id?: string
  partnerId: string
  price: runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type PartnerItemPriceUpdateWithoutItemInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  price?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  partner?: Prisma.PartnerUpdateOneRequiredWithoutItemPricesNestedInput
}

export type PartnerItemPriceUncheckedUpdateWithoutItemInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  partnerId?: Prisma.StringFieldUpdateOperationsInput | string
  price?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PartnerItemPriceUncheckedUpdateManyWithoutItemInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  partnerId?: Prisma.StringFieldUpdateOperationsInput | string
  price?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PartnerItemPriceCreateManyPartnerInput = {
  id?: string
  itemId: string
  price: runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type PartnerItemPriceUpdateWithoutPartnerInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  price?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  item?: Prisma.ItemUpdateOneRequiredWithoutPartnerPricesNestedInput
}

export type PartnerItemPriceUncheckedUpdateWithoutPartnerInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  itemId?: Prisma.StringFieldUpdateOperationsInput | string
  price?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PartnerItemPriceUncheckedUpdateManyWithoutPartnerInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  itemId?: Prisma.StringFieldUpdateOperationsInput | string
  price?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type PartnerItemPriceSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  partnerId?: boolean
  itemId?: boolean
  price?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  partner?: boolean | Prisma.PartnerDefaultArgs<ExtArgs>
  item?: boolean | Prisma.ItemDefaultArgs<ExtArgs>
}, ExtArgs["result"]["partnerItemPrice"]>

export type PartnerItemPriceSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  partnerId?: boolean
  itemId?: boolean
  price?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  partner?: boolean | Prisma.PartnerDefaultArgs<ExtArgs>
  item?: boolean | Prisma.ItemDefaultArgs<ExtArgs>
}, ExtArgs["result"]["partnerItemPrice"]>

export type PartnerItemPriceSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  partnerId?: boolean
  itemId?: boolean
  price?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  partner?: boolean | Prisma.PartnerDefaultArgs<ExtArgs>
  item?: boolean | Prisma.ItemDefaultArgs<ExtArgs>
}, ExtArgs["result"]["partnerItemPrice"]>

export type PartnerItemPriceSelectScalar = {
  id?: boolean
  partnerId?: boolean
  itemId?: boolean
  price?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type PartnerItemPriceOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "partnerId" | "itemId" | "price" | "createdAt" | "updatedAt", ExtArgs["result"]["partnerItemPrice"]>
export type PartnerItemPriceInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  partner?: boolean | Prisma.PartnerDefaultArgs<ExtArgs>
  item?: boolean | Prisma.ItemDefaultArgs<ExtArgs>
}
export type PartnerItemPriceIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  partner?: boolean | Prisma.PartnerDefaultArgs<ExtArgs>
  item?: boolean | Prisma.ItemDefaultArgs<ExtArgs>
}
export type PartnerItemPriceIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  partner?: boolean | Prisma.PartnerDefaultArgs<ExtArgs>
  item?: boolean | Prisma.ItemDefaultArgs<ExtArgs>
}

export type $PartnerItemPricePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "PartnerItemPrice"
  objects: {
    partner: Prisma.$PartnerPayload<ExtArgs>
    item: Prisma.$ItemPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    partnerId: string
    itemId: string
    price: runtime.Decimal
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["partnerItemPrice"]>
  composites: {}
}

export type PartnerItemPriceGetPayload<S extends boolean | null | undefined | PartnerItemPriceDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$PartnerItemPricePayload, S>

export type PartnerItemPriceCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<PartnerItemPriceFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: PartnerItemPriceCountAggregateInputType | true
  }

export interface PartnerItemPriceDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['PartnerItemPrice'], meta: { name: 'PartnerItemPrice' } }
  /**
   * Find zero or one PartnerItemPrice that matches the filter.
   * @param {PartnerItemPriceFindUniqueArgs} args - Arguments to find a PartnerItemPrice
   * @example
   * // Get one PartnerItemPrice
   * const partnerItemPrice = await prisma.partnerItemPrice.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends PartnerItemPriceFindUniqueArgs>(args: Prisma.SelectSubset<T, PartnerItemPriceFindUniqueArgs<ExtArgs>>): Prisma.Prisma__PartnerItemPriceClient<runtime.Types.Result.GetResult<Prisma.$PartnerItemPricePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one PartnerItemPrice that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {PartnerItemPriceFindUniqueOrThrowArgs} args - Arguments to find a PartnerItemPrice
   * @example
   * // Get one PartnerItemPrice
   * const partnerItemPrice = await prisma.partnerItemPrice.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends PartnerItemPriceFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, PartnerItemPriceFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__PartnerItemPriceClient<runtime.Types.Result.GetResult<Prisma.$PartnerItemPricePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first PartnerItemPrice that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PartnerItemPriceFindFirstArgs} args - Arguments to find a PartnerItemPrice
   * @example
   * // Get one PartnerItemPrice
   * const partnerItemPrice = await prisma.partnerItemPrice.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends PartnerItemPriceFindFirstArgs>(args?: Prisma.SelectSubset<T, PartnerItemPriceFindFirstArgs<ExtArgs>>): Prisma.Prisma__PartnerItemPriceClient<runtime.Types.Result.GetResult<Prisma.$PartnerItemPricePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first PartnerItemPrice that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PartnerItemPriceFindFirstOrThrowArgs} args - Arguments to find a PartnerItemPrice
   * @example
   * // Get one PartnerItemPrice
   * const partnerItemPrice = await prisma.partnerItemPrice.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends PartnerItemPriceFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, PartnerItemPriceFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__PartnerItemPriceClient<runtime.Types.Result.GetResult<Prisma.$PartnerItemPricePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more PartnerItemPrices that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PartnerItemPriceFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all PartnerItemPrices
   * const partnerItemPrices = await prisma.partnerItemPrice.findMany()
   * 
   * // Get first 10 PartnerItemPrices
   * const partnerItemPrices = await prisma.partnerItemPrice.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const partnerItemPriceWithIdOnly = await prisma.partnerItemPrice.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends PartnerItemPriceFindManyArgs>(args?: Prisma.SelectSubset<T, PartnerItemPriceFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PartnerItemPricePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a PartnerItemPrice.
   * @param {PartnerItemPriceCreateArgs} args - Arguments to create a PartnerItemPrice.
   * @example
   * // Create one PartnerItemPrice
   * const PartnerItemPrice = await prisma.partnerItemPrice.create({
   *   data: {
   *     // ... data to create a PartnerItemPrice
   *   }
   * })
   * 
   */
  create<T extends PartnerItemPriceCreateArgs>(args: Prisma.SelectSubset<T, PartnerItemPriceCreateArgs<ExtArgs>>): Prisma.Prisma__PartnerItemPriceClient<runtime.Types.Result.GetResult<Prisma.$PartnerItemPricePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many PartnerItemPrices.
   * @param {PartnerItemPriceCreateManyArgs} args - Arguments to create many PartnerItemPrices.
   * @example
   * // Create many PartnerItemPrices
   * const partnerItemPrice = await prisma.partnerItemPrice.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends PartnerItemPriceCreateManyArgs>(args?: Prisma.SelectSubset<T, PartnerItemPriceCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many PartnerItemPrices and returns the data saved in the database.
   * @param {PartnerItemPriceCreateManyAndReturnArgs} args - Arguments to create many PartnerItemPrices.
   * @example
   * // Create many PartnerItemPrices
   * const partnerItemPrice = await prisma.partnerItemPrice.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many PartnerItemPrices and only return the `id`
   * const partnerItemPriceWithIdOnly = await prisma.partnerItemPrice.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends PartnerItemPriceCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, PartnerItemPriceCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PartnerItemPricePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a PartnerItemPrice.
   * @param {PartnerItemPriceDeleteArgs} args - Arguments to delete one PartnerItemPrice.
   * @example
   * // Delete one PartnerItemPrice
   * const PartnerItemPrice = await prisma.partnerItemPrice.delete({
   *   where: {
   *     // ... filter to delete one PartnerItemPrice
   *   }
   * })
   * 
   */
  delete<T extends PartnerItemPriceDeleteArgs>(args: Prisma.SelectSubset<T, PartnerItemPriceDeleteArgs<ExtArgs>>): Prisma.Prisma__PartnerItemPriceClient<runtime.Types.Result.GetResult<Prisma.$PartnerItemPricePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one PartnerItemPrice.
   * @param {PartnerItemPriceUpdateArgs} args - Arguments to update one PartnerItemPrice.
   * @example
   * // Update one PartnerItemPrice
   * const partnerItemPrice = await prisma.partnerItemPrice.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends PartnerItemPriceUpdateArgs>(args: Prisma.SelectSubset<T, PartnerItemPriceUpdateArgs<ExtArgs>>): Prisma.Prisma__PartnerItemPriceClient<runtime.Types.Result.GetResult<Prisma.$PartnerItemPricePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more PartnerItemPrices.
   * @param {PartnerItemPriceDeleteManyArgs} args - Arguments to filter PartnerItemPrices to delete.
   * @example
   * // Delete a few PartnerItemPrices
   * const { count } = await prisma.partnerItemPrice.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends PartnerItemPriceDeleteManyArgs>(args?: Prisma.SelectSubset<T, PartnerItemPriceDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more PartnerItemPrices.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PartnerItemPriceUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many PartnerItemPrices
   * const partnerItemPrice = await prisma.partnerItemPrice.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends PartnerItemPriceUpdateManyArgs>(args: Prisma.SelectSubset<T, PartnerItemPriceUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more PartnerItemPrices and returns the data updated in the database.
   * @param {PartnerItemPriceUpdateManyAndReturnArgs} args - Arguments to update many PartnerItemPrices.
   * @example
   * // Update many PartnerItemPrices
   * const partnerItemPrice = await prisma.partnerItemPrice.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more PartnerItemPrices and only return the `id`
   * const partnerItemPriceWithIdOnly = await prisma.partnerItemPrice.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends PartnerItemPriceUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, PartnerItemPriceUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PartnerItemPricePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one PartnerItemPrice.
   * @param {PartnerItemPriceUpsertArgs} args - Arguments to update or create a PartnerItemPrice.
   * @example
   * // Update or create a PartnerItemPrice
   * const partnerItemPrice = await prisma.partnerItemPrice.upsert({
   *   create: {
   *     // ... data to create a PartnerItemPrice
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the PartnerItemPrice we want to update
   *   }
   * })
   */
  upsert<T extends PartnerItemPriceUpsertArgs>(args: Prisma.SelectSubset<T, PartnerItemPriceUpsertArgs<ExtArgs>>): Prisma.Prisma__PartnerItemPriceClient<runtime.Types.Result.GetResult<Prisma.$PartnerItemPricePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of PartnerItemPrices.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PartnerItemPriceCountArgs} args - Arguments to filter PartnerItemPrices to count.
   * @example
   * // Count the number of PartnerItemPrices
   * const count = await prisma.partnerItemPrice.count({
   *   where: {
   *     // ... the filter for the PartnerItemPrices we want to count
   *   }
   * })
  **/
  count<T extends PartnerItemPriceCountArgs>(
    args?: Prisma.Subset<T, PartnerItemPriceCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], PartnerItemPriceCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a PartnerItemPrice.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PartnerItemPriceAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends PartnerItemPriceAggregateArgs>(args: Prisma.Subset<T, PartnerItemPriceAggregateArgs>): Prisma.PrismaPromise<GetPartnerItemPriceAggregateType<T>>

  /**
   * Group by PartnerItemPrice.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PartnerItemPriceGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends PartnerItemPriceGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: PartnerItemPriceGroupByArgs['orderBy'] }
      : { orderBy?: PartnerItemPriceGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, PartnerItemPriceGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetPartnerItemPriceGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the PartnerItemPrice model
 */
readonly fields: PartnerItemPriceFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for PartnerItemPrice.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__PartnerItemPriceClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  partner<T extends Prisma.PartnerDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.PartnerDefaultArgs<ExtArgs>>): Prisma.Prisma__PartnerClient<runtime.Types.Result.GetResult<Prisma.$PartnerPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  item<T extends Prisma.ItemDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ItemDefaultArgs<ExtArgs>>): Prisma.Prisma__ItemClient<runtime.Types.Result.GetResult<Prisma.$ItemPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the PartnerItemPrice model
 */
export interface PartnerItemPriceFieldRefs {
  readonly id: Prisma.FieldRef<"PartnerItemPrice", 'String'>
  readonly partnerId: Prisma.FieldRef<"PartnerItemPrice", 'String'>
  readonly itemId: Prisma.FieldRef<"PartnerItemPrice", 'String'>
  readonly price: Prisma.FieldRef<"PartnerItemPrice", 'Decimal'>
  readonly createdAt: Prisma.FieldRef<"PartnerItemPrice", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"PartnerItemPrice", 'DateTime'>
}
    

// Custom InputTypes
/**
 * PartnerItemPrice findUnique
 */
export type PartnerItemPriceFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PartnerItemPrice
   */
  select?: Prisma.PartnerItemPriceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PartnerItemPrice
   */
  omit?: Prisma.PartnerItemPriceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PartnerItemPriceInclude<ExtArgs> | null
  /**
   * Filter, which PartnerItemPrice to fetch.
   */
  where: Prisma.PartnerItemPriceWhereUniqueInput
}

/**
 * PartnerItemPrice findUniqueOrThrow
 */
export type PartnerItemPriceFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PartnerItemPrice
   */
  select?: Prisma.PartnerItemPriceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PartnerItemPrice
   */
  omit?: Prisma.PartnerItemPriceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PartnerItemPriceInclude<ExtArgs> | null
  /**
   * Filter, which PartnerItemPrice to fetch.
   */
  where: Prisma.PartnerItemPriceWhereUniqueInput
}

/**
 * PartnerItemPrice findFirst
 */
export type PartnerItemPriceFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PartnerItemPrice
   */
  select?: Prisma.PartnerItemPriceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PartnerItemPrice
   */
  omit?: Prisma.PartnerItemPriceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PartnerItemPriceInclude<ExtArgs> | null
  /**
   * Filter, which PartnerItemPrice to fetch.
   */
  where?: Prisma.PartnerItemPriceWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PartnerItemPrices to fetch.
   */
  orderBy?: Prisma.PartnerItemPriceOrderByWithRelationInput | Prisma.PartnerItemPriceOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for PartnerItemPrices.
   */
  cursor?: Prisma.PartnerItemPriceWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PartnerItemPrices from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PartnerItemPrices.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PartnerItemPrices.
   */
  distinct?: Prisma.PartnerItemPriceScalarFieldEnum | Prisma.PartnerItemPriceScalarFieldEnum[]
}

/**
 * PartnerItemPrice findFirstOrThrow
 */
export type PartnerItemPriceFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PartnerItemPrice
   */
  select?: Prisma.PartnerItemPriceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PartnerItemPrice
   */
  omit?: Prisma.PartnerItemPriceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PartnerItemPriceInclude<ExtArgs> | null
  /**
   * Filter, which PartnerItemPrice to fetch.
   */
  where?: Prisma.PartnerItemPriceWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PartnerItemPrices to fetch.
   */
  orderBy?: Prisma.PartnerItemPriceOrderByWithRelationInput | Prisma.PartnerItemPriceOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for PartnerItemPrices.
   */
  cursor?: Prisma.PartnerItemPriceWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PartnerItemPrices from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PartnerItemPrices.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PartnerItemPrices.
   */
  distinct?: Prisma.PartnerItemPriceScalarFieldEnum | Prisma.PartnerItemPriceScalarFieldEnum[]
}

/**
 * PartnerItemPrice findMany
 */
export type PartnerItemPriceFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PartnerItemPrice
   */
  select?: Prisma.PartnerItemPriceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PartnerItemPrice
   */
  omit?: Prisma.PartnerItemPriceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PartnerItemPriceInclude<ExtArgs> | null
  /**
   * Filter, which PartnerItemPrices to fetch.
   */
  where?: Prisma.PartnerItemPriceWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PartnerItemPrices to fetch.
   */
  orderBy?: Prisma.PartnerItemPriceOrderByWithRelationInput | Prisma.PartnerItemPriceOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing PartnerItemPrices.
   */
  cursor?: Prisma.PartnerItemPriceWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PartnerItemPrices from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PartnerItemPrices.
   */
  skip?: number
  distinct?: Prisma.PartnerItemPriceScalarFieldEnum | Prisma.PartnerItemPriceScalarFieldEnum[]
}

/**
 * PartnerItemPrice create
 */
export type PartnerItemPriceCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PartnerItemPrice
   */
  select?: Prisma.PartnerItemPriceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PartnerItemPrice
   */
  omit?: Prisma.PartnerItemPriceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PartnerItemPriceInclude<ExtArgs> | null
  /**
   * The data needed to create a PartnerItemPrice.
   */
  data: Prisma.XOR<Prisma.PartnerItemPriceCreateInput, Prisma.PartnerItemPriceUncheckedCreateInput>
}

/**
 * PartnerItemPrice createMany
 */
export type PartnerItemPriceCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many PartnerItemPrices.
   */
  data: Prisma.PartnerItemPriceCreateManyInput | Prisma.PartnerItemPriceCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * PartnerItemPrice createManyAndReturn
 */
export type PartnerItemPriceCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PartnerItemPrice
   */
  select?: Prisma.PartnerItemPriceSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the PartnerItemPrice
   */
  omit?: Prisma.PartnerItemPriceOmit<ExtArgs> | null
  /**
   * The data used to create many PartnerItemPrices.
   */
  data: Prisma.PartnerItemPriceCreateManyInput | Prisma.PartnerItemPriceCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PartnerItemPriceIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * PartnerItemPrice update
 */
export type PartnerItemPriceUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PartnerItemPrice
   */
  select?: Prisma.PartnerItemPriceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PartnerItemPrice
   */
  omit?: Prisma.PartnerItemPriceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PartnerItemPriceInclude<ExtArgs> | null
  /**
   * The data needed to update a PartnerItemPrice.
   */
  data: Prisma.XOR<Prisma.PartnerItemPriceUpdateInput, Prisma.PartnerItemPriceUncheckedUpdateInput>
  /**
   * Choose, which PartnerItemPrice to update.
   */
  where: Prisma.PartnerItemPriceWhereUniqueInput
}

/**
 * PartnerItemPrice updateMany
 */
export type PartnerItemPriceUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update PartnerItemPrices.
   */
  data: Prisma.XOR<Prisma.PartnerItemPriceUpdateManyMutationInput, Prisma.PartnerItemPriceUncheckedUpdateManyInput>
  /**
   * Filter which PartnerItemPrices to update
   */
  where?: Prisma.PartnerItemPriceWhereInput
  /**
   * Limit how many PartnerItemPrices to update.
   */
  limit?: number
}

/**
 * PartnerItemPrice updateManyAndReturn
 */
export type PartnerItemPriceUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PartnerItemPrice
   */
  select?: Prisma.PartnerItemPriceSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the PartnerItemPrice
   */
  omit?: Prisma.PartnerItemPriceOmit<ExtArgs> | null
  /**
   * The data used to update PartnerItemPrices.
   */
  data: Prisma.XOR<Prisma.PartnerItemPriceUpdateManyMutationInput, Prisma.PartnerItemPriceUncheckedUpdateManyInput>
  /**
   * Filter which PartnerItemPrices to update
   */
  where?: Prisma.PartnerItemPriceWhereInput
  /**
   * Limit how many PartnerItemPrices to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PartnerItemPriceIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * PartnerItemPrice upsert
 */
export type PartnerItemPriceUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PartnerItemPrice
   */
  select?: Prisma.PartnerItemPriceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PartnerItemPrice
   */
  omit?: Prisma.PartnerItemPriceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PartnerItemPriceInclude<ExtArgs> | null
  /**
   * The filter to search for the PartnerItemPrice to update in case it exists.
   */
  where: Prisma.PartnerItemPriceWhereUniqueInput
  /**
   * In case the PartnerItemPrice found by the `where` argument doesn't exist, create a new PartnerItemPrice with this data.
   */
  create: Prisma.XOR<Prisma.PartnerItemPriceCreateInput, Prisma.PartnerItemPriceUncheckedCreateInput>
  /**
   * In case the PartnerItemPrice was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.PartnerItemPriceUpdateInput, Prisma.PartnerItemPriceUncheckedUpdateInput>
}

/**
 * PartnerItemPrice delete
 */
export type PartnerItemPriceDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PartnerItemPrice
   */
  select?: Prisma.PartnerItemPriceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PartnerItemPrice
   */
  omit?: Prisma.PartnerItemPriceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PartnerItemPriceInclude<ExtArgs> | null
  /**
   * Filter which PartnerItemPrice to delete.
   */
  where: Prisma.PartnerItemPriceWhereUniqueInput
}

/**
 * PartnerItemPrice deleteMany
 */
export type PartnerItemPriceDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which PartnerItemPrices to delete
   */
  where?: Prisma.PartnerItemPriceWhereInput
  /**
   * Limit how many PartnerItemPrices to delete.
   */
  limit?: number
}

/**
 * PartnerItemPrice without action
 */
export type PartnerItemPriceDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PartnerItemPrice
   */
  select?: Prisma.PartnerItemPriceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PartnerItemPrice
   */
  omit?: Prisma.PartnerItemPriceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PartnerItemPriceInclude<ExtArgs> | null
}
