
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `RABLine` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model RABLine
 * 
 */
export type RABLineModel = runtime.Types.Result.DefaultSelection<Prisma.$RABLinePayload>

export type AggregateRABLine = {
  _count: RABLineCountAggregateOutputType | null
  _avg: RABLineAvgAggregateOutputType | null
  _sum: RABLineSumAggregateOutputType | null
  _min: RABLineMinAggregateOutputType | null
  _max: RABLineMaxAggregateOutputType | null
}

export type RABLineAvgAggregateOutputType = {
  requiredQty: number | null
  lastStockSnapshot: number | null
  replenishQty: number | null
  unitPrice: runtime.Decimal | null
  totalAmount: runtime.Decimal | null
  usedAmount: runtime.Decimal | null
}

export type RABLineSumAggregateOutputType = {
  requiredQty: number | null
  lastStockSnapshot: number | null
  replenishQty: number | null
  unitPrice: runtime.Decimal | null
  totalAmount: runtime.Decimal | null
  usedAmount: runtime.Decimal | null
}

export type RABLineMinAggregateOutputType = {
  id: string | null
  rabId: string | null
  itemId: string | null
  requiredQty: number | null
  lastStockSnapshot: number | null
  replenishQty: number | null
  unitPrice: runtime.Decimal | null
  totalAmount: runtime.Decimal | null
  usedAmount: runtime.Decimal | null
  notes: string | null
}

export type RABLineMaxAggregateOutputType = {
  id: string | null
  rabId: string | null
  itemId: string | null
  requiredQty: number | null
  lastStockSnapshot: number | null
  replenishQty: number | null
  unitPrice: runtime.Decimal | null
  totalAmount: runtime.Decimal | null
  usedAmount: runtime.Decimal | null
  notes: string | null
}

export type RABLineCountAggregateOutputType = {
  id: number
  rabId: number
  itemId: number
  requiredQty: number
  lastStockSnapshot: number
  replenishQty: number
  unitPrice: number
  totalAmount: number
  usedAmount: number
  notes: number
  _all: number
}


export type RABLineAvgAggregateInputType = {
  requiredQty?: true
  lastStockSnapshot?: true
  replenishQty?: true
  unitPrice?: true
  totalAmount?: true
  usedAmount?: true
}

export type RABLineSumAggregateInputType = {
  requiredQty?: true
  lastStockSnapshot?: true
  replenishQty?: true
  unitPrice?: true
  totalAmount?: true
  usedAmount?: true
}

export type RABLineMinAggregateInputType = {
  id?: true
  rabId?: true
  itemId?: true
  requiredQty?: true
  lastStockSnapshot?: true
  replenishQty?: true
  unitPrice?: true
  totalAmount?: true
  usedAmount?: true
  notes?: true
}

export type RABLineMaxAggregateInputType = {
  id?: true
  rabId?: true
  itemId?: true
  requiredQty?: true
  lastStockSnapshot?: true
  replenishQty?: true
  unitPrice?: true
  totalAmount?: true
  usedAmount?: true
  notes?: true
}

export type RABLineCountAggregateInputType = {
  id?: true
  rabId?: true
  itemId?: true
  requiredQty?: true
  lastStockSnapshot?: true
  replenishQty?: true
  unitPrice?: true
  totalAmount?: true
  usedAmount?: true
  notes?: true
  _all?: true
}

export type RABLineAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which RABLine to aggregate.
   */
  where?: Prisma.RABLineWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of RABLines to fetch.
   */
  orderBy?: Prisma.RABLineOrderByWithRelationInput | Prisma.RABLineOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.RABLineWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` RABLines from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` RABLines.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned RABLines
  **/
  _count?: true | RABLineCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: RABLineAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: RABLineSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: RABLineMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: RABLineMaxAggregateInputType
}

export type GetRABLineAggregateType<T extends RABLineAggregateArgs> = {
      [P in keyof T & keyof AggregateRABLine]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateRABLine[P]>
    : Prisma.GetScalarType<T[P], AggregateRABLine[P]>
}




export type RABLineGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.RABLineWhereInput
  orderBy?: Prisma.RABLineOrderByWithAggregationInput | Prisma.RABLineOrderByWithAggregationInput[]
  by: Prisma.RABLineScalarFieldEnum[] | Prisma.RABLineScalarFieldEnum
  having?: Prisma.RABLineScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: RABLineCountAggregateInputType | true
  _avg?: RABLineAvgAggregateInputType
  _sum?: RABLineSumAggregateInputType
  _min?: RABLineMinAggregateInputType
  _max?: RABLineMaxAggregateInputType
}

export type RABLineGroupByOutputType = {
  id: string
  rabId: string
  itemId: string
  requiredQty: number
  lastStockSnapshot: number
  replenishQty: number
  unitPrice: runtime.Decimal
  totalAmount: runtime.Decimal
  usedAmount: runtime.Decimal
  notes: string | null
  _count: RABLineCountAggregateOutputType | null
  _avg: RABLineAvgAggregateOutputType | null
  _sum: RABLineSumAggregateOutputType | null
  _min: RABLineMinAggregateOutputType | null
  _max: RABLineMaxAggregateOutputType | null
}

type GetRABLineGroupByPayload<T extends RABLineGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<RABLineGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof RABLineGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], RABLineGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], RABLineGroupByOutputType[P]>
      }
    >
  >



export type RABLineWhereInput = {
  AND?: Prisma.RABLineWhereInput | Prisma.RABLineWhereInput[]
  OR?: Prisma.RABLineWhereInput[]
  NOT?: Prisma.RABLineWhereInput | Prisma.RABLineWhereInput[]
  id?: Prisma.StringFilter<"RABLine"> | string
  rabId?: Prisma.StringFilter<"RABLine"> | string
  itemId?: Prisma.StringFilter<"RABLine"> | string
  requiredQty?: Prisma.IntFilter<"RABLine"> | number
  lastStockSnapshot?: Prisma.IntFilter<"RABLine"> | number
  replenishQty?: Prisma.IntFilter<"RABLine"> | number
  unitPrice?: Prisma.DecimalFilter<"RABLine"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  totalAmount?: Prisma.DecimalFilter<"RABLine"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  usedAmount?: Prisma.DecimalFilter<"RABLine"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  notes?: Prisma.StringNullableFilter<"RABLine"> | string | null
  rab?: Prisma.XOR<Prisma.RABScalarRelationFilter, Prisma.RABWhereInput>
  item?: Prisma.XOR<Prisma.ItemScalarRelationFilter, Prisma.ItemWhereInput>
}

export type RABLineOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  rabId?: Prisma.SortOrder
  itemId?: Prisma.SortOrder
  requiredQty?: Prisma.SortOrder
  lastStockSnapshot?: Prisma.SortOrder
  replenishQty?: Prisma.SortOrder
  unitPrice?: Prisma.SortOrder
  totalAmount?: Prisma.SortOrder
  usedAmount?: Prisma.SortOrder
  notes?: Prisma.SortOrderInput | Prisma.SortOrder
  rab?: Prisma.RABOrderByWithRelationInput
  item?: Prisma.ItemOrderByWithRelationInput
}

export type RABLineWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.RABLineWhereInput | Prisma.RABLineWhereInput[]
  OR?: Prisma.RABLineWhereInput[]
  NOT?: Prisma.RABLineWhereInput | Prisma.RABLineWhereInput[]
  rabId?: Prisma.StringFilter<"RABLine"> | string
  itemId?: Prisma.StringFilter<"RABLine"> | string
  requiredQty?: Prisma.IntFilter<"RABLine"> | number
  lastStockSnapshot?: Prisma.IntFilter<"RABLine"> | number
  replenishQty?: Prisma.IntFilter<"RABLine"> | number
  unitPrice?: Prisma.DecimalFilter<"RABLine"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  totalAmount?: Prisma.DecimalFilter<"RABLine"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  usedAmount?: Prisma.DecimalFilter<"RABLine"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  notes?: Prisma.StringNullableFilter<"RABLine"> | string | null
  rab?: Prisma.XOR<Prisma.RABScalarRelationFilter, Prisma.RABWhereInput>
  item?: Prisma.XOR<Prisma.ItemScalarRelationFilter, Prisma.ItemWhereInput>
}, "id">

export type RABLineOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  rabId?: Prisma.SortOrder
  itemId?: Prisma.SortOrder
  requiredQty?: Prisma.SortOrder
  lastStockSnapshot?: Prisma.SortOrder
  replenishQty?: Prisma.SortOrder
  unitPrice?: Prisma.SortOrder
  totalAmount?: Prisma.SortOrder
  usedAmount?: Prisma.SortOrder
  notes?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.RABLineCountOrderByAggregateInput
  _avg?: Prisma.RABLineAvgOrderByAggregateInput
  _max?: Prisma.RABLineMaxOrderByAggregateInput
  _min?: Prisma.RABLineMinOrderByAggregateInput
  _sum?: Prisma.RABLineSumOrderByAggregateInput
}

export type RABLineScalarWhereWithAggregatesInput = {
  AND?: Prisma.RABLineScalarWhereWithAggregatesInput | Prisma.RABLineScalarWhereWithAggregatesInput[]
  OR?: Prisma.RABLineScalarWhereWithAggregatesInput[]
  NOT?: Prisma.RABLineScalarWhereWithAggregatesInput | Prisma.RABLineScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"RABLine"> | string
  rabId?: Prisma.StringWithAggregatesFilter<"RABLine"> | string
  itemId?: Prisma.StringWithAggregatesFilter<"RABLine"> | string
  requiredQty?: Prisma.IntWithAggregatesFilter<"RABLine"> | number
  lastStockSnapshot?: Prisma.IntWithAggregatesFilter<"RABLine"> | number
  replenishQty?: Prisma.IntWithAggregatesFilter<"RABLine"> | number
  unitPrice?: Prisma.DecimalWithAggregatesFilter<"RABLine"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  totalAmount?: Prisma.DecimalWithAggregatesFilter<"RABLine"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  usedAmount?: Prisma.DecimalWithAggregatesFilter<"RABLine"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  notes?: Prisma.StringNullableWithAggregatesFilter<"RABLine"> | string | null
}

export type RABLineCreateInput = {
  id?: string
  requiredQty: number
  lastStockSnapshot: number
  replenishQty: number
  unitPrice: runtime.Decimal | runtime.DecimalJsLike | number | string
  totalAmount: runtime.Decimal | runtime.DecimalJsLike | number | string
  usedAmount?: runtime.Decimal | runtime.DecimalJsLike | number | string
  notes?: string | null
  rab: Prisma.RABCreateNestedOneWithoutRabLinesInput
  item: Prisma.ItemCreateNestedOneWithoutRabLinesInput
}

export type RABLineUncheckedCreateInput = {
  id?: string
  rabId: string
  itemId: string
  requiredQty: number
  lastStockSnapshot: number
  replenishQty: number
  unitPrice: runtime.Decimal | runtime.DecimalJsLike | number | string
  totalAmount: runtime.Decimal | runtime.DecimalJsLike | number | string
  usedAmount?: runtime.Decimal | runtime.DecimalJsLike | number | string
  notes?: string | null
}

export type RABLineUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  requiredQty?: Prisma.IntFieldUpdateOperationsInput | number
  lastStockSnapshot?: Prisma.IntFieldUpdateOperationsInput | number
  replenishQty?: Prisma.IntFieldUpdateOperationsInput | number
  unitPrice?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  totalAmount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  usedAmount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  rab?: Prisma.RABUpdateOneRequiredWithoutRabLinesNestedInput
  item?: Prisma.ItemUpdateOneRequiredWithoutRabLinesNestedInput
}

export type RABLineUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  rabId?: Prisma.StringFieldUpdateOperationsInput | string
  itemId?: Prisma.StringFieldUpdateOperationsInput | string
  requiredQty?: Prisma.IntFieldUpdateOperationsInput | number
  lastStockSnapshot?: Prisma.IntFieldUpdateOperationsInput | number
  replenishQty?: Prisma.IntFieldUpdateOperationsInput | number
  unitPrice?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  totalAmount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  usedAmount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type RABLineCreateManyInput = {
  id?: string
  rabId: string
  itemId: string
  requiredQty: number
  lastStockSnapshot: number
  replenishQty: number
  unitPrice: runtime.Decimal | runtime.DecimalJsLike | number | string
  totalAmount: runtime.Decimal | runtime.DecimalJsLike | number | string
  usedAmount?: runtime.Decimal | runtime.DecimalJsLike | number | string
  notes?: string | null
}

export type RABLineUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  requiredQty?: Prisma.IntFieldUpdateOperationsInput | number
  lastStockSnapshot?: Prisma.IntFieldUpdateOperationsInput | number
  replenishQty?: Prisma.IntFieldUpdateOperationsInput | number
  unitPrice?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  totalAmount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  usedAmount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type RABLineUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  rabId?: Prisma.StringFieldUpdateOperationsInput | string
  itemId?: Prisma.StringFieldUpdateOperationsInput | string
  requiredQty?: Prisma.IntFieldUpdateOperationsInput | number
  lastStockSnapshot?: Prisma.IntFieldUpdateOperationsInput | number
  replenishQty?: Prisma.IntFieldUpdateOperationsInput | number
  unitPrice?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  totalAmount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  usedAmount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type RABLineListRelationFilter = {
  every?: Prisma.RABLineWhereInput
  some?: Prisma.RABLineWhereInput
  none?: Prisma.RABLineWhereInput
}

export type RABLineOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type RABLineCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  rabId?: Prisma.SortOrder
  itemId?: Prisma.SortOrder
  requiredQty?: Prisma.SortOrder
  lastStockSnapshot?: Prisma.SortOrder
  replenishQty?: Prisma.SortOrder
  unitPrice?: Prisma.SortOrder
  totalAmount?: Prisma.SortOrder
  usedAmount?: Prisma.SortOrder
  notes?: Prisma.SortOrder
}

export type RABLineAvgOrderByAggregateInput = {
  requiredQty?: Prisma.SortOrder
  lastStockSnapshot?: Prisma.SortOrder
  replenishQty?: Prisma.SortOrder
  unitPrice?: Prisma.SortOrder
  totalAmount?: Prisma.SortOrder
  usedAmount?: Prisma.SortOrder
}

export type RABLineMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  rabId?: Prisma.SortOrder
  itemId?: Prisma.SortOrder
  requiredQty?: Prisma.SortOrder
  lastStockSnapshot?: Prisma.SortOrder
  replenishQty?: Prisma.SortOrder
  unitPrice?: Prisma.SortOrder
  totalAmount?: Prisma.SortOrder
  usedAmount?: Prisma.SortOrder
  notes?: Prisma.SortOrder
}

export type RABLineMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  rabId?: Prisma.SortOrder
  itemId?: Prisma.SortOrder
  requiredQty?: Prisma.SortOrder
  lastStockSnapshot?: Prisma.SortOrder
  replenishQty?: Prisma.SortOrder
  unitPrice?: Prisma.SortOrder
  totalAmount?: Prisma.SortOrder
  usedAmount?: Prisma.SortOrder
  notes?: Prisma.SortOrder
}

export type RABLineSumOrderByAggregateInput = {
  requiredQty?: Prisma.SortOrder
  lastStockSnapshot?: Prisma.SortOrder
  replenishQty?: Prisma.SortOrder
  unitPrice?: Prisma.SortOrder
  totalAmount?: Prisma.SortOrder
  usedAmount?: Prisma.SortOrder
}

export type RABLineCreateNestedManyWithoutItemInput = {
  create?: Prisma.XOR<Prisma.RABLineCreateWithoutItemInput, Prisma.RABLineUncheckedCreateWithoutItemInput> | Prisma.RABLineCreateWithoutItemInput[] | Prisma.RABLineUncheckedCreateWithoutItemInput[]
  connectOrCreate?: Prisma.RABLineCreateOrConnectWithoutItemInput | Prisma.RABLineCreateOrConnectWithoutItemInput[]
  createMany?: Prisma.RABLineCreateManyItemInputEnvelope
  connect?: Prisma.RABLineWhereUniqueInput | Prisma.RABLineWhereUniqueInput[]
}

export type RABLineUncheckedCreateNestedManyWithoutItemInput = {
  create?: Prisma.XOR<Prisma.RABLineCreateWithoutItemInput, Prisma.RABLineUncheckedCreateWithoutItemInput> | Prisma.RABLineCreateWithoutItemInput[] | Prisma.RABLineUncheckedCreateWithoutItemInput[]
  connectOrCreate?: Prisma.RABLineCreateOrConnectWithoutItemInput | Prisma.RABLineCreateOrConnectWithoutItemInput[]
  createMany?: Prisma.RABLineCreateManyItemInputEnvelope
  connect?: Prisma.RABLineWhereUniqueInput | Prisma.RABLineWhereUniqueInput[]
}

export type RABLineUpdateManyWithoutItemNestedInput = {
  create?: Prisma.XOR<Prisma.RABLineCreateWithoutItemInput, Prisma.RABLineUncheckedCreateWithoutItemInput> | Prisma.RABLineCreateWithoutItemInput[] | Prisma.RABLineUncheckedCreateWithoutItemInput[]
  connectOrCreate?: Prisma.RABLineCreateOrConnectWithoutItemInput | Prisma.RABLineCreateOrConnectWithoutItemInput[]
  upsert?: Prisma.RABLineUpsertWithWhereUniqueWithoutItemInput | Prisma.RABLineUpsertWithWhereUniqueWithoutItemInput[]
  createMany?: Prisma.RABLineCreateManyItemInputEnvelope
  set?: Prisma.RABLineWhereUniqueInput | Prisma.RABLineWhereUniqueInput[]
  disconnect?: Prisma.RABLineWhereUniqueInput | Prisma.RABLineWhereUniqueInput[]
  delete?: Prisma.RABLineWhereUniqueInput | Prisma.RABLineWhereUniqueInput[]
  connect?: Prisma.RABLineWhereUniqueInput | Prisma.RABLineWhereUniqueInput[]
  update?: Prisma.RABLineUpdateWithWhereUniqueWithoutItemInput | Prisma.RABLineUpdateWithWhereUniqueWithoutItemInput[]
  updateMany?: Prisma.RABLineUpdateManyWithWhereWithoutItemInput | Prisma.RABLineUpdateManyWithWhereWithoutItemInput[]
  deleteMany?: Prisma.RABLineScalarWhereInput | Prisma.RABLineScalarWhereInput[]
}

export type RABLineUncheckedUpdateManyWithoutItemNestedInput = {
  create?: Prisma.XOR<Prisma.RABLineCreateWithoutItemInput, Prisma.RABLineUncheckedCreateWithoutItemInput> | Prisma.RABLineCreateWithoutItemInput[] | Prisma.RABLineUncheckedCreateWithoutItemInput[]
  connectOrCreate?: Prisma.RABLineCreateOrConnectWithoutItemInput | Prisma.RABLineCreateOrConnectWithoutItemInput[]
  upsert?: Prisma.RABLineUpsertWithWhereUniqueWithoutItemInput | Prisma.RABLineUpsertWithWhereUniqueWithoutItemInput[]
  createMany?: Prisma.RABLineCreateManyItemInputEnvelope
  set?: Prisma.RABLineWhereUniqueInput | Prisma.RABLineWhereUniqueInput[]
  disconnect?: Prisma.RABLineWhereUniqueInput | Prisma.RABLineWhereUniqueInput[]
  delete?: Prisma.RABLineWhereUniqueInput | Prisma.RABLineWhereUniqueInput[]
  connect?: Prisma.RABLineWhereUniqueInput | Prisma.RABLineWhereUniqueInput[]
  update?: Prisma.RABLineUpdateWithWhereUniqueWithoutItemInput | Prisma.RABLineUpdateWithWhereUniqueWithoutItemInput[]
  updateMany?: Prisma.RABLineUpdateManyWithWhereWithoutItemInput | Prisma.RABLineUpdateManyWithWhereWithoutItemInput[]
  deleteMany?: Prisma.RABLineScalarWhereInput | Prisma.RABLineScalarWhereInput[]
}

export type RABLineCreateNestedManyWithoutRabInput = {
  create?: Prisma.XOR<Prisma.RABLineCreateWithoutRabInput, Prisma.RABLineUncheckedCreateWithoutRabInput> | Prisma.RABLineCreateWithoutRabInput[] | Prisma.RABLineUncheckedCreateWithoutRabInput[]
  connectOrCreate?: Prisma.RABLineCreateOrConnectWithoutRabInput | Prisma.RABLineCreateOrConnectWithoutRabInput[]
  createMany?: Prisma.RABLineCreateManyRabInputEnvelope
  connect?: Prisma.RABLineWhereUniqueInput | Prisma.RABLineWhereUniqueInput[]
}

export type RABLineUncheckedCreateNestedManyWithoutRabInput = {
  create?: Prisma.XOR<Prisma.RABLineCreateWithoutRabInput, Prisma.RABLineUncheckedCreateWithoutRabInput> | Prisma.RABLineCreateWithoutRabInput[] | Prisma.RABLineUncheckedCreateWithoutRabInput[]
  connectOrCreate?: Prisma.RABLineCreateOrConnectWithoutRabInput | Prisma.RABLineCreateOrConnectWithoutRabInput[]
  createMany?: Prisma.RABLineCreateManyRabInputEnvelope
  connect?: Prisma.RABLineWhereUniqueInput | Prisma.RABLineWhereUniqueInput[]
}

export type RABLineUpdateManyWithoutRabNestedInput = {
  create?: Prisma.XOR<Prisma.RABLineCreateWithoutRabInput, Prisma.RABLineUncheckedCreateWithoutRabInput> | Prisma.RABLineCreateWithoutRabInput[] | Prisma.RABLineUncheckedCreateWithoutRabInput[]
  connectOrCreate?: Prisma.RABLineCreateOrConnectWithoutRabInput | Prisma.RABLineCreateOrConnectWithoutRabInput[]
  upsert?: Prisma.RABLineUpsertWithWhereUniqueWithoutRabInput | Prisma.RABLineUpsertWithWhereUniqueWithoutRabInput[]
  createMany?: Prisma.RABLineCreateManyRabInputEnvelope
  set?: Prisma.RABLineWhereUniqueInput | Prisma.RABLineWhereUniqueInput[]
  disconnect?: Prisma.RABLineWhereUniqueInput | Prisma.RABLineWhereUniqueInput[]
  delete?: Prisma.RABLineWhereUniqueInput | Prisma.RABLineWhereUniqueInput[]
  connect?: Prisma.RABLineWhereUniqueInput | Prisma.RABLineWhereUniqueInput[]
  update?: Prisma.RABLineUpdateWithWhereUniqueWithoutRabInput | Prisma.RABLineUpdateWithWhereUniqueWithoutRabInput[]
  updateMany?: Prisma.RABLineUpdateManyWithWhereWithoutRabInput | Prisma.RABLineUpdateManyWithWhereWithoutRabInput[]
  deleteMany?: Prisma.RABLineScalarWhereInput | Prisma.RABLineScalarWhereInput[]
}

export type RABLineUncheckedUpdateManyWithoutRabNestedInput = {
  create?: Prisma.XOR<Prisma.RABLineCreateWithoutRabInput, Prisma.RABLineUncheckedCreateWithoutRabInput> | Prisma.RABLineCreateWithoutRabInput[] | Prisma.RABLineUncheckedCreateWithoutRabInput[]
  connectOrCreate?: Prisma.RABLineCreateOrConnectWithoutRabInput | Prisma.RABLineCreateOrConnectWithoutRabInput[]
  upsert?: Prisma.RABLineUpsertWithWhereUniqueWithoutRabInput | Prisma.RABLineUpsertWithWhereUniqueWithoutRabInput[]
  createMany?: Prisma.RABLineCreateManyRabInputEnvelope
  set?: Prisma.RABLineWhereUniqueInput | Prisma.RABLineWhereUniqueInput[]
  disconnect?: Prisma.RABLineWhereUniqueInput | Prisma.RABLineWhereUniqueInput[]
  delete?: Prisma.RABLineWhereUniqueInput | Prisma.RABLineWhereUniqueInput[]
  connect?: Prisma.RABLineWhereUniqueInput | Prisma.RABLineWhereUniqueInput[]
  update?: Prisma.RABLineUpdateWithWhereUniqueWithoutRabInput | Prisma.RABLineUpdateWithWhereUniqueWithoutRabInput[]
  updateMany?: Prisma.RABLineUpdateManyWithWhereWithoutRabInput | Prisma.RABLineUpdateManyWithWhereWithoutRabInput[]
  deleteMany?: Prisma.RABLineScalarWhereInput | Prisma.RABLineScalarWhereInput[]
}

export type RABLineCreateWithoutItemInput = {
  id?: string
  requiredQty: number
  lastStockSnapshot: number
  replenishQty: number
  unitPrice: runtime.Decimal | runtime.DecimalJsLike | number | string
  totalAmount: runtime.Decimal | runtime.DecimalJsLike | number | string
  usedAmount?: runtime.Decimal | runtime.DecimalJsLike | number | string
  notes?: string | null
  rab: Prisma.RABCreateNestedOneWithoutRabLinesInput
}

export type RABLineUncheckedCreateWithoutItemInput = {
  id?: string
  rabId: string
  requiredQty: number
  lastStockSnapshot: number
  replenishQty: number
  unitPrice: runtime.Decimal | runtime.DecimalJsLike | number | string
  totalAmount: runtime.Decimal | runtime.DecimalJsLike | number | string
  usedAmount?: runtime.Decimal | runtime.DecimalJsLike | number | string
  notes?: string | null
}

export type RABLineCreateOrConnectWithoutItemInput = {
  where: Prisma.RABLineWhereUniqueInput
  create: Prisma.XOR<Prisma.RABLineCreateWithoutItemInput, Prisma.RABLineUncheckedCreateWithoutItemInput>
}

export type RABLineCreateManyItemInputEnvelope = {
  data: Prisma.RABLineCreateManyItemInput | Prisma.RABLineCreateManyItemInput[]
  skipDuplicates?: boolean
}

export type RABLineUpsertWithWhereUniqueWithoutItemInput = {
  where: Prisma.RABLineWhereUniqueInput
  update: Prisma.XOR<Prisma.RABLineUpdateWithoutItemInput, Prisma.RABLineUncheckedUpdateWithoutItemInput>
  create: Prisma.XOR<Prisma.RABLineCreateWithoutItemInput, Prisma.RABLineUncheckedCreateWithoutItemInput>
}

export type RABLineUpdateWithWhereUniqueWithoutItemInput = {
  where: Prisma.RABLineWhereUniqueInput
  data: Prisma.XOR<Prisma.RABLineUpdateWithoutItemInput, Prisma.RABLineUncheckedUpdateWithoutItemInput>
}

export type RABLineUpdateManyWithWhereWithoutItemInput = {
  where: Prisma.RABLineScalarWhereInput
  data: Prisma.XOR<Prisma.RABLineUpdateManyMutationInput, Prisma.RABLineUncheckedUpdateManyWithoutItemInput>
}

export type RABLineScalarWhereInput = {
  AND?: Prisma.RABLineScalarWhereInput | Prisma.RABLineScalarWhereInput[]
  OR?: Prisma.RABLineScalarWhereInput[]
  NOT?: Prisma.RABLineScalarWhereInput | Prisma.RABLineScalarWhereInput[]
  id?: Prisma.StringFilter<"RABLine"> | string
  rabId?: Prisma.StringFilter<"RABLine"> | string
  itemId?: Prisma.StringFilter<"RABLine"> | string
  requiredQty?: Prisma.IntFilter<"RABLine"> | number
  lastStockSnapshot?: Prisma.IntFilter<"RABLine"> | number
  replenishQty?: Prisma.IntFilter<"RABLine"> | number
  unitPrice?: Prisma.DecimalFilter<"RABLine"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  totalAmount?: Prisma.DecimalFilter<"RABLine"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  usedAmount?: Prisma.DecimalFilter<"RABLine"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  notes?: Prisma.StringNullableFilter<"RABLine"> | string | null
}

export type RABLineCreateWithoutRabInput = {
  id?: string
  requiredQty: number
  lastStockSnapshot: number
  replenishQty: number
  unitPrice: runtime.Decimal | runtime.DecimalJsLike | number | string
  totalAmount: runtime.Decimal | runtime.DecimalJsLike | number | string
  usedAmount?: runtime.Decimal | runtime.DecimalJsLike | number | string
  notes?: string | null
  item: Prisma.ItemCreateNestedOneWithoutRabLinesInput
}

export type RABLineUncheckedCreateWithoutRabInput = {
  id?: string
  itemId: string
  requiredQty: number
  lastStockSnapshot: number
  replenishQty: number
  unitPrice: runtime.Decimal | runtime.DecimalJsLike | number | string
  totalAmount: runtime.Decimal | runtime.DecimalJsLike | number | string
  usedAmount?: runtime.Decimal | runtime.DecimalJsLike | number | string
  notes?: string | null
}

export type RABLineCreateOrConnectWithoutRabInput = {
  where: Prisma.RABLineWhereUniqueInput
  create: Prisma.XOR<Prisma.RABLineCreateWithoutRabInput, Prisma.RABLineUncheckedCreateWithoutRabInput>
}

export type RABLineCreateManyRabInputEnvelope = {
  data: Prisma.RABLineCreateManyRabInput | Prisma.RABLineCreateManyRabInput[]
  skipDuplicates?: boolean
}

export type RABLineUpsertWithWhereUniqueWithoutRabInput = {
  where: Prisma.RABLineWhereUniqueInput
  update: Prisma.XOR<Prisma.RABLineUpdateWithoutRabInput, Prisma.RABLineUncheckedUpdateWithoutRabInput>
  create: Prisma.XOR<Prisma.RABLineCreateWithoutRabInput, Prisma.RABLineUncheckedCreateWithoutRabInput>
}

export type RABLineUpdateWithWhereUniqueWithoutRabInput = {
  where: Prisma.RABLineWhereUniqueInput
  data: Prisma.XOR<Prisma.RABLineUpdateWithoutRabInput, Prisma.RABLineUncheckedUpdateWithoutRabInput>
}

export type RABLineUpdateManyWithWhereWithoutRabInput = {
  where: Prisma.RABLineScalarWhereInput
  data: Prisma.XOR<Prisma.RABLineUpdateManyMutationInput, Prisma.RABLineUncheckedUpdateManyWithoutRabInput>
}

export type RABLineCreateManyItemInput = {
  id?: string
  rabId: string
  requiredQty: number
  lastStockSnapshot: number
  replenishQty: number
  unitPrice: runtime.Decimal | runtime.DecimalJsLike | number | string
  totalAmount: runtime.Decimal | runtime.DecimalJsLike | number | string
  usedAmount?: runtime.Decimal | runtime.DecimalJsLike | number | string
  notes?: string | null
}

export type RABLineUpdateWithoutItemInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  requiredQty?: Prisma.IntFieldUpdateOperationsInput | number
  lastStockSnapshot?: Prisma.IntFieldUpdateOperationsInput | number
  replenishQty?: Prisma.IntFieldUpdateOperationsInput | number
  unitPrice?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  totalAmount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  usedAmount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  rab?: Prisma.RABUpdateOneRequiredWithoutRabLinesNestedInput
}

export type RABLineUncheckedUpdateWithoutItemInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  rabId?: Prisma.StringFieldUpdateOperationsInput | string
  requiredQty?: Prisma.IntFieldUpdateOperationsInput | number
  lastStockSnapshot?: Prisma.IntFieldUpdateOperationsInput | number
  replenishQty?: Prisma.IntFieldUpdateOperationsInput | number
  unitPrice?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  totalAmount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  usedAmount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type RABLineUncheckedUpdateManyWithoutItemInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  rabId?: Prisma.StringFieldUpdateOperationsInput | string
  requiredQty?: Prisma.IntFieldUpdateOperationsInput | number
  lastStockSnapshot?: Prisma.IntFieldUpdateOperationsInput | number
  replenishQty?: Prisma.IntFieldUpdateOperationsInput | number
  unitPrice?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  totalAmount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  usedAmount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type RABLineCreateManyRabInput = {
  id?: string
  itemId: string
  requiredQty: number
  lastStockSnapshot: number
  replenishQty: number
  unitPrice: runtime.Decimal | runtime.DecimalJsLike | number | string
  totalAmount: runtime.Decimal | runtime.DecimalJsLike | number | string
  usedAmount?: runtime.Decimal | runtime.DecimalJsLike | number | string
  notes?: string | null
}

export type RABLineUpdateWithoutRabInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  requiredQty?: Prisma.IntFieldUpdateOperationsInput | number
  lastStockSnapshot?: Prisma.IntFieldUpdateOperationsInput | number
  replenishQty?: Prisma.IntFieldUpdateOperationsInput | number
  unitPrice?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  totalAmount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  usedAmount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  item?: Prisma.ItemUpdateOneRequiredWithoutRabLinesNestedInput
}

export type RABLineUncheckedUpdateWithoutRabInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  itemId?: Prisma.StringFieldUpdateOperationsInput | string
  requiredQty?: Prisma.IntFieldUpdateOperationsInput | number
  lastStockSnapshot?: Prisma.IntFieldUpdateOperationsInput | number
  replenishQty?: Prisma.IntFieldUpdateOperationsInput | number
  unitPrice?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  totalAmount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  usedAmount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type RABLineUncheckedUpdateManyWithoutRabInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  itemId?: Prisma.StringFieldUpdateOperationsInput | string
  requiredQty?: Prisma.IntFieldUpdateOperationsInput | number
  lastStockSnapshot?: Prisma.IntFieldUpdateOperationsInput | number
  replenishQty?: Prisma.IntFieldUpdateOperationsInput | number
  unitPrice?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  totalAmount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  usedAmount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}



export type RABLineSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  rabId?: boolean
  itemId?: boolean
  requiredQty?: boolean
  lastStockSnapshot?: boolean
  replenishQty?: boolean
  unitPrice?: boolean
  totalAmount?: boolean
  usedAmount?: boolean
  notes?: boolean
  rab?: boolean | Prisma.RABDefaultArgs<ExtArgs>
  item?: boolean | Prisma.ItemDefaultArgs<ExtArgs>
}, ExtArgs["result"]["rABLine"]>

export type RABLineSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  rabId?: boolean
  itemId?: boolean
  requiredQty?: boolean
  lastStockSnapshot?: boolean
  replenishQty?: boolean
  unitPrice?: boolean
  totalAmount?: boolean
  usedAmount?: boolean
  notes?: boolean
  rab?: boolean | Prisma.RABDefaultArgs<ExtArgs>
  item?: boolean | Prisma.ItemDefaultArgs<ExtArgs>
}, ExtArgs["result"]["rABLine"]>

export type RABLineSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  rabId?: boolean
  itemId?: boolean
  requiredQty?: boolean
  lastStockSnapshot?: boolean
  replenishQty?: boolean
  unitPrice?: boolean
  totalAmount?: boolean
  usedAmount?: boolean
  notes?: boolean
  rab?: boolean | Prisma.RABDefaultArgs<ExtArgs>
  item?: boolean | Prisma.ItemDefaultArgs<ExtArgs>
}, ExtArgs["result"]["rABLine"]>

export type RABLineSelectScalar = {
  id?: boolean
  rabId?: boolean
  itemId?: boolean
  requiredQty?: boolean
  lastStockSnapshot?: boolean
  replenishQty?: boolean
  unitPrice?: boolean
  totalAmount?: boolean
  usedAmount?: boolean
  notes?: boolean
}

export type RABLineOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "rabId" | "itemId" | "requiredQty" | "lastStockSnapshot" | "replenishQty" | "unitPrice" | "totalAmount" | "usedAmount" | "notes", ExtArgs["result"]["rABLine"]>
export type RABLineInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  rab?: boolean | Prisma.RABDefaultArgs<ExtArgs>
  item?: boolean | Prisma.ItemDefaultArgs<ExtArgs>
}
export type RABLineIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  rab?: boolean | Prisma.RABDefaultArgs<ExtArgs>
  item?: boolean | Prisma.ItemDefaultArgs<ExtArgs>
}
export type RABLineIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  rab?: boolean | Prisma.RABDefaultArgs<ExtArgs>
  item?: boolean | Prisma.ItemDefaultArgs<ExtArgs>
}

export type $RABLinePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "RABLine"
  objects: {
    rab: Prisma.$RABPayload<ExtArgs>
    item: Prisma.$ItemPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    rabId: string
    itemId: string
    requiredQty: number
    lastStockSnapshot: number
    replenishQty: number
    unitPrice: runtime.Decimal
    totalAmount: runtime.Decimal
    usedAmount: runtime.Decimal
    notes: string | null
  }, ExtArgs["result"]["rABLine"]>
  composites: {}
}

export type RABLineGetPayload<S extends boolean | null | undefined | RABLineDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$RABLinePayload, S>

export type RABLineCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<RABLineFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: RABLineCountAggregateInputType | true
  }

export interface RABLineDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['RABLine'], meta: { name: 'RABLine' } }
  /**
   * Find zero or one RABLine that matches the filter.
   * @param {RABLineFindUniqueArgs} args - Arguments to find a RABLine
   * @example
   * // Get one RABLine
   * const rABLine = await prisma.rABLine.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends RABLineFindUniqueArgs>(args: Prisma.SelectSubset<T, RABLineFindUniqueArgs<ExtArgs>>): Prisma.Prisma__RABLineClient<runtime.Types.Result.GetResult<Prisma.$RABLinePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one RABLine that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {RABLineFindUniqueOrThrowArgs} args - Arguments to find a RABLine
   * @example
   * // Get one RABLine
   * const rABLine = await prisma.rABLine.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends RABLineFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, RABLineFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__RABLineClient<runtime.Types.Result.GetResult<Prisma.$RABLinePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first RABLine that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RABLineFindFirstArgs} args - Arguments to find a RABLine
   * @example
   * // Get one RABLine
   * const rABLine = await prisma.rABLine.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends RABLineFindFirstArgs>(args?: Prisma.SelectSubset<T, RABLineFindFirstArgs<ExtArgs>>): Prisma.Prisma__RABLineClient<runtime.Types.Result.GetResult<Prisma.$RABLinePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first RABLine that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RABLineFindFirstOrThrowArgs} args - Arguments to find a RABLine
   * @example
   * // Get one RABLine
   * const rABLine = await prisma.rABLine.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends RABLineFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, RABLineFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__RABLineClient<runtime.Types.Result.GetResult<Prisma.$RABLinePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more RABLines that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RABLineFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all RABLines
   * const rABLines = await prisma.rABLine.findMany()
   * 
   * // Get first 10 RABLines
   * const rABLines = await prisma.rABLine.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const rABLineWithIdOnly = await prisma.rABLine.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends RABLineFindManyArgs>(args?: Prisma.SelectSubset<T, RABLineFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$RABLinePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a RABLine.
   * @param {RABLineCreateArgs} args - Arguments to create a RABLine.
   * @example
   * // Create one RABLine
   * const RABLine = await prisma.rABLine.create({
   *   data: {
   *     // ... data to create a RABLine
   *   }
   * })
   * 
   */
  create<T extends RABLineCreateArgs>(args: Prisma.SelectSubset<T, RABLineCreateArgs<ExtArgs>>): Prisma.Prisma__RABLineClient<runtime.Types.Result.GetResult<Prisma.$RABLinePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many RABLines.
   * @param {RABLineCreateManyArgs} args - Arguments to create many RABLines.
   * @example
   * // Create many RABLines
   * const rABLine = await prisma.rABLine.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends RABLineCreateManyArgs>(args?: Prisma.SelectSubset<T, RABLineCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many RABLines and returns the data saved in the database.
   * @param {RABLineCreateManyAndReturnArgs} args - Arguments to create many RABLines.
   * @example
   * // Create many RABLines
   * const rABLine = await prisma.rABLine.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many RABLines and only return the `id`
   * const rABLineWithIdOnly = await prisma.rABLine.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends RABLineCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, RABLineCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$RABLinePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a RABLine.
   * @param {RABLineDeleteArgs} args - Arguments to delete one RABLine.
   * @example
   * // Delete one RABLine
   * const RABLine = await prisma.rABLine.delete({
   *   where: {
   *     // ... filter to delete one RABLine
   *   }
   * })
   * 
   */
  delete<T extends RABLineDeleteArgs>(args: Prisma.SelectSubset<T, RABLineDeleteArgs<ExtArgs>>): Prisma.Prisma__RABLineClient<runtime.Types.Result.GetResult<Prisma.$RABLinePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one RABLine.
   * @param {RABLineUpdateArgs} args - Arguments to update one RABLine.
   * @example
   * // Update one RABLine
   * const rABLine = await prisma.rABLine.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends RABLineUpdateArgs>(args: Prisma.SelectSubset<T, RABLineUpdateArgs<ExtArgs>>): Prisma.Prisma__RABLineClient<runtime.Types.Result.GetResult<Prisma.$RABLinePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more RABLines.
   * @param {RABLineDeleteManyArgs} args - Arguments to filter RABLines to delete.
   * @example
   * // Delete a few RABLines
   * const { count } = await prisma.rABLine.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends RABLineDeleteManyArgs>(args?: Prisma.SelectSubset<T, RABLineDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more RABLines.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RABLineUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many RABLines
   * const rABLine = await prisma.rABLine.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends RABLineUpdateManyArgs>(args: Prisma.SelectSubset<T, RABLineUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more RABLines and returns the data updated in the database.
   * @param {RABLineUpdateManyAndReturnArgs} args - Arguments to update many RABLines.
   * @example
   * // Update many RABLines
   * const rABLine = await prisma.rABLine.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more RABLines and only return the `id`
   * const rABLineWithIdOnly = await prisma.rABLine.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends RABLineUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, RABLineUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$RABLinePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one RABLine.
   * @param {RABLineUpsertArgs} args - Arguments to update or create a RABLine.
   * @example
   * // Update or create a RABLine
   * const rABLine = await prisma.rABLine.upsert({
   *   create: {
   *     // ... data to create a RABLine
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the RABLine we want to update
   *   }
   * })
   */
  upsert<T extends RABLineUpsertArgs>(args: Prisma.SelectSubset<T, RABLineUpsertArgs<ExtArgs>>): Prisma.Prisma__RABLineClient<runtime.Types.Result.GetResult<Prisma.$RABLinePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of RABLines.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RABLineCountArgs} args - Arguments to filter RABLines to count.
   * @example
   * // Count the number of RABLines
   * const count = await prisma.rABLine.count({
   *   where: {
   *     // ... the filter for the RABLines we want to count
   *   }
   * })
  **/
  count<T extends RABLineCountArgs>(
    args?: Prisma.Subset<T, RABLineCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], RABLineCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a RABLine.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RABLineAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends RABLineAggregateArgs>(args: Prisma.Subset<T, RABLineAggregateArgs>): Prisma.PrismaPromise<GetRABLineAggregateType<T>>

  /**
   * Group by RABLine.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RABLineGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends RABLineGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: RABLineGroupByArgs['orderBy'] }
      : { orderBy?: RABLineGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, RABLineGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetRABLineGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the RABLine model
 */
readonly fields: RABLineFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for RABLine.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__RABLineClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  rab<T extends Prisma.RABDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.RABDefaultArgs<ExtArgs>>): Prisma.Prisma__RABClient<runtime.Types.Result.GetResult<Prisma.$RABPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  item<T extends Prisma.ItemDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ItemDefaultArgs<ExtArgs>>): Prisma.Prisma__ItemClient<runtime.Types.Result.GetResult<Prisma.$ItemPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the RABLine model
 */
export interface RABLineFieldRefs {
  readonly id: Prisma.FieldRef<"RABLine", 'String'>
  readonly rabId: Prisma.FieldRef<"RABLine", 'String'>
  readonly itemId: Prisma.FieldRef<"RABLine", 'String'>
  readonly requiredQty: Prisma.FieldRef<"RABLine", 'Int'>
  readonly lastStockSnapshot: Prisma.FieldRef<"RABLine", 'Int'>
  readonly replenishQty: Prisma.FieldRef<"RABLine", 'Int'>
  readonly unitPrice: Prisma.FieldRef<"RABLine", 'Decimal'>
  readonly totalAmount: Prisma.FieldRef<"RABLine", 'Decimal'>
  readonly usedAmount: Prisma.FieldRef<"RABLine", 'Decimal'>
  readonly notes: Prisma.FieldRef<"RABLine", 'String'>
}
    

// Custom InputTypes
/**
 * RABLine findUnique
 */
export type RABLineFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RABLine
   */
  select?: Prisma.RABLineSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RABLine
   */
  omit?: Prisma.RABLineOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RABLineInclude<ExtArgs> | null
  /**
   * Filter, which RABLine to fetch.
   */
  where: Prisma.RABLineWhereUniqueInput
}

/**
 * RABLine findUniqueOrThrow
 */
export type RABLineFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RABLine
   */
  select?: Prisma.RABLineSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RABLine
   */
  omit?: Prisma.RABLineOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RABLineInclude<ExtArgs> | null
  /**
   * Filter, which RABLine to fetch.
   */
  where: Prisma.RABLineWhereUniqueInput
}

/**
 * RABLine findFirst
 */
export type RABLineFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RABLine
   */
  select?: Prisma.RABLineSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RABLine
   */
  omit?: Prisma.RABLineOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RABLineInclude<ExtArgs> | null
  /**
   * Filter, which RABLine to fetch.
   */
  where?: Prisma.RABLineWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of RABLines to fetch.
   */
  orderBy?: Prisma.RABLineOrderByWithRelationInput | Prisma.RABLineOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for RABLines.
   */
  cursor?: Prisma.RABLineWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` RABLines from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` RABLines.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of RABLines.
   */
  distinct?: Prisma.RABLineScalarFieldEnum | Prisma.RABLineScalarFieldEnum[]
}

/**
 * RABLine findFirstOrThrow
 */
export type RABLineFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RABLine
   */
  select?: Prisma.RABLineSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RABLine
   */
  omit?: Prisma.RABLineOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RABLineInclude<ExtArgs> | null
  /**
   * Filter, which RABLine to fetch.
   */
  where?: Prisma.RABLineWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of RABLines to fetch.
   */
  orderBy?: Prisma.RABLineOrderByWithRelationInput | Prisma.RABLineOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for RABLines.
   */
  cursor?: Prisma.RABLineWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` RABLines from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` RABLines.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of RABLines.
   */
  distinct?: Prisma.RABLineScalarFieldEnum | Prisma.RABLineScalarFieldEnum[]
}

/**
 * RABLine findMany
 */
export type RABLineFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RABLine
   */
  select?: Prisma.RABLineSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RABLine
   */
  omit?: Prisma.RABLineOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RABLineInclude<ExtArgs> | null
  /**
   * Filter, which RABLines to fetch.
   */
  where?: Prisma.RABLineWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of RABLines to fetch.
   */
  orderBy?: Prisma.RABLineOrderByWithRelationInput | Prisma.RABLineOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing RABLines.
   */
  cursor?: Prisma.RABLineWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` RABLines from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` RABLines.
   */
  skip?: number
  distinct?: Prisma.RABLineScalarFieldEnum | Prisma.RABLineScalarFieldEnum[]
}

/**
 * RABLine create
 */
export type RABLineCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RABLine
   */
  select?: Prisma.RABLineSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RABLine
   */
  omit?: Prisma.RABLineOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RABLineInclude<ExtArgs> | null
  /**
   * The data needed to create a RABLine.
   */
  data: Prisma.XOR<Prisma.RABLineCreateInput, Prisma.RABLineUncheckedCreateInput>
}

/**
 * RABLine createMany
 */
export type RABLineCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many RABLines.
   */
  data: Prisma.RABLineCreateManyInput | Prisma.RABLineCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * RABLine createManyAndReturn
 */
export type RABLineCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RABLine
   */
  select?: Prisma.RABLineSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the RABLine
   */
  omit?: Prisma.RABLineOmit<ExtArgs> | null
  /**
   * The data used to create many RABLines.
   */
  data: Prisma.RABLineCreateManyInput | Prisma.RABLineCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RABLineIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * RABLine update
 */
export type RABLineUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RABLine
   */
  select?: Prisma.RABLineSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RABLine
   */
  omit?: Prisma.RABLineOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RABLineInclude<ExtArgs> | null
  /**
   * The data needed to update a RABLine.
   */
  data: Prisma.XOR<Prisma.RABLineUpdateInput, Prisma.RABLineUncheckedUpdateInput>
  /**
   * Choose, which RABLine to update.
   */
  where: Prisma.RABLineWhereUniqueInput
}

/**
 * RABLine updateMany
 */
export type RABLineUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update RABLines.
   */
  data: Prisma.XOR<Prisma.RABLineUpdateManyMutationInput, Prisma.RABLineUncheckedUpdateManyInput>
  /**
   * Filter which RABLines to update
   */
  where?: Prisma.RABLineWhereInput
  /**
   * Limit how many RABLines to update.
   */
  limit?: number
}

/**
 * RABLine updateManyAndReturn
 */
export type RABLineUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RABLine
   */
  select?: Prisma.RABLineSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the RABLine
   */
  omit?: Prisma.RABLineOmit<ExtArgs> | null
  /**
   * The data used to update RABLines.
   */
  data: Prisma.XOR<Prisma.RABLineUpdateManyMutationInput, Prisma.RABLineUncheckedUpdateManyInput>
  /**
   * Filter which RABLines to update
   */
  where?: Prisma.RABLineWhereInput
  /**
   * Limit how many RABLines to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RABLineIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * RABLine upsert
 */
export type RABLineUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RABLine
   */
  select?: Prisma.RABLineSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RABLine
   */
  omit?: Prisma.RABLineOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RABLineInclude<ExtArgs> | null
  /**
   * The filter to search for the RABLine to update in case it exists.
   */
  where: Prisma.RABLineWhereUniqueInput
  /**
   * In case the RABLine found by the `where` argument doesn't exist, create a new RABLine with this data.
   */
  create: Prisma.XOR<Prisma.RABLineCreateInput, Prisma.RABLineUncheckedCreateInput>
  /**
   * In case the RABLine was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.RABLineUpdateInput, Prisma.RABLineUncheckedUpdateInput>
}

/**
 * RABLine delete
 */
export type RABLineDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RABLine
   */
  select?: Prisma.RABLineSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RABLine
   */
  omit?: Prisma.RABLineOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RABLineInclude<ExtArgs> | null
  /**
   * Filter which RABLine to delete.
   */
  where: Prisma.RABLineWhereUniqueInput
}

/**
 * RABLine deleteMany
 */
export type RABLineDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which RABLines to delete
   */
  where?: Prisma.RABLineWhereInput
  /**
   * Limit how many RABLines to delete.
   */
  limit?: number
}

/**
 * RABLine without action
 */
export type RABLineDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RABLine
   */
  select?: Prisma.RABLineSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RABLine
   */
  omit?: Prisma.RABLineOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RABLineInclude<ExtArgs> | null
}
