
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `UOM` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model UOM
 * 
 */
export type UOMModel = runtime.Types.Result.DefaultSelection<Prisma.$UOMPayload>

export type AggregateUOM = {
  _count: UOMCountAggregateOutputType | null
  _min: UOMMinAggregateOutputType | null
  _max: UOMMaxAggregateOutputType | null
}

export type UOMMinAggregateOutputType = {
  id: string | null
  name: string | null
  symbol: string | null
  isActive: boolean | null
  createdAt: Date | null
  updatedAt: Date | null
  createdById: string | null
}

export type UOMMaxAggregateOutputType = {
  id: string | null
  name: string | null
  symbol: string | null
  isActive: boolean | null
  createdAt: Date | null
  updatedAt: Date | null
  createdById: string | null
}

export type UOMCountAggregateOutputType = {
  id: number
  name: number
  symbol: number
  isActive: number
  createdAt: number
  updatedAt: number
  createdById: number
  _all: number
}


export type UOMMinAggregateInputType = {
  id?: true
  name?: true
  symbol?: true
  isActive?: true
  createdAt?: true
  updatedAt?: true
  createdById?: true
}

export type UOMMaxAggregateInputType = {
  id?: true
  name?: true
  symbol?: true
  isActive?: true
  createdAt?: true
  updatedAt?: true
  createdById?: true
}

export type UOMCountAggregateInputType = {
  id?: true
  name?: true
  symbol?: true
  isActive?: true
  createdAt?: true
  updatedAt?: true
  createdById?: true
  _all?: true
}

export type UOMAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which UOM to aggregate.
   */
  where?: Prisma.UOMWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of UOMS to fetch.
   */
  orderBy?: Prisma.UOMOrderByWithRelationInput | Prisma.UOMOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.UOMWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` UOMS from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` UOMS.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned UOMS
  **/
  _count?: true | UOMCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: UOMMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: UOMMaxAggregateInputType
}

export type GetUOMAggregateType<T extends UOMAggregateArgs> = {
      [P in keyof T & keyof AggregateUOM]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateUOM[P]>
    : Prisma.GetScalarType<T[P], AggregateUOM[P]>
}




export type UOMGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.UOMWhereInput
  orderBy?: Prisma.UOMOrderByWithAggregationInput | Prisma.UOMOrderByWithAggregationInput[]
  by: Prisma.UOMScalarFieldEnum[] | Prisma.UOMScalarFieldEnum
  having?: Prisma.UOMScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: UOMCountAggregateInputType | true
  _min?: UOMMinAggregateInputType
  _max?: UOMMaxAggregateInputType
}

export type UOMGroupByOutputType = {
  id: string
  name: string
  symbol: string
  isActive: boolean
  createdAt: Date
  updatedAt: Date
  createdById: string | null
  _count: UOMCountAggregateOutputType | null
  _min: UOMMinAggregateOutputType | null
  _max: UOMMaxAggregateOutputType | null
}

type GetUOMGroupByPayload<T extends UOMGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<UOMGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof UOMGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], UOMGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], UOMGroupByOutputType[P]>
      }
    >
  >



export type UOMWhereInput = {
  AND?: Prisma.UOMWhereInput | Prisma.UOMWhereInput[]
  OR?: Prisma.UOMWhereInput[]
  NOT?: Prisma.UOMWhereInput | Prisma.UOMWhereInput[]
  id?: Prisma.StringFilter<"UOM"> | string
  name?: Prisma.StringFilter<"UOM"> | string
  symbol?: Prisma.StringFilter<"UOM"> | string
  isActive?: Prisma.BoolFilter<"UOM"> | boolean
  createdAt?: Prisma.DateTimeFilter<"UOM"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"UOM"> | Date | string
  createdById?: Prisma.StringNullableFilter<"UOM"> | string | null
  createdBy?: Prisma.XOR<Prisma.UserNullableScalarRelationFilter, Prisma.UserWhereInput> | null
  items?: Prisma.ItemListRelationFilter
}

export type UOMOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  symbol?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  createdById?: Prisma.SortOrderInput | Prisma.SortOrder
  createdBy?: Prisma.UserOrderByWithRelationInput
  items?: Prisma.ItemOrderByRelationAggregateInput
}

export type UOMWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  name?: string
  symbol?: string
  AND?: Prisma.UOMWhereInput | Prisma.UOMWhereInput[]
  OR?: Prisma.UOMWhereInput[]
  NOT?: Prisma.UOMWhereInput | Prisma.UOMWhereInput[]
  isActive?: Prisma.BoolFilter<"UOM"> | boolean
  createdAt?: Prisma.DateTimeFilter<"UOM"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"UOM"> | Date | string
  createdById?: Prisma.StringNullableFilter<"UOM"> | string | null
  createdBy?: Prisma.XOR<Prisma.UserNullableScalarRelationFilter, Prisma.UserWhereInput> | null
  items?: Prisma.ItemListRelationFilter
}, "id" | "name" | "symbol">

export type UOMOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  symbol?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  createdById?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.UOMCountOrderByAggregateInput
  _max?: Prisma.UOMMaxOrderByAggregateInput
  _min?: Prisma.UOMMinOrderByAggregateInput
}

export type UOMScalarWhereWithAggregatesInput = {
  AND?: Prisma.UOMScalarWhereWithAggregatesInput | Prisma.UOMScalarWhereWithAggregatesInput[]
  OR?: Prisma.UOMScalarWhereWithAggregatesInput[]
  NOT?: Prisma.UOMScalarWhereWithAggregatesInput | Prisma.UOMScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"UOM"> | string
  name?: Prisma.StringWithAggregatesFilter<"UOM"> | string
  symbol?: Prisma.StringWithAggregatesFilter<"UOM"> | string
  isActive?: Prisma.BoolWithAggregatesFilter<"UOM"> | boolean
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"UOM"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"UOM"> | Date | string
  createdById?: Prisma.StringNullableWithAggregatesFilter<"UOM"> | string | null
}

export type UOMCreateInput = {
  id?: string
  name: string
  symbol: string
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  createdBy?: Prisma.UserCreateNestedOneWithoutCreatedUOMsInput
  items?: Prisma.ItemCreateNestedManyWithoutUomInput
}

export type UOMUncheckedCreateInput = {
  id?: string
  name: string
  symbol: string
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  createdById?: string | null
  items?: Prisma.ItemUncheckedCreateNestedManyWithoutUomInput
}

export type UOMUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  symbol?: Prisma.StringFieldUpdateOperationsInput | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdBy?: Prisma.UserUpdateOneWithoutCreatedUOMsNestedInput
  items?: Prisma.ItemUpdateManyWithoutUomNestedInput
}

export type UOMUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  symbol?: Prisma.StringFieldUpdateOperationsInput | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdById?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  items?: Prisma.ItemUncheckedUpdateManyWithoutUomNestedInput
}

export type UOMCreateManyInput = {
  id?: string
  name: string
  symbol: string
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  createdById?: string | null
}

export type UOMUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  symbol?: Prisma.StringFieldUpdateOperationsInput | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type UOMUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  symbol?: Prisma.StringFieldUpdateOperationsInput | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdById?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type UOMListRelationFilter = {
  every?: Prisma.UOMWhereInput
  some?: Prisma.UOMWhereInput
  none?: Prisma.UOMWhereInput
}

export type UOMOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type UOMCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  symbol?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  createdById?: Prisma.SortOrder
}

export type UOMMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  symbol?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  createdById?: Prisma.SortOrder
}

export type UOMMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  symbol?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  createdById?: Prisma.SortOrder
}

export type UOMScalarRelationFilter = {
  is?: Prisma.UOMWhereInput
  isNot?: Prisma.UOMWhereInput
}

export type UOMCreateNestedManyWithoutCreatedByInput = {
  create?: Prisma.XOR<Prisma.UOMCreateWithoutCreatedByInput, Prisma.UOMUncheckedCreateWithoutCreatedByInput> | Prisma.UOMCreateWithoutCreatedByInput[] | Prisma.UOMUncheckedCreateWithoutCreatedByInput[]
  connectOrCreate?: Prisma.UOMCreateOrConnectWithoutCreatedByInput | Prisma.UOMCreateOrConnectWithoutCreatedByInput[]
  createMany?: Prisma.UOMCreateManyCreatedByInputEnvelope
  connect?: Prisma.UOMWhereUniqueInput | Prisma.UOMWhereUniqueInput[]
}

export type UOMUncheckedCreateNestedManyWithoutCreatedByInput = {
  create?: Prisma.XOR<Prisma.UOMCreateWithoutCreatedByInput, Prisma.UOMUncheckedCreateWithoutCreatedByInput> | Prisma.UOMCreateWithoutCreatedByInput[] | Prisma.UOMUncheckedCreateWithoutCreatedByInput[]
  connectOrCreate?: Prisma.UOMCreateOrConnectWithoutCreatedByInput | Prisma.UOMCreateOrConnectWithoutCreatedByInput[]
  createMany?: Prisma.UOMCreateManyCreatedByInputEnvelope
  connect?: Prisma.UOMWhereUniqueInput | Prisma.UOMWhereUniqueInput[]
}

export type UOMUpdateManyWithoutCreatedByNestedInput = {
  create?: Prisma.XOR<Prisma.UOMCreateWithoutCreatedByInput, Prisma.UOMUncheckedCreateWithoutCreatedByInput> | Prisma.UOMCreateWithoutCreatedByInput[] | Prisma.UOMUncheckedCreateWithoutCreatedByInput[]
  connectOrCreate?: Prisma.UOMCreateOrConnectWithoutCreatedByInput | Prisma.UOMCreateOrConnectWithoutCreatedByInput[]
  upsert?: Prisma.UOMUpsertWithWhereUniqueWithoutCreatedByInput | Prisma.UOMUpsertWithWhereUniqueWithoutCreatedByInput[]
  createMany?: Prisma.UOMCreateManyCreatedByInputEnvelope
  set?: Prisma.UOMWhereUniqueInput | Prisma.UOMWhereUniqueInput[]
  disconnect?: Prisma.UOMWhereUniqueInput | Prisma.UOMWhereUniqueInput[]
  delete?: Prisma.UOMWhereUniqueInput | Prisma.UOMWhereUniqueInput[]
  connect?: Prisma.UOMWhereUniqueInput | Prisma.UOMWhereUniqueInput[]
  update?: Prisma.UOMUpdateWithWhereUniqueWithoutCreatedByInput | Prisma.UOMUpdateWithWhereUniqueWithoutCreatedByInput[]
  updateMany?: Prisma.UOMUpdateManyWithWhereWithoutCreatedByInput | Prisma.UOMUpdateManyWithWhereWithoutCreatedByInput[]
  deleteMany?: Prisma.UOMScalarWhereInput | Prisma.UOMScalarWhereInput[]
}

export type UOMUncheckedUpdateManyWithoutCreatedByNestedInput = {
  create?: Prisma.XOR<Prisma.UOMCreateWithoutCreatedByInput, Prisma.UOMUncheckedCreateWithoutCreatedByInput> | Prisma.UOMCreateWithoutCreatedByInput[] | Prisma.UOMUncheckedCreateWithoutCreatedByInput[]
  connectOrCreate?: Prisma.UOMCreateOrConnectWithoutCreatedByInput | Prisma.UOMCreateOrConnectWithoutCreatedByInput[]
  upsert?: Prisma.UOMUpsertWithWhereUniqueWithoutCreatedByInput | Prisma.UOMUpsertWithWhereUniqueWithoutCreatedByInput[]
  createMany?: Prisma.UOMCreateManyCreatedByInputEnvelope
  set?: Prisma.UOMWhereUniqueInput | Prisma.UOMWhereUniqueInput[]
  disconnect?: Prisma.UOMWhereUniqueInput | Prisma.UOMWhereUniqueInput[]
  delete?: Prisma.UOMWhereUniqueInput | Prisma.UOMWhereUniqueInput[]
  connect?: Prisma.UOMWhereUniqueInput | Prisma.UOMWhereUniqueInput[]
  update?: Prisma.UOMUpdateWithWhereUniqueWithoutCreatedByInput | Prisma.UOMUpdateWithWhereUniqueWithoutCreatedByInput[]
  updateMany?: Prisma.UOMUpdateManyWithWhereWithoutCreatedByInput | Prisma.UOMUpdateManyWithWhereWithoutCreatedByInput[]
  deleteMany?: Prisma.UOMScalarWhereInput | Prisma.UOMScalarWhereInput[]
}

export type UOMCreateNestedOneWithoutItemsInput = {
  create?: Prisma.XOR<Prisma.UOMCreateWithoutItemsInput, Prisma.UOMUncheckedCreateWithoutItemsInput>
  connectOrCreate?: Prisma.UOMCreateOrConnectWithoutItemsInput
  connect?: Prisma.UOMWhereUniqueInput
}

export type UOMUpdateOneRequiredWithoutItemsNestedInput = {
  create?: Prisma.XOR<Prisma.UOMCreateWithoutItemsInput, Prisma.UOMUncheckedCreateWithoutItemsInput>
  connectOrCreate?: Prisma.UOMCreateOrConnectWithoutItemsInput
  upsert?: Prisma.UOMUpsertWithoutItemsInput
  connect?: Prisma.UOMWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.UOMUpdateToOneWithWhereWithoutItemsInput, Prisma.UOMUpdateWithoutItemsInput>, Prisma.UOMUncheckedUpdateWithoutItemsInput>
}

export type UOMCreateWithoutCreatedByInput = {
  id?: string
  name: string
  symbol: string
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  items?: Prisma.ItemCreateNestedManyWithoutUomInput
}

export type UOMUncheckedCreateWithoutCreatedByInput = {
  id?: string
  name: string
  symbol: string
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  items?: Prisma.ItemUncheckedCreateNestedManyWithoutUomInput
}

export type UOMCreateOrConnectWithoutCreatedByInput = {
  where: Prisma.UOMWhereUniqueInput
  create: Prisma.XOR<Prisma.UOMCreateWithoutCreatedByInput, Prisma.UOMUncheckedCreateWithoutCreatedByInput>
}

export type UOMCreateManyCreatedByInputEnvelope = {
  data: Prisma.UOMCreateManyCreatedByInput | Prisma.UOMCreateManyCreatedByInput[]
  skipDuplicates?: boolean
}

export type UOMUpsertWithWhereUniqueWithoutCreatedByInput = {
  where: Prisma.UOMWhereUniqueInput
  update: Prisma.XOR<Prisma.UOMUpdateWithoutCreatedByInput, Prisma.UOMUncheckedUpdateWithoutCreatedByInput>
  create: Prisma.XOR<Prisma.UOMCreateWithoutCreatedByInput, Prisma.UOMUncheckedCreateWithoutCreatedByInput>
}

export type UOMUpdateWithWhereUniqueWithoutCreatedByInput = {
  where: Prisma.UOMWhereUniqueInput
  data: Prisma.XOR<Prisma.UOMUpdateWithoutCreatedByInput, Prisma.UOMUncheckedUpdateWithoutCreatedByInput>
}

export type UOMUpdateManyWithWhereWithoutCreatedByInput = {
  where: Prisma.UOMScalarWhereInput
  data: Prisma.XOR<Prisma.UOMUpdateManyMutationInput, Prisma.UOMUncheckedUpdateManyWithoutCreatedByInput>
}

export type UOMScalarWhereInput = {
  AND?: Prisma.UOMScalarWhereInput | Prisma.UOMScalarWhereInput[]
  OR?: Prisma.UOMScalarWhereInput[]
  NOT?: Prisma.UOMScalarWhereInput | Prisma.UOMScalarWhereInput[]
  id?: Prisma.StringFilter<"UOM"> | string
  name?: Prisma.StringFilter<"UOM"> | string
  symbol?: Prisma.StringFilter<"UOM"> | string
  isActive?: Prisma.BoolFilter<"UOM"> | boolean
  createdAt?: Prisma.DateTimeFilter<"UOM"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"UOM"> | Date | string
  createdById?: Prisma.StringNullableFilter<"UOM"> | string | null
}

export type UOMCreateWithoutItemsInput = {
  id?: string
  name: string
  symbol: string
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  createdBy?: Prisma.UserCreateNestedOneWithoutCreatedUOMsInput
}

export type UOMUncheckedCreateWithoutItemsInput = {
  id?: string
  name: string
  symbol: string
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  createdById?: string | null
}

export type UOMCreateOrConnectWithoutItemsInput = {
  where: Prisma.UOMWhereUniqueInput
  create: Prisma.XOR<Prisma.UOMCreateWithoutItemsInput, Prisma.UOMUncheckedCreateWithoutItemsInput>
}

export type UOMUpsertWithoutItemsInput = {
  update: Prisma.XOR<Prisma.UOMUpdateWithoutItemsInput, Prisma.UOMUncheckedUpdateWithoutItemsInput>
  create: Prisma.XOR<Prisma.UOMCreateWithoutItemsInput, Prisma.UOMUncheckedCreateWithoutItemsInput>
  where?: Prisma.UOMWhereInput
}

export type UOMUpdateToOneWithWhereWithoutItemsInput = {
  where?: Prisma.UOMWhereInput
  data: Prisma.XOR<Prisma.UOMUpdateWithoutItemsInput, Prisma.UOMUncheckedUpdateWithoutItemsInput>
}

export type UOMUpdateWithoutItemsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  symbol?: Prisma.StringFieldUpdateOperationsInput | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdBy?: Prisma.UserUpdateOneWithoutCreatedUOMsNestedInput
}

export type UOMUncheckedUpdateWithoutItemsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  symbol?: Prisma.StringFieldUpdateOperationsInput | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdById?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type UOMCreateManyCreatedByInput = {
  id?: string
  name: string
  symbol: string
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type UOMUpdateWithoutCreatedByInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  symbol?: Prisma.StringFieldUpdateOperationsInput | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  items?: Prisma.ItemUpdateManyWithoutUomNestedInput
}

export type UOMUncheckedUpdateWithoutCreatedByInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  symbol?: Prisma.StringFieldUpdateOperationsInput | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  items?: Prisma.ItemUncheckedUpdateManyWithoutUomNestedInput
}

export type UOMUncheckedUpdateManyWithoutCreatedByInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  symbol?: Prisma.StringFieldUpdateOperationsInput | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type UOMCountOutputType
 */

export type UOMCountOutputType = {
  items: number
}

export type UOMCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  items?: boolean | UOMCountOutputTypeCountItemsArgs
}

/**
 * UOMCountOutputType without action
 */
export type UOMCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UOMCountOutputType
   */
  select?: Prisma.UOMCountOutputTypeSelect<ExtArgs> | null
}

/**
 * UOMCountOutputType without action
 */
export type UOMCountOutputTypeCountItemsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ItemWhereInput
}


export type UOMSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  symbol?: boolean
  isActive?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  createdById?: boolean
  createdBy?: boolean | Prisma.UOM$createdByArgs<ExtArgs>
  items?: boolean | Prisma.UOM$itemsArgs<ExtArgs>
  _count?: boolean | Prisma.UOMCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["uOM"]>

export type UOMSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  symbol?: boolean
  isActive?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  createdById?: boolean
  createdBy?: boolean | Prisma.UOM$createdByArgs<ExtArgs>
}, ExtArgs["result"]["uOM"]>

export type UOMSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  symbol?: boolean
  isActive?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  createdById?: boolean
  createdBy?: boolean | Prisma.UOM$createdByArgs<ExtArgs>
}, ExtArgs["result"]["uOM"]>

export type UOMSelectScalar = {
  id?: boolean
  name?: boolean
  symbol?: boolean
  isActive?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  createdById?: boolean
}

export type UOMOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "name" | "symbol" | "isActive" | "createdAt" | "updatedAt" | "createdById", ExtArgs["result"]["uOM"]>
export type UOMInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  createdBy?: boolean | Prisma.UOM$createdByArgs<ExtArgs>
  items?: boolean | Prisma.UOM$itemsArgs<ExtArgs>
  _count?: boolean | Prisma.UOMCountOutputTypeDefaultArgs<ExtArgs>
}
export type UOMIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  createdBy?: boolean | Prisma.UOM$createdByArgs<ExtArgs>
}
export type UOMIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  createdBy?: boolean | Prisma.UOM$createdByArgs<ExtArgs>
}

export type $UOMPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "UOM"
  objects: {
    createdBy: Prisma.$UserPayload<ExtArgs> | null
    items: Prisma.$ItemPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    name: string
    symbol: string
    isActive: boolean
    createdAt: Date
    updatedAt: Date
    createdById: string | null
  }, ExtArgs["result"]["uOM"]>
  composites: {}
}

export type UOMGetPayload<S extends boolean | null | undefined | UOMDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$UOMPayload, S>

export type UOMCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<UOMFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: UOMCountAggregateInputType | true
  }

export interface UOMDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['UOM'], meta: { name: 'UOM' } }
  /**
   * Find zero or one UOM that matches the filter.
   * @param {UOMFindUniqueArgs} args - Arguments to find a UOM
   * @example
   * // Get one UOM
   * const uOM = await prisma.uOM.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends UOMFindUniqueArgs>(args: Prisma.SelectSubset<T, UOMFindUniqueArgs<ExtArgs>>): Prisma.Prisma__UOMClient<runtime.Types.Result.GetResult<Prisma.$UOMPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one UOM that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {UOMFindUniqueOrThrowArgs} args - Arguments to find a UOM
   * @example
   * // Get one UOM
   * const uOM = await prisma.uOM.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends UOMFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, UOMFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__UOMClient<runtime.Types.Result.GetResult<Prisma.$UOMPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first UOM that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UOMFindFirstArgs} args - Arguments to find a UOM
   * @example
   * // Get one UOM
   * const uOM = await prisma.uOM.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends UOMFindFirstArgs>(args?: Prisma.SelectSubset<T, UOMFindFirstArgs<ExtArgs>>): Prisma.Prisma__UOMClient<runtime.Types.Result.GetResult<Prisma.$UOMPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first UOM that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UOMFindFirstOrThrowArgs} args - Arguments to find a UOM
   * @example
   * // Get one UOM
   * const uOM = await prisma.uOM.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends UOMFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, UOMFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__UOMClient<runtime.Types.Result.GetResult<Prisma.$UOMPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more UOMS that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UOMFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all UOMS
   * const uOMS = await prisma.uOM.findMany()
   * 
   * // Get first 10 UOMS
   * const uOMS = await prisma.uOM.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const uOMWithIdOnly = await prisma.uOM.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends UOMFindManyArgs>(args?: Prisma.SelectSubset<T, UOMFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UOMPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a UOM.
   * @param {UOMCreateArgs} args - Arguments to create a UOM.
   * @example
   * // Create one UOM
   * const UOM = await prisma.uOM.create({
   *   data: {
   *     // ... data to create a UOM
   *   }
   * })
   * 
   */
  create<T extends UOMCreateArgs>(args: Prisma.SelectSubset<T, UOMCreateArgs<ExtArgs>>): Prisma.Prisma__UOMClient<runtime.Types.Result.GetResult<Prisma.$UOMPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many UOMS.
   * @param {UOMCreateManyArgs} args - Arguments to create many UOMS.
   * @example
   * // Create many UOMS
   * const uOM = await prisma.uOM.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends UOMCreateManyArgs>(args?: Prisma.SelectSubset<T, UOMCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many UOMS and returns the data saved in the database.
   * @param {UOMCreateManyAndReturnArgs} args - Arguments to create many UOMS.
   * @example
   * // Create many UOMS
   * const uOM = await prisma.uOM.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many UOMS and only return the `id`
   * const uOMWithIdOnly = await prisma.uOM.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends UOMCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, UOMCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UOMPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a UOM.
   * @param {UOMDeleteArgs} args - Arguments to delete one UOM.
   * @example
   * // Delete one UOM
   * const UOM = await prisma.uOM.delete({
   *   where: {
   *     // ... filter to delete one UOM
   *   }
   * })
   * 
   */
  delete<T extends UOMDeleteArgs>(args: Prisma.SelectSubset<T, UOMDeleteArgs<ExtArgs>>): Prisma.Prisma__UOMClient<runtime.Types.Result.GetResult<Prisma.$UOMPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one UOM.
   * @param {UOMUpdateArgs} args - Arguments to update one UOM.
   * @example
   * // Update one UOM
   * const uOM = await prisma.uOM.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends UOMUpdateArgs>(args: Prisma.SelectSubset<T, UOMUpdateArgs<ExtArgs>>): Prisma.Prisma__UOMClient<runtime.Types.Result.GetResult<Prisma.$UOMPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more UOMS.
   * @param {UOMDeleteManyArgs} args - Arguments to filter UOMS to delete.
   * @example
   * // Delete a few UOMS
   * const { count } = await prisma.uOM.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends UOMDeleteManyArgs>(args?: Prisma.SelectSubset<T, UOMDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more UOMS.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UOMUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many UOMS
   * const uOM = await prisma.uOM.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends UOMUpdateManyArgs>(args: Prisma.SelectSubset<T, UOMUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more UOMS and returns the data updated in the database.
   * @param {UOMUpdateManyAndReturnArgs} args - Arguments to update many UOMS.
   * @example
   * // Update many UOMS
   * const uOM = await prisma.uOM.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more UOMS and only return the `id`
   * const uOMWithIdOnly = await prisma.uOM.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends UOMUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, UOMUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UOMPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one UOM.
   * @param {UOMUpsertArgs} args - Arguments to update or create a UOM.
   * @example
   * // Update or create a UOM
   * const uOM = await prisma.uOM.upsert({
   *   create: {
   *     // ... data to create a UOM
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the UOM we want to update
   *   }
   * })
   */
  upsert<T extends UOMUpsertArgs>(args: Prisma.SelectSubset<T, UOMUpsertArgs<ExtArgs>>): Prisma.Prisma__UOMClient<runtime.Types.Result.GetResult<Prisma.$UOMPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of UOMS.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UOMCountArgs} args - Arguments to filter UOMS to count.
   * @example
   * // Count the number of UOMS
   * const count = await prisma.uOM.count({
   *   where: {
   *     // ... the filter for the UOMS we want to count
   *   }
   * })
  **/
  count<T extends UOMCountArgs>(
    args?: Prisma.Subset<T, UOMCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], UOMCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a UOM.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UOMAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends UOMAggregateArgs>(args: Prisma.Subset<T, UOMAggregateArgs>): Prisma.PrismaPromise<GetUOMAggregateType<T>>

  /**
   * Group by UOM.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UOMGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends UOMGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: UOMGroupByArgs['orderBy'] }
      : { orderBy?: UOMGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, UOMGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetUOMGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the UOM model
 */
readonly fields: UOMFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for UOM.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__UOMClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  createdBy<T extends Prisma.UOM$createdByArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UOM$createdByArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  items<T extends Prisma.UOM$itemsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UOM$itemsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ItemPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the UOM model
 */
export interface UOMFieldRefs {
  readonly id: Prisma.FieldRef<"UOM", 'String'>
  readonly name: Prisma.FieldRef<"UOM", 'String'>
  readonly symbol: Prisma.FieldRef<"UOM", 'String'>
  readonly isActive: Prisma.FieldRef<"UOM", 'Boolean'>
  readonly createdAt: Prisma.FieldRef<"UOM", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"UOM", 'DateTime'>
  readonly createdById: Prisma.FieldRef<"UOM", 'String'>
}
    

// Custom InputTypes
/**
 * UOM findUnique
 */
export type UOMFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UOM
   */
  select?: Prisma.UOMSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UOM
   */
  omit?: Prisma.UOMOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UOMInclude<ExtArgs> | null
  /**
   * Filter, which UOM to fetch.
   */
  where: Prisma.UOMWhereUniqueInput
}

/**
 * UOM findUniqueOrThrow
 */
export type UOMFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UOM
   */
  select?: Prisma.UOMSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UOM
   */
  omit?: Prisma.UOMOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UOMInclude<ExtArgs> | null
  /**
   * Filter, which UOM to fetch.
   */
  where: Prisma.UOMWhereUniqueInput
}

/**
 * UOM findFirst
 */
export type UOMFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UOM
   */
  select?: Prisma.UOMSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UOM
   */
  omit?: Prisma.UOMOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UOMInclude<ExtArgs> | null
  /**
   * Filter, which UOM to fetch.
   */
  where?: Prisma.UOMWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of UOMS to fetch.
   */
  orderBy?: Prisma.UOMOrderByWithRelationInput | Prisma.UOMOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for UOMS.
   */
  cursor?: Prisma.UOMWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` UOMS from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` UOMS.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of UOMS.
   */
  distinct?: Prisma.UOMScalarFieldEnum | Prisma.UOMScalarFieldEnum[]
}

/**
 * UOM findFirstOrThrow
 */
export type UOMFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UOM
   */
  select?: Prisma.UOMSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UOM
   */
  omit?: Prisma.UOMOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UOMInclude<ExtArgs> | null
  /**
   * Filter, which UOM to fetch.
   */
  where?: Prisma.UOMWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of UOMS to fetch.
   */
  orderBy?: Prisma.UOMOrderByWithRelationInput | Prisma.UOMOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for UOMS.
   */
  cursor?: Prisma.UOMWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` UOMS from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` UOMS.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of UOMS.
   */
  distinct?: Prisma.UOMScalarFieldEnum | Prisma.UOMScalarFieldEnum[]
}

/**
 * UOM findMany
 */
export type UOMFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UOM
   */
  select?: Prisma.UOMSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UOM
   */
  omit?: Prisma.UOMOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UOMInclude<ExtArgs> | null
  /**
   * Filter, which UOMS to fetch.
   */
  where?: Prisma.UOMWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of UOMS to fetch.
   */
  orderBy?: Prisma.UOMOrderByWithRelationInput | Prisma.UOMOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing UOMS.
   */
  cursor?: Prisma.UOMWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` UOMS from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` UOMS.
   */
  skip?: number
  distinct?: Prisma.UOMScalarFieldEnum | Prisma.UOMScalarFieldEnum[]
}

/**
 * UOM create
 */
export type UOMCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UOM
   */
  select?: Prisma.UOMSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UOM
   */
  omit?: Prisma.UOMOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UOMInclude<ExtArgs> | null
  /**
   * The data needed to create a UOM.
   */
  data: Prisma.XOR<Prisma.UOMCreateInput, Prisma.UOMUncheckedCreateInput>
}

/**
 * UOM createMany
 */
export type UOMCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many UOMS.
   */
  data: Prisma.UOMCreateManyInput | Prisma.UOMCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * UOM createManyAndReturn
 */
export type UOMCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UOM
   */
  select?: Prisma.UOMSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the UOM
   */
  omit?: Prisma.UOMOmit<ExtArgs> | null
  /**
   * The data used to create many UOMS.
   */
  data: Prisma.UOMCreateManyInput | Prisma.UOMCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UOMIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * UOM update
 */
export type UOMUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UOM
   */
  select?: Prisma.UOMSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UOM
   */
  omit?: Prisma.UOMOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UOMInclude<ExtArgs> | null
  /**
   * The data needed to update a UOM.
   */
  data: Prisma.XOR<Prisma.UOMUpdateInput, Prisma.UOMUncheckedUpdateInput>
  /**
   * Choose, which UOM to update.
   */
  where: Prisma.UOMWhereUniqueInput
}

/**
 * UOM updateMany
 */
export type UOMUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update UOMS.
   */
  data: Prisma.XOR<Prisma.UOMUpdateManyMutationInput, Prisma.UOMUncheckedUpdateManyInput>
  /**
   * Filter which UOMS to update
   */
  where?: Prisma.UOMWhereInput
  /**
   * Limit how many UOMS to update.
   */
  limit?: number
}

/**
 * UOM updateManyAndReturn
 */
export type UOMUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UOM
   */
  select?: Prisma.UOMSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the UOM
   */
  omit?: Prisma.UOMOmit<ExtArgs> | null
  /**
   * The data used to update UOMS.
   */
  data: Prisma.XOR<Prisma.UOMUpdateManyMutationInput, Prisma.UOMUncheckedUpdateManyInput>
  /**
   * Filter which UOMS to update
   */
  where?: Prisma.UOMWhereInput
  /**
   * Limit how many UOMS to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UOMIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * UOM upsert
 */
export type UOMUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UOM
   */
  select?: Prisma.UOMSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UOM
   */
  omit?: Prisma.UOMOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UOMInclude<ExtArgs> | null
  /**
   * The filter to search for the UOM to update in case it exists.
   */
  where: Prisma.UOMWhereUniqueInput
  /**
   * In case the UOM found by the `where` argument doesn't exist, create a new UOM with this data.
   */
  create: Prisma.XOR<Prisma.UOMCreateInput, Prisma.UOMUncheckedCreateInput>
  /**
   * In case the UOM was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.UOMUpdateInput, Prisma.UOMUncheckedUpdateInput>
}

/**
 * UOM delete
 */
export type UOMDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UOM
   */
  select?: Prisma.UOMSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UOM
   */
  omit?: Prisma.UOMOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UOMInclude<ExtArgs> | null
  /**
   * Filter which UOM to delete.
   */
  where: Prisma.UOMWhereUniqueInput
}

/**
 * UOM deleteMany
 */
export type UOMDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which UOMS to delete
   */
  where?: Prisma.UOMWhereInput
  /**
   * Limit how many UOMS to delete.
   */
  limit?: number
}

/**
 * UOM.createdBy
 */
export type UOM$createdByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  where?: Prisma.UserWhereInput
}

/**
 * UOM.items
 */
export type UOM$itemsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Item
   */
  select?: Prisma.ItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Item
   */
  omit?: Prisma.ItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ItemInclude<ExtArgs> | null
  where?: Prisma.ItemWhereInput
  orderBy?: Prisma.ItemOrderByWithRelationInput | Prisma.ItemOrderByWithRelationInput[]
  cursor?: Prisma.ItemWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.ItemScalarFieldEnum | Prisma.ItemScalarFieldEnum[]
}

/**
 * UOM without action
 */
export type UOMDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UOM
   */
  select?: Prisma.UOMSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UOM
   */
  omit?: Prisma.UOMOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UOMInclude<ExtArgs> | null
}
