
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file should be your main import to use Prisma-related types and utilities in a browser. 
 * Use it to get access to models, enums, and input types.
 * 
 * This file does not contain a `PrismaClient` class, nor several other helpers that are intended as server-side only.
 * See `client.ts` for the standard, server-side entry point.
 *
 * 🟢 You can import this file directly.
 */

import * as Prisma from './internal/prismaNamespaceBrowser'
export { Prisma }
export * as $Enums from './enums'
export * from './enums';
/**
 * Model User
 * 
 */
export type User = Prisma.UserModel
/**
 * Model Role
 * 
 */
export type Role = Prisma.RoleModel
/**
 * Model Permission
 * 
 */
export type Permission = Prisma.PermissionModel
/**
 * Model Category
 * 
 */
export type Category = Prisma.CategoryModel
/**
 * Model UOM
 * 
 */
export type UOM = Prisma.UOMModel
/**
 * Model Warehouse
 * 
 */
export type Warehouse = Prisma.WarehouseModel
/**
 * Model WarehouseStock
 * 
 */
export type WarehouseStock = Prisma.WarehouseStockModel
/**
 * Model Vendor
 * 
 */
export type Vendor = Prisma.VendorModel
/**
 * Model VendorItem
 * 
 */
export type VendorItem = Prisma.VendorItemModel
/**
 * Model Item
 * 
 */
export type Item = Prisma.ItemModel
/**
 * Model ItemPriceHistory
 * 
 */
export type ItemPriceHistory = Prisma.ItemPriceHistoryModel
/**
 * Model Currency
 * 
 */
export type Currency = Prisma.CurrencyModel
/**
 * Model RAB
 * 
 */
export type RAB = Prisma.RABModel
/**
 * Model RABLine
 * 
 */
export type RABLine = Prisma.RABLineModel
/**
 * Model PurchaseRequest
 * 
 */
export type PurchaseRequest = Prisma.PurchaseRequestModel
/**
 * Model PurchaseRequestItem
 * 
 */
export type PurchaseRequestItem = Prisma.PurchaseRequestItemModel
/**
 * Model Inbound
 * 
 */
export type Inbound = Prisma.InboundModel
/**
 * Model InboundItem
 * 
 */
export type InboundItem = Prisma.InboundItemModel
/**
 * Model Outbound
 * 
 */
export type Outbound = Prisma.OutboundModel
/**
 * Model OutboundItem
 * 
 */
export type OutboundItem = Prisma.OutboundItemModel
/**
 * Model Partner
 * 
 */
export type Partner = Prisma.PartnerModel
/**
 * Model PartnerItemPrice
 * 
 */
export type PartnerItemPrice = Prisma.PartnerItemPriceModel
/**
 * Model StockCard
 * 
 */
export type StockCard = Prisma.StockCardModel
/**
 * Model StockOpname
 * 
 */
export type StockOpname = Prisma.StockOpnameModel
/**
 * Model StockOpnameCount
 * 
 */
export type StockOpnameCount = Prisma.StockOpnameCountModel
/**
 * Model StockAdjustment
 * 
 */
export type StockAdjustment = Prisma.StockAdjustmentModel
/**
 * Model StockAdjustmentItem
 * 
 */
export type StockAdjustmentItem = Prisma.StockAdjustmentItemModel
/**
 * Model Return
 * 
 */
export type Return = Prisma.ReturnModel
/**
 * Model ReturnItem
 * 
 */
export type ReturnItem = Prisma.ReturnItemModel
/**
 * Model Bill
 * 
 */
export type Bill = Prisma.BillModel
/**
 * Model Payment
 * 
 */
export type Payment = Prisma.PaymentModel
