
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const UserRole = {
  ADMIN: 'ADMIN',
  MANAGER: 'MANAGER',
  PURCHASING_STAFF: 'PURCHASING_STAFF',
  WAREHOUSE_STAFF: 'WAREHOUSE_STAFF'
} as const

export type UserRole = (typeof UserRole)[keyof typeof UserRole]


export const ApprovalStatus = {
  DRAFT: 'DRAFT',
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED'
} as const

export type ApprovalStatus = (typeof ApprovalStatus)[keyof typeof ApprovalStatus]


export const POStatus = {
  DRAFT: 'DRAFT',
  PENDING_MANAGER_APPROVAL: 'PENDING_MANAGER_APPROVAL',
  PENDING_PURCHASING_APPROVAL: 'PENDING_PURCHASING_APPROVAL',
  APPROVED: 'APPROVED',
  CONFIRMED: 'CONFIRMED',
  WAITING_PAYMENT: 'WAITING_PAYMENT',
  PAYMENT_RELEASED: 'PAYMENT_RELEASED',
  PO_ISSUED: 'PO_ISSUED',
  SENT_TO_VENDOR: 'SENT_TO_VENDOR',
  PARTIALLY_RECEIVED: 'PARTIALLY_RECEIVED',
  FULLY_RECEIVED: 'FULLY_RECEIVED',
  CANCELLED: 'CANCELLED',
  REJECTED: 'REJECTED'
} as const

export type POStatus = (typeof POStatus)[keyof typeof POStatus]


export const InboundStatus = {
  PENDING_VERIFICATION: 'PENDING_VERIFICATION',
  VERIFIED: 'VERIFIED',
  REJECTED: 'REJECTED'
} as const

export type InboundStatus = (typeof InboundStatus)[keyof typeof InboundStatus]


export const OutboundStatus = {
  DRAFT: 'DRAFT',
  PENDING_APPROVAL: 'PENDING_APPROVAL',
  APPROVED: 'APPROVED',
  RELEASED: 'RELEASED',
  REJECTED: 'REJECTED'
} as const

export type OutboundStatus = (typeof OutboundStatus)[keyof typeof OutboundStatus]


export const StockOpnameStatus = {
  SCHEDULED: 'SCHEDULED',
  COUNTING_IN_PROGRESS: 'COUNTING_IN_PROGRESS',
  PENDING_RECOUNT: 'PENDING_RECOUNT',
  COUNTING_COMPLETE: 'COUNTING_COMPLETE',
  FINALIZED: 'FINALIZED'
} as const

export type StockOpnameStatus = (typeof StockOpnameStatus)[keyof typeof StockOpnameStatus]


export const AdjustmentType = {
  OPNAME_RESULT: 'OPNAME_RESULT',
  MANUAL_WRITEOFF: 'MANUAL_WRITEOFF',
  DAMAGED: 'DAMAGED',
  EXPIRED: 'EXPIRED',
  OTHER: 'OTHER'
} as const

export type AdjustmentType = (typeof AdjustmentType)[keyof typeof AdjustmentType]


export const ReturnReason = {
  LOW_QUALITY: 'LOW_QUALITY',
  DAMAGED: 'DAMAGED',
  OVERSTOCK: 'OVERSTOCK',
  WRONG_ITEM: 'WRONG_ITEM',
  OTHER: 'OTHER'
} as const

export type ReturnReason = (typeof ReturnReason)[keyof typeof ReturnReason]


export const ReturnStatus = {
  DRAFT: 'DRAFT',
  PENDING_APPROVAL: 'PENDING_APPROVAL',
  APPROVED: 'APPROVED',
  SENT_TO_VENDOR: 'SENT_TO_VENDOR',
  COMPLETED: 'COMPLETED',
  REJECTED: 'REJECTED'
} as const

export type ReturnStatus = (typeof ReturnStatus)[keyof typeof ReturnStatus]


export const BillStatus = {
  DRAFT: 'DRAFT',
  PENDING_VERIFICATION: 'PENDING_VERIFICATION',
  VERIFIED: 'VERIFIED',
  PARTIALLY_PAID: 'PARTIALLY_PAID',
  FULLY_PAID: 'FULLY_PAID',
  REJECTED: 'REJECTED'
} as const

export type BillStatus = (typeof BillStatus)[keyof typeof BillStatus]


export const PaymentStatus = {
  PENDING_VALIDATION: 'PENDING_VALIDATION',
  VALIDATED: 'VALIDATED',
  REJECTED: 'REJECTED'
} as const

export type PaymentStatus = (typeof PaymentStatus)[keyof typeof PaymentStatus]


export const StockMovementType = {
  INBOUND: 'INBOUND',
  OUTBOUND: 'OUTBOUND',
  ADJUSTMENT_IN: 'ADJUSTMENT_IN',
  ADJUSTMENT_OUT: 'ADJUSTMENT_OUT',
  RETURN_OUT: 'RETURN_OUT',
  RETURN_IN: 'RETURN_IN'
} as const

export type StockMovementType = (typeof StockMovementType)[keyof typeof StockMovementType]


export const VendorType = {
  SPK: 'SPK',
  NON_SPK: 'NON_SPK'
} as const

export type VendorType = (typeof VendorType)[keyof typeof VendorType]


export const BankName = {
  BCA: 'BCA',
  BRI: 'BRI',
  BNI: 'BNI',
  MANDIRI: 'MANDIRI'
} as const

export type BankName = (typeof BankName)[keyof typeof BankName]


export const InboundDiscrepancyType = {
  NONE: 'NONE',
  SHORTAGE: 'SHORTAGE',
  OVERAGE: 'OVERAGE',
  WRONG_ITEM: 'WRONG_ITEM',
  DAMAGED: 'DAMAGED'
} as const

export type InboundDiscrepancyType = (typeof InboundDiscrepancyType)[keyof typeof InboundDiscrepancyType]


export const DiscrepancyResolution = {
  PENDING: 'PENDING',
  WAIT_REMAINING: 'WAIT_REMAINING',
  CLOSE_SHORT: 'CLOSE_SHORT',
  RETURN_TO_VENDOR: 'RETURN_TO_VENDOR',
  KEEP_EXCESS: 'KEEP_EXCESS',
  REPLACE_ITEM: 'REPLACE_ITEM',
  REFUND: 'REFUND'
} as const

export type DiscrepancyResolution = (typeof DiscrepancyResolution)[keyof typeof DiscrepancyResolution]
